Filter homepage proposals
saltastroops/web-manager-2021 pull request #100
Opened 2022-03-03 07:43 UTC by mofokeng-chaka

2022-03-03 12:14 UTC, hettlage requested changes
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/100)* status: 2 of 5 files reviewed, 21 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[cypress/integration/home/home-user.spec.ts, line 5 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxE0DrA1OGbky9cVmwI:-MxE0DrA1OGbky9cVmwJ:b-4yew6t) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L5)):*
> ```XML
> import { login } from "../../support/utils";
> 
> const USERNAME = "hettlage";
> ```

There is a subtle problem: By restricting tests to my username, you cannot reliably test all functionality. 
___
*[cypress/integration/home/home-user.spec.ts, line 9 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxDsYGTECb75oEdOUJv:-MxDsYGTECb75oEdOUJw:b-iyxze7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L9)):*
> ```XML
> describe("Home User", () => {
>   beforeEach(() => {
>     // Give I am logged in
> ```

Give > Given
___
*[cypress/integration/home/home-user.spec.ts, line 12 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxDsb2W98tSPIh-xTis:-MxDsb2W98tSPIh-xTit:bo2o91n) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L12)):*
> ```XML
>     login(USERNAME);
> 
>     // And I visit a home page
> ```

a home page > the home page
___
*[cypress/integration/home/home-user.spec.ts, line 15 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxE0jPx76cjVmypessF:-MxE0jPx76cjVmypessG:b-oqjp7i) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L15)):*
> ```XML
>     HomePage.visit();
>   });
> ```

It seems you are not testing what happens

* when you click on the "only your proposals" checkbox
* when you click on the "only proposals requiring your attention" checkbox
* when you click on the "only phase 2 proposals" checkbox
* when you click on the "only science proposals" checkbox
* when you click on the "only phase 1 proposals" checkbox
___
*[cypress/integration/home/home-user.spec.ts, line 19 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxDuUcvEftt8PRuo8BV:-MxDuUcvEftt8PRuo8BW:b-61ysua) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L19)):*
> ```XML
>     HomeUser.semesterRangeInputsDisabled(true);
>     HomeUser.semesterSelectDisabled(true);
>     HomeUser.clickRadioButton("current-semester");
> ```

I think your very generic methods like `clickRadioButton` blur the boundary between `home-user.spec.ts` and `home-user.ts`, as they require knowledge of implementation details (such as the data-test attribute) and focus on the _how_, not on the _what_.
___
*[cypress/integration/home/home-user.spec.ts, line 24 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxE6RMS2wBP8RWgZnYR:-MxE6RMS2wBP8RWgZnYS:bmxla2a) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L24)):*
> ```XML
> 
>   it("should filter proposals table by the next semester when the next semester radio button is clicked", () => {
>     HomeUser.semesterRangeInputsDisabled(true);
> ```

There is somewhat of a bug here... The option should be "Show proposals for the current and next semester".
___
*[cypress/integration/home/home-user.spec.ts, line 31 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxDvmq6Azccusewwt2f:-MxDvmq6Azccusewwt2g:b-xufn18) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L31)):*
> ```XML
> 
>   it(
>     "should filter proposals table by the input semester range when semester range radio button is clicked " +
> ```

when semester > when the semester
___
*[cypress/integration/home/home-user.spec.ts, line 39 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxDvZ6r43W8IaTSg6j6:-MxDvZ6r43W8IaTSg6j7:betudx6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L39)):*
> ```XML
>       HomeUser.semesterRangeInputsDisabled(false);
>       HomeUser.semesterSelectDisabled(true);
>       HomeUser.typeSemesterRange(start_semester, end_semester);
> ```

You should also test the case that only the start or end semester is given
___
*[cypress/integration/home/home-user.spec.ts, line 86 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxE8yRg1Y13UYOoOkZk:-MxE8yRg1Y13UYOoOkZl:b-26sdn9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L86)):*
> ```XML
>   });
> 
>   it("should filter proposals table to show only rejected proposals when the rejected checkbox is clicked", () => {
> ```

But the checkbox is for "rejected, completed and expired" proposals. So the test and probably the WM code might need some updating.
___
*[cypress/integration/home/home-user.spec.ts, line 96 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxE07ZKEbhjMZg-PWM9:-MxE07ZKEbhjMZg-PWMA:b26rhd1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L96)):*
> ```XML
>   });
> 
>   it("should filter proposals table to show only ddt proposals when the ddt checkbox is clicked", () => {
> ```

only ddt >only  DDT
___
*[cypress/support/components/home-user.ts, line 17 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxDt2sQDqYIU2vJV1VH:-MxDt2sQDqYIU2vJV1VI:b-u9qxga) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/support/components/home-user.ts#L17)):*
> ```XML
>   }
> 
>   static typeSemesterRange(start_semester: string, end_semester: string): void {
> ```

What about the case that you only provide one of the two semesters?
___
*[cypress/support/components/home-user.ts, line 30 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxDteYv6w_zpebYyT2u:-MxDteYv6w_zpebYyT2v:b-jmeva3) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/support/components/home-user.ts#L30)):*
> ```XML
>   }
> 
>   static filteredBySingleSemester(): void {
> ```

Couldn't you pass the semester as an argument and then check that every proposal is for that proposal (like you do in `filteredBySemesterRange`)?
___
*[cypress/support/components/home-user.ts, line 77 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxEAOh41vpQbpeZKNNL:-MxEAOh41vpQbpeZKNNM:btdwb67) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/support/components/home-user.ts#L77)):*
> ```XML
>   }
> 
>   static filteredProposalsBy(filter: string): void {
> ```

Maybe rather split this up into different functions?
___
*[cypress/support/components/home-user.ts, line 82 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxE-j9H8OWY4n5D3X8I:-MxE-j9I0z8OCOakT0c6:b-46i7li) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/support/components/home-user.ts#L82)):*
> ```XML
>         cy.get(PROPOSAL_STATUSES).each(($el) => {
>           const status = $el.text();
>           expect(status).to.be.emp [...]

2022-03-08 08:00 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/100)* status: 2 of 5 files reviewed, 21 unresolved discussions (waiting on @hettlage)

___
*[cypress/integration/home/home-user.spec.ts, line 5 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxE0DrA1OGbky9cVmwI:-MxZPdzv8VtjtxkZ40jW:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is a subtle problem: By restricting tests to my username, you cannot reliably test all functionality. 
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 9 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxDsYGTECb75oEdOUJv:-MxEy0z2CVQqKBJWArf5:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Give > Given
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 12 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxDsb2W98tSPIh-xTis:-MxEy1eE1txBQoC112Cr:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

a home page > the home page
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 15 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxE0jPx76cjVmypessF:-MxZWGek0y5b8kJBtDMl:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It seems you are not testing what happens

* when you click on the "only your proposals" checkbox
* when you click on the "only proposals requiring your attention" checkbox
* when you click on the "only phase 2 proposals" checkbox
* when you click on the "only science proposals" checkbox
* when you click on the "only phase 1 proposals" checkbox

</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 19 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxDuUcvEftt8PRuo8BV:-MxZWHkX0Wpwg7sctkKw:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think your very generic methods like `clickRadioButton` blur the boundary between `home-user.spec.ts` and `home-user.ts`, as they require knowledge of implementation details (such as the data-test attribute) and focus on the _how_, not on the _what_.
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 24 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxE6RMS2wBP8RWgZnYR:-MxZfF9xABIyETCW6o9_:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is somewhat of a bug here... The option should be "Show proposals for the current and next semester".
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 31 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxDvmq6Azccusewwt2f:-MxEyoSHBLQS7--8VcRp:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

when semester > when the semester
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 39 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxDvZ6r43W8IaTSg6j6:-MxcUZ_d55gpo17_9j6G:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should also test the case that only the start or end semester is given
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 86 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxE8yRg1Y13UYOoOkZk:-MxcUc2F0ZHe68G2aA27:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L86)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But the checkbox is for "rejected, completed and expired" proposals. So the test and probably the WM code might need some updating.
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 96 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxE07ZKEbhjMZg-PWM9:-MxcUcb5ENzjatCmG48J:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L96)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

only ddt >only  DDT
</blockquote></details>

Done.
___
*[cypress/support/components/home-user.ts, line 17 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxDt2sQDqYIU2vJV1VH:-MxcUfnI9Asfr2g5r_bX:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/support/components/home-user.ts#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What about the case that you only provide one of the two semesters?
</blockquote></details>

Done.
___
*[cypress/support/components/home-user.ts, line 30 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxDteYv6w_zpebYyT2u:-MxOt9pK8ZscNykCVsAw:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/support/components/home-user.ts#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Couldn't you pass the semester as an argument and then check that every proposal is for that proposal (like you do in `filteredBySemesterRange`)?
</blockquote></details>

Done.
___
*[cypress/support/components/home-user.ts, line 77 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxEAOh41vpQbpeZKNNL:-MxOtBRDEsgSdYA92MLi:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/support/components/home-user.ts#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe rather split this up into different functions?
</blockquote></details>

Done.
___
*[cypress/support/components/home-user.ts, line 82 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxE-j9H8OWY4n5D3X8I:-MxcUhEz2fVWcCpVMzv9:bqeu8ud) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/support/components/home-user.ts#L82)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This looks wrong...
</blockquote></details>

I have fixed it now.
___
*[src/app/home/home-user/home-user.component.ts, line 27 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxEXKYV-iWIJa3KJXO3:-MxcUnJ8Bx09seqoWsAU:b-896fix) ([raw file](http [...]

2022-03-09 08:04 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/100)* status: all files reviewed, 48 unresolved discussions (waiting on @mofokeng-chaka)

___
*[src/app/home/home-user/home-user.component.ts, line 68 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mxhh6yi5oB3qjafWFS0:-Mxhh6yi5oB3qjafWFS1:bse6twy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/92f194009e90a89c355a0685d122f0087b3f16f1/src/app/home/home-user/home-user.component.ts#L68)):*
> ```XML
>       });
> 
>     this.user$
> ```

Do you need an extra observable?


<!-- Sent from Reviewable.io -->

2022-03-13 06:47 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/100)* status: 1 of 6 files reviewed, 48 unresolved discussions (waiting on @hettlage)

___
*[cypress/integration/home/home-user.spec.ts, line 5 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxE0DrA1OGbky9cVmwI:-MxwEM-v5FYm8E9DL5wZ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think you need multiple usernames.
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 24 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxE6RMS2wBP8RWgZnYR:-MxhWY47Dq0NESi3Z_Am:bb4azs7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ce995e8b6c4cde46fb7e6122cc62934dfc5acf4/cypress/integration/home/home-user.spec.ts#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm afraid this does not seem to be resolved yet.
</blockquote></details>

Oh right, now I see what you meant, it should be fixed now.
___
*[cypress/integration/home/home-user.spec.ts, line 31 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxdGj2w9z6CAkgYW-6O:-Mxt3qFHC7fL9H_TMCwD:bjam3s4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/92f194009e90a89c355a0685d122f0087b3f16f1/cypress/integration/home/home-user.spec.ts#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If you want to test the local storage, I'd suggest you reload the page and then check the correct radio button is selected and / or the correct proposals are shown. (But this should be treated in a different test?)

But I feel you haven't addressed the concern: The option should be for the current and the next semester combined, not just for the next semester,
</blockquote></details>

It should be fixed now.
___
*[cypress/integration/home/home-user.spec.ts, line 60 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxdHvKI0ozmR5SRpPXA:-MxhdJRN5bEqhlwksKdV:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/92f194009e90a89c355a0685d122f0087b3f16f1/cypress/integration/home/home-user.spec.ts#L60)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

contain > contains ?

Checking for the entire error message makes the test a bit brittle.
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 60 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxdIHJs0plosi77EsS4:-MxhdJxRBYYj9Kkf_ArL:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/92f194009e90a89c355a0685d122f0087b3f16f1/cypress/integration/home/home-user.spec.ts#L60)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This may sound like nit-picking, but wouldn't something like "Please supply a start and/or end semester." be clearer?
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 64 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxdIVuK8id0FDdsETNS:-MxhdRHg1aGjv4smX3GX:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/92f194009e90a89c355a0685d122f0087b3f16f1/cypress/integration/home/home-user.spec.ts#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

the wrong > a wrong
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 72 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxdI0Xw8UA_1UIeZVaW:-MxhdSEa4qE3egc7fBxW:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/92f194009e90a89c355a0685d122f0087b3f16f1/cypress/integration/home/home-user.spec.ts#L72)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

contain > contains
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 73 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxdJ0524ysjY3v048UE:-MxhdWYR6jOuMYNwf-X8:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/92f194009e90a89c355a0685d122f0087b3f16f1/cypress/integration/home/home-user.spec.ts#L73)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Checking for the entire error message makes the test a bit brittle.
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 79 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxdJH_bBgFt5x02DcLD:-MxheFxnBHoZvmTfW-ed:b-yvjvut) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/92f194009e90a89c355a0685d122f0087b3f16f1/cypress/integration/home/home-user.spec.ts#L79)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the description can be shortened - clicking buttons isn't overly relevant... :-)

Also "current semester" is presumably wrong. Wouldn't future semesters be included as well?
</blockquote></details>

You're right future semesters are also included. Thanks!
___
*[cypress/integration/home/home-user.spec.ts, line 91 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxdKeCh0ppx5q2ZYXpY:-Mxt4B4N2jKrTWxmHt63:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/92f194009e90a89c355a0685d122f0087b3f16f1/cypress/integration/home/home-user.spec.ts#L91)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What about the case when only an end semester is given? And the case when both start and end semester are given?
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 94 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxdKtMS0znUZY31n2YF:-Mxt4_KPE06HL-0DcLvC:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/92f194009e90a89c355a0685d122f0087b3f16f1/cypress/integration/home/home-user.spec.ts#L94)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"single semester range" sounds odd. Shouldn't that be just "single semester"?
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 102 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxdLtIj7-H8M4alDgPu:-Mxt4b3_DqMAFBbeAnMY:b-xb2mys) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/92f194009e90a89c355a0685d122f0087b3f16f1/cypress/integration/home/home-user.spec.ts#L102)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't know, but concatenating strings in the description looks a bit odd to meat
</blockquote></details>

Fixed it now.
___
*[cypress/integration/home/home-user.spec.ts, line 106 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxdLYtf5tohOkoPGTXI:-Mxt5TMb1A4yNiQb13xW:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/92f194009e90a89c355a0685d122f0087b3f16f1/cypress/integration/home/home-user.spec.ts#L106)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

A general comment: You are repeating some test assertions over and over again, which might not be necessary.
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 126 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxdOm8DDxzsglFfl94K:-Mxt5UAl7bQWl1Pos9PZ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/92f194009e90a89c355a0685d122f0087b3f16f1/cypress/integration/home/home-user.spec.ts#L126)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See my comment on testing local storage and current/next semester above.
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 13 [...]

2022-03-14 12:37 UTC, hettlage requested changes
> Reviewed 3 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/100)* status: 5 of 6 files reviewed, 51 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[cypress/integration/home/home-user.spec.ts, line 173 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxdR68W2XTKxQoNRMv3:-My3kxvO44y6k1IYesXm:b-j2rxf5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/92f194009e90a89c355a0685d122f0087b3f16f1/cypress/integration/home/home-user.spec.ts#L173)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope, I think I can still see "ddt"?
___
*[cypress/integration/home/home-user.spec.ts, line 6 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-My3cb-Z8n_ONRGj6nLs:-My3cb-_-OLM0qLZnZsV:b-wog2ik) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L6)):*
> ```XML
> import { login } from "../../support/utils";
> 
> const USERNAMES = ["cmofokeng", "dibnob", "MoSalt", "skelton"];
> ```

I think usernames should be avoided in the source code -- at least id the users don't know about it.
___
*[cypress/integration/home/home-user.spec.ts, line 8 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-My3coyo1Oolg5mXsUZm:-My3coyo1Oolg5mXsUZn:b-hjx5xy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L8)):*
> ```XML
> const USERNAMES = ["cmofokeng", "dibnob", "MoSalt", "skelton"];
> 
> USERNAMES.forEach((username) => {
> ```

While clever, I'm not sure one should loop over all users for all tests. So maybe in this case having a beforeEach method is not the way to go?
___
*[cypress/integration/home/home-user.spec.ts, line 23 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-My3kDSk3wWZqkklabC2:-My3kDSk3wWZqkklabC3:b-f587b4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L23)):*
> ```XML
>       HomeUser.semesterSelectDisabled(true);
>       HomeUser.clickCurrentSemesterRadioButton();
>       cy.wait(2000);
> ```

Do you really have to use all these explicit waits in the tests?
___
*[cypress/integration/home/home-user.spec.ts, line 66 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-My3epEIEO0WVZIx_SZZ:-My3epEIEO0WVZIx_SZ_:b-uoa70p) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L66)):*
> ```XML
>     });
> 
>     it("should show proposals for the given input start semester to future semesters", () => {
> ```

Maybe better?: "should show proposals from the given input start semester onwards"

But I think there is an issue: If, say, only proposals for the start semester were shown, the test would still pass, wouldn't it? And the same would be true, if an empty list was shown, wouldn't it?

(Similar concerns apply to other tests as well.)
___
*[cypress/integration/home/home-user.spec.ts, line 69 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-My3fPZO1DZd0KG86FLw:-My3fPZO1DZd0KG86FLx:b-7t7vp9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L69)):*
> ```XML
>       const start_semester = "2018-1";
>       HomeUser.clickSemesterRangeRadioButton();
>       HomeUser.typeSemesterRange(start_semester, "");
> ```

typeSemesterRange > typeSemesterRanges ?
___
*[cypress/integration/home/home-user.spec.ts, line 75 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-My3fX6Y8iYJsbWaetWq:-My3fX6Y8iYJsbWaetWr:bs1sv32) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L75)):*
> ```XML
>     });
> 
>     it("should show proposals from the past semesters to the given input end semester", () => {
> ```

Maybe better: "should show proposals up to the given input semester"
___
*[cypress/integration/home/home-user.spec.ts, line 76 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-My3fsBn3hc3ZX6GbUtA:-My3fsBo7s3x1Rcb8LLh:bi4tcdu) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L76)):*
> ```XML
> 
>     it("should show proposals from the past semesters to the given input end semester", () => {
>       const start_semester = "2018-1";
> ```

Shouldn't that be the end semester?
___
*[cypress/integration/home/home-user.spec.ts, line 94 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-My3gbyu2PnNztCGIyMf:-My3gbyu2PnNztCGIyMg:bub1yqe) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L94)):*
> ```XML
>     });
> 
>     it("should show proposals for the selected semester when the semester is selected from the options and the page is reloaded", () => {
> ```

Shouldn't there be equivalent tests for the other options? Also, you could test in addition that the input elements show the correct value.
___
*[cypress/integration/home/home-user.spec.ts, line 157 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-My3kb5gE3gXZV9sisV7:-My3kb5gE3gXZV9sisV8:bhats7h) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L157)):*
> ```XML
>     });
> 
>     it("should show no proposals when the deleted checkbox is clicked", () => {
> ```

It should show no proposals? That sounds wrongs -- it should show deleted proposals.
___
*[cypress/integration/home/home-user.spec.ts, line 202 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-My3lDvJ6QvHfIGW9Hfb:-My3lDvJ6QvHfIGW9Hfc:be9w7kr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L202)):*
> ```XML
>     });
> 
>     it("should show current and next semester, and unchecked proposals", () => {
> ```

That sounds a bit as if you test two features in the same test...
___
*[cypress/plugins/index.ts, line 21 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-My3mGUcDvMc16kiefMJ:-My3mGUcDvMc16kiefMK:btj7sch) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/plugins/index.ts#L21)):*
> ```XML
> // https://www.cypress.io/blog/2021/05/11/testing-html-emails-using-cypress/
> 
> // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
> ```

Is this disabling necessary or could you just choose `any` as the type of `on`? 
___
*[cypress/support/components/home-user.ts, line 59 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxdU8tHE-ibSHdJImkX:-My7PPZl2KavI0mZWGeq:bxln2dh) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/92f194009e90a89c355a0685d122f0087b3f16f1/cypress/support/components/home-user.ts#L59)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I don't think that would be necessary. I am expecting the list of rows not to be empty for all the cases (given the input start and/or end semester) except when the input semester format is wrong and in that case, an alert is expected to be shown.
</blockquote></details>

But how do you know -- but maybe we should chat about this?
___
*[cypress/support/components/home-user.ts, line 100 at r2](https://reviewable.io/revie [...]

2022-03-17 20:11 UTC, hettlage requested changes
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/100)* status: all files reviewed, 32 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[cypress/integration/home/home-user.spec.ts, line 20 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNE_i77GQMUbFHxQWO:-MyNE_iABfRStgU2P2SL:b-p1rube) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L20)):*
> ```XML
> 
>     it("should show proposals for the current semester", () => {
>       HomeUser.semesterRangeInputsDisabled(true);
> ```

The test is failing.
___
*[cypress/integration/home/home-user.spec.ts, line 69 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-My3fPZO1DZd0KG86FLw:-MyNOFk05jLQpgDFRiEr:bxph67k) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L69)):*
> You're correct with your first point, the tests will still pass if only proposals for the start semester were shown, and this would be the case only if you have over 1000 semesters belonging to that specific start semester. In that case, I think the test is fine and generalizes well for this specific case.

But this statement assumes that the code is working -- and this is what you want to test.

(Of course this applies to the next test as well.)
___
*[cypress/integration/home/home-user.spec.ts, line 94 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-My3gbyu2PnNztCGIyMf:-MyNPCJjCzWFtDINimk-:bs9d8i7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L94)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think you check that the input fields / checkboxes are set correctly after reloading?
___
*[cypress/integration/home/home-user.spec.ts, line 65 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNNLbO4vYzATSgHYTF:-MyNNLbO4vYzATSgHYTG:bd4t1u) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/cypress/integration/home/home-user.spec.ts#L65)):*
> ```XML
>   });
> 
>   it("should show proposals for the given input semester range when the page is reloaded after clicking the semester range filter", () => {
> ```

This test (I think) is crashing Cypress, at least for me.
___
*[cypress/plugins/database.ts, line 10 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNQRfaBGKQmyNOBq_0:-MyNQRfaBGKQmyNOBq_1:b-3ysrmo) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/cypress/plugins/database.ts#L10)):*
> ```XML
>  * resolves to the new password.
>  */
> export function updateUserPassword(username: string): unknown {
> ```

I think you should avoid the `unknown` type -- you can be more specific than this.
___
*[cypress/support/components/home-user.ts, line 59 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxdU8tHE-ibSHdJImkX:-MyOQvjq3Cc508g8ffJd:bt6lln7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/92f194009e90a89c355a0685d122f0087b3f16f1/cypress/support/components/home-user.ts#L59)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Now I know this because every time a user tries to filter by semester range, a new filtered list is requested and the list of rows cannot be empty.
</blockquote></details>

If the code is working -- but this is what you are testing...
___
*[cypress/support/components/home-user.ts, line 80 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNRD9r2YPrBPW2c2ov:-MyNRD9r2YPrBPW2c2ow:b-yhaomw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/cypress/support/components/home-user.ts#L80)):*
> ```XML
> 
>   static filteredByCurrentAndNextSemester(): void {
>     let current_semester = "";
> ```

There are two problems here, I think:

* There is too much logic for a test ("you'd need a unit test to test this unit test").
* The date is not frozen.
___
*[cypress/support/components/home-user.ts, line 102 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNSEVs3lFbQynpA7L9:-MyNSEVs3lFbQynpA7LA:bq8hocs) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/cypress/support/components/home-user.ts#L102)):*
> ```XML
>       semesters.push(semester);
>     });
>     semesters.forEach((semester) =>
> ```

Given the async nature of Cypress, I'd guess you are checking an empty list of semesters here.
___
*[cypress/support/components/home-user.ts, line 195 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNSx5gC_FFExwxE0L2:-MyNSx5gC_FFExwxE0L3:bb04vin) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/cypress/support/components/home-user.ts#L195)):*
> ```XML
>     cy.task("getUser", username).then((user) => {
>       cy.get(PROPOSAL_TABLE_ROWS).then(() => {
>         cy.get(LIAISON_ASTRONOMER).each(($el) => {
> ```

If there are proposals with the correct liaison astronomer which are not under technical/scientific review, the test would still pass.
___
*[cypress/support/components/home-user.ts, line 293 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNTRqpB2v8dYFpMlCe:-MyNTRqq8uGQAr8bHhjH:b-l38ewj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/cypress/support/components/home-user.ts#L293)):*
> ```XML
>         });
> 
>         investigators.forEach((investigator, index) => {
> ```

Given the async nature of Cypress , I'd guess you are checking an empty list of investigators.
___
*[src/app/home/home-user/home-user.component.ts, line 32 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNX84M4l2giPYnUEoj:-MyNX84M4l2giPYnUEok:b-8u54ng) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/src/app/home/home-user/home-user.component.ts#L32)):*
> ```XML
>   semesterFilter = "";
>   otherFilterByProperties: { [elementId: string]: string } = {};
>   /* eslint-disable */
> ```

I don't think it's a good idea to disable ESLint.
___
*[src/app/home/home-user/home-user.component.ts, line 49 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNXg-_8lrLKZWUPU2g:-MyNXg-_8lrLKZWUPU2h:b-bilc91) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/src/app/home/home-user/home-user.component.ts#L49)):*
> ```XML
>     this.loadFilters();
> 
>     this.filterFunctions["unassigned"] = (proposals: ProposalListItem[]) =>
> ```

I think this can be simplified:

```
this.filterFunctions["unassigned"] =  this.filterUnassignedProposals
```

Analogously for most of the other cases.
___
*[src/app/home/home-user/home-user.component.ts, line 88 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNYJZY96zN0z__KPeY:-MyNYJZY96zN0z__KPeZ:b-rnesar) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/src/app/home/home-user/home-user.component.ts#L88)):*
> ```XML
>       .subscribe(
>         (p) => {
>           this.proposals = p;
> ```

`this.filteredProposals` should rather be a copy of `this.proposals`.
___
*[src/app/home/home-user/home-user.component.ts, line 93 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNYkPH3elM7an2b0_p:-MyNYkPH3elM7an2b0_q:b-9hwg1z) ([raw file](https://github.com/saltastroops/web-manager- [...]

2022-03-22 13:17 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/100)* status: 6 of 13 files reviewed, 32 unresolved discussions (waiting on @hettlage)

___
*[cypress/integration/home/home-user.spec.ts, line 20 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNE_i77GQMUbFHxQWO:-MyQpz2v4-eK5CtQw_V7:b-s8a3bt) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The test is failing.
</blockquote></details>

That's weird because all the tests are passing on my side.
___
*[cypress/integration/home/home-user.spec.ts, line 69 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-My3fPZO1DZd0KG86FLw:-MyfvLcwEVdozYuEWP2t:b-kf5tyg) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L69)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

> You're correct with your first point, the tests will still pass if only proposals for the start semester were shown, and this would be the case only if you have over 1000 semesters belonging to that specific start semester. In that case, I think the test is fine and generalizes well for this specific case.

But this statement assumes that the code is working -- and this is what you want to test.

(Of course this applies to the next test as well.)
</blockquote></details>

I have added a test to check if unique semesters are returned.
___
*[cypress/integration/home/home-user.spec.ts, line 94 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-My3gbyu2PnNztCGIyMf:-MylkKYe5egLWQJwo3D9:b1s99tg) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L94)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you check that the input fields / checkboxes are set correctly after reloading?
</blockquote></details>

They should be checked now.
___
*[cypress/integration/home/home-user.spec.ts, line 65 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNNLbO4vYzATSgHYTF:-MyQtTPf1EcednpnEeKa:b-448ym5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/cypress/integration/home/home-user.spec.ts#L65)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This test (I think) is crashing Cypress, at least for me.
</blockquote></details>

That's weird because it doesn't on my side. Also, this is the only test that was failing now and the solution was to wait after reloading the page.

PS: I noted is that cypress is inconsistent especially when you open the browser and run the tests from there using the `cypress open` command. It is better to run the tests using the `cypress run` command instead. 
___
*[cypress/plugins/database.ts, line 10 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNQRfaBGKQmyNOBq_0:-Myfs-pb6VNHcAGqODQe:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/cypress/plugins/database.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think you should avoid the `unknown` type -- you can be more specific than this.
</blockquote></details>

Done.
___
*[cypress/support/components/home-user.ts, line 59 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MxdU8tHE-ibSHdJImkX:-Mylkk7L90Fj7BBm0vJY:b4e63gq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/92f194009e90a89c355a0685d122f0087b3f16f1/cypress/support/components/home-user.ts#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If the code is working -- but this is what you are testing...
</blockquote></details>

I have added some changes, hoping they do what you suggest.
___
*[cypress/support/components/home-user.ts, line 80 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNRD9r2YPrBPW2c2ov:-Myfs49pCk2g3A_kGeD-:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/cypress/support/components/home-user.ts#L80)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There are two problems here, I think:

* There is too much logic for a test ("you'd need a unit test to test this unit test").
* The date is not frozen.
</blockquote></details>

Done.
___
*[cypress/support/components/home-user.ts, line 102 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNSEVs3lFbQynpA7L9:-MyR2XPtD9Z8rzqNpO6M:bu3xvt2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/cypress/support/components/home-user.ts#L102)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given the async nature of Cypress, I'd guess you are checking an empty list of semesters here.
</blockquote></details>

You might be correct, however, I think cypress would raise an error and fail the test if `cy.get(PRINCIPAL_INVESTIGATOR)` return an empty list/array.
___
*[cypress/support/components/home-user.ts, line 195 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNSx5gC_FFExwxE0L2:-MyR5LGy7CO2BS1WY6P9:b-gd4jij) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/cypress/support/components/home-user.ts#L195)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If there are proposals with the correct liaison astronomer which are not under technical/scientific review, the test would still pass.
</blockquote></details>

I have added another test to check for correct proposal statuses.
___
*[cypress/support/components/home-user.ts, line 293 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNTRqpB2v8dYFpMlCe:-MyR0mSG3e_Uzfg8Yb8y:bu3xvt2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/cypress/support/components/home-user.ts#L293)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given the async nature of Cypress , I'd guess you are checking an empty list of investigators.
</blockquote></details>

You might be correct, however, I think cypress would raise an error and fail the test if `cy.get(PRINCIPAL_INVESTIGATOR)` return an empty list/array.
___
*[src/app/home/home-user/home-user.component.ts, line 32 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNX84M4l2giPYnUEoj:-MyR5zsGD4vQkp9V7zSZ:b-wxzx16) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/src/app/home/home-user/home-user.component.ts#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think it's a good idea to disable ESLint.
</blockquote></details>

You're right, I have changed this to disable eslint for the next line only.
___
*[src/app/home/home-user/home-user.component.ts, line 49 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNXg-_8lrLKZWUPU2g:-MyR8Dvi96FjZENGI0HA:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/src/app/home/home-user/home-user.component.ts#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think this can be simplified:

```
this.filterFunctions["unassigned"] =  this.filterUnassignedProposals
```

Analogously for most of the other cases.
</blockquote></details>

Done.
___
*[src/app/home/home-user/home-user.component.ts, line 88 at r5](https://reviewable.io/reviews/saltastroops/web-m [...]

2022-03-22 18:53 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/100)* status: all files reviewed, 35 unresolved discussions (waiting on @mofokeng-chaka)

___
*[cypress/integration/home/home-user.spec.ts, line 20 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNE_i77GQMUbFHxQWO:-MymyReeApUFaIkne5WO:b-sw127r) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L20)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

That's weird because all the tests are passing on my side.
</blockquote></details>

5 tests are failing for me (when using cypress run).
___
*[cypress/integration/home/home-user.spec.ts, line 13 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym-XULA1huc36C0gJC:-Mym-XULA1huc36C0gJD:baak41a) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/integration/home/home-user.spec.ts#L13)):*
> ```XML
>     login(USERNAME);
> 
>     HomeUser.freezeDate(2021, 6);
> ```

I doubt this works, as you are replacing the method on an instance in `freezeDate`. But it turns out that Cypress gas a function for freezing time, `cy.clock`. See https://docs.cypress.io/api/commands/clock.
___
*[cypress/integration/home/home-user.spec.ts, line 24 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MylyTcr1xhDVL-M96Do:-MylyTcr1xhDVL-M96Dp:byg9465) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/integration/home/home-user.spec.ts#L24)):*
> ```XML
>     cy.on("window:alert", (text) => {
>       expect(text).contains(
>         "1000 or more proposals ratify the filter criteria.",
> ```

ratify > satisfy
___
*[cypress/integration/home/home-user.spec.ts, line 157 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym1jiH80toDPnxlzfj:-Mym1jiH80toDPnxlzfk:b-z70rxa) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/integration/home/home-user.spec.ts#L157)):*
> ```XML
>     HomeUser.filteredUncheckedProposals();
>     cy.reload();
>     HomeUser.uncheckedCheckboxChecked(true);
> ```

Do you really mean _unchecked_ CheckboxChecked?
___
*[cypress/integration/home/home-user.spec.ts, line 275 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym2TB-7Qp8uAQk-nAh:-Mym2TB-7Qp8uAQk-nAi:b-bjf42g) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/integration/home/home-user.spec.ts#L275)):*
> ```XML
>     HomeUser.semesterRangeInputsDisabled(true);
>     HomeUser.semesterSelectDisabled(true);
>     HomeUser.freezeDate(2021, 6);
> ```

See comment on `freezeDate` above.
___
*[cypress/plugins/database.ts, line 10 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNQRfaBGKQmyNOBq_0:-Mym3-Ev9M19mgnG70fk:bvvly48) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/cypress/plugins/database.ts#L10)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Isn't this a `Promise<string>`?
___
*[cypress/plugins/database.ts, line 65 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym3_ET-GhI3bIfzCUX:-Mym3_ET-GhI3bIfzCUY:b9o32sp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/plugins/database.ts#L65)):*
> ```XML
> export function clearObservationComments(
>   proposalCode: string,
> ): Promise<unknown> {
> ```

Isn't this a `Promise<boolean>`?
___
*[cypress/support/components/home-user.ts, line 293 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNTRqpB2v8dYFpMlCe:-Mym7-JAE_vflWdyEHA7:b-sfuw20) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/cypress/support/components/home-user.ts#L293)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

You might be correct, however, I think cypress would raise an error and fail the test if `cy.get(PRINCIPAL_INVESTIGATOR)` return an empty list/array.
</blockquote></details>

I'm not denying this. But the problem is that you are checking the investigators array before it has been populated.
___
*[cypress/support/components/home-user.ts, line 37 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym4OUNEj6hK_nvoghH:-Mym4OUOACnCp8lZ5Lha:b-m8yq5p) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/support/components/home-user.ts#L37)):*
> ```XML
> 
> export class HomeUser {
>   static freezeDate(year: number, month: number): void {
> ```

See comment in `home-user.spec.ts`.
___
*[cypress/support/components/home-user.ts, line 160 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym4mD7BM2kgSr32X_M:-Mym4mD7BM2kgSr32X_N:b7nsgv) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/support/components/home-user.ts#L160)):*
> ```XML
>         expect(Array.from(new Set(semesters)).length > 1).to.be.true;
> 
>         semesters.forEach((semester) => {
> ```

There are still potential loopholes here -- if only a single semester was returned, you wouldn't notice.
___
*[cypress/support/components/home-user.ts, line 341 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym5kd69MzW6-vOJqcZ:-Mym5kd69MzW6-vOJqc_:bn8w24h) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/support/components/home-user.ts#L341)):*
> ```XML
>   static filteredProposalsRequiringAttention(username: string): void {
>     cy.task("getUser", username).then((user) => {
>       cy.get(PROPOSAL_TABLE_ROWS).then(() => {
> ```

I don't think the `cy.get(PROPOSAL_TABLE_ROWS)` is necessary?
___
*[cypress/support/components/home-user.ts, line 435 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym6KEAD401YiRChQjb:-Mym6KEAD401YiRChQjc:bn8w24h) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/support/components/home-user.ts#L435)):*
> ```XML
>     const astronomers = [];
>     cy.task("getUser", username).then((user) => {
>       cy.get(PROPOSAL_TABLE_ROWS).then(() => {
> ```

I don't think the `cy.get(PROPOSAL_TABLE_ROWS)` is necessary?
___
*[src/app/home/home-user/home-user.component.html, line 55 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym7cxbB01A8ffQTKJH:-Mym7cxbB01A8ffQTKJI:b-maxso9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/src/app/home/home-user/home-user.component.html#L55)):*
> ```HTML
>       type="text"
>       id="start_semester"
>       [value]="startSemesterValue"
> ```

Why not `startSemester`?

Oh, I see you have two variables for this. But I'm pretty sure you only need one.
___
*[src/app/home/home-user/home-user.component.html, line 58 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym7T2O3Jk7Cxqqe7sT:-Mym7T2PBin653GIHigZ:bi4abln) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/src/app/home/home-user/home-user.component.html#L58)):*
> ```HTML
>       placeholder="yyyy-s"
>       data-test="start-semester"
>       [(ngModel)]="startSemesterValue"
> ```

I'd avoid double-binding.
___
*[src/app/home/home-user/home-user.component.html, line 65 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym7Zyo-Mw-7_-PGU8I:-Mym7Z [...]

2022-03-23 19:51 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/100)* status: 7 of 13 files reviewed, 35 unresolved discussions (waiting on @hettlage)

___
*[cypress/integration/home/home-user.spec.ts, line 20 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNE_i77GQMUbFHxQWO:-MyprnmCADHIzfAF8Vyc:b-v73phk) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

5 tests are failing for me (when using cypress run).
</blockquote></details>

Cypress is very inconsistent then, all the tests are passing on my side. Another thing to try is running the tests more than once, I realized that for some weird reason, sometimes the tests fail on the first run but they pass on following runs.
___
*[cypress/integration/home/home-user.spec.ts, line 13 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym-XULA1huc36C0gJC:-MypobjnEZF8MO5_vUfM:b-nf5wl1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/integration/home/home-user.spec.ts#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I doubt this works, as you are replacing the method on an instance in `freezeDate`. But it turns out that Cypress gas a function for freezing time, `cy.clock`. See https://docs.cypress.io/api/commands/clock.
</blockquote></details>

Well, it does work, in fact, I tried using `cy.clock` before and it didn't work. Maybe it could be the case of different function scopes and the fact that it is being used in the different scripts but It didn't override the current date-time and as such tests failed. The tests only passed when I used `cy.stub` which let me control the behaviour of the `Date`methods.
___
*[cypress/integration/home/home-user.spec.ts, line 24 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MylyTcr1xhDVL-M96Do:-MyprhLwE4372_C5d4Ei:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/integration/home/home-user.spec.ts#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

ratify > satisfy
</blockquote></details>

Done.
___
*[cypress/integration/home/home-user.spec.ts, line 157 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym1jiH80toDPnxlzfj:-MyqChB8E2P-kRGD5Nfl:b-bqyih2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/integration/home/home-user.spec.ts#L157)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do you really mean _unchecked_ CheckboxChecked?
</blockquote></details>

I see the point you are making, I have changed this name.
___
*[cypress/integration/home/home-user.spec.ts, line 275 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym2TB-7Qp8uAQk-nAh:-Mypt8BxDMhw3QZs6vBf:bcknpq3) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/integration/home/home-user.spec.ts#L275)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comment on `freezeDate` above.
</blockquote></details>

See my reply to that comment.
___
*[cypress/plugins/database.ts, line 10 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNQRfaBGKQmyNOBq_0:-MyptYjl69R0Hk6BS1MW:b-87rmoq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/cypress/plugins/database.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't this a `Promise<string>`?
</blockquote></details>

That is correct.
___
*[cypress/plugins/database.ts, line 65 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym3_ET-GhI3bIfzCUX:-Mypthwz70bXz78YIBf7:b-87rmoq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/plugins/database.ts#L65)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't this a `Promise<boolean>`?
</blockquote></details>

That is correct.
___
*[cypress/support/components/home-user.ts, line 293 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNTRqpB2v8dYFpMlCe:-MyqGoEqBwUdXxJkyqTd:b-m6q92u) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/cypress/support/components/home-user.ts#L293)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not denying this. But the problem is that you are checking the investigators array before it has been populated.
</blockquote></details>

You're right and have changed this accordingly.
___
*[cypress/support/components/home-user.ts, line 37 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym4OUNEj6hK_nvoghH:-MyqCreI4zU1HkzK3hZL:b-q4a0hr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/support/components/home-user.ts#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comment in `home-user.spec.ts`.
</blockquote></details>

See mine as well
___
*[cypress/support/components/home-user.ts, line 160 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym4mD7BM2kgSr32X_M:-MypttRr-5DUinvOh15T:b-3b54f8) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/support/components/home-user.ts#L160)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There are still potential loopholes here -- if only a single semester was returned, you wouldn't notice.
</blockquote></details>

You would because the line above would return false and the test would fail.
___
*[cypress/support/components/home-user.ts, line 341 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym5kd69MzW6-vOJqcZ:-Mypu4nd76jv5QLbEEWY:b-65zj82) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/support/components/home-user.ts#L341)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the `cy.get(PROPOSAL_TABLE_ROWS)` is necessary?
</blockquote></details>

You're probably right, it is not necessary
___
*[cypress/support/components/home-user.ts, line 435 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym6KEAD401YiRChQjb:-MyqD2K8E2oomD_IiqJr:b-65zj82) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/support/components/home-user.ts#L435)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the `cy.get(PROPOSAL_TABLE_ROWS)` is necessary?
</blockquote></details>

You're probably right, it is not necessary
___
*[src/app/home/home-user/home-user.component.html, line 55 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym7cxbB01A8ffQTKJH:-MyqN5Bc-swtI-A_qHP5:bk6theg) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/src/app/home/home-user/home-user.component.html#L55)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why not `startSemester`?

Oh, I see you have two variables for this. But I'm pretty sure you only need one.
</blockquote></details>

You're probably right but then because of the current implementation, doing so means that when a user clicks on the current semester filter, you would have both text inputs showing the current semester and the same goes for other filters as well.
___
*[src/app/home/home-user/home-user.component.html [...]

2022-03-24 19:54 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/100)* status: all files reviewed, 14 unresolved discussions (waiting on @mofokeng-chaka)

___
*[cypress/integration/home/home-user.spec.ts, line 20 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNE_i77GQMUbFHxQWO:-MywRrGJ4YG_SzUgSHQg:b-2vb48e) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L20)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Cypress is very inconsistent then, all the tests are passing on my side. Another thing to try is running the tests more than once, I realized that for some weird reason, sometimes the tests fail on the first run but they pass on following runs.
</blockquote></details>

That should give reason for utmost concern. Flakey tests are very problematic. :-/
___
*[cypress/integration/home/home-user.spec.ts, line 13 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym-XULA1huc36C0gJC:-MywQU_rDoyxnCreozuH:b-1r9wj6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/integration/home/home-user.spec.ts#L13)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Well, it does work, in fact, I tried using `cy.clock` before and it didn't work. Maybe it could be the case of different function scopes and the fact that it is being used in the different scripts but It didn't override the current date-time and as such tests failed. The tests only passed when I used `cy.stub` which let me control the behaviour of the `Date`methods.
</blockquote></details>

Ah, yes, it using the prototype. But I wonder whether you couldn't just use `Date.prototype` then? Another concern is whether the prototype is restored between tests (but that would probably apply to cy.clock as well).

But I don't think you `freezeDate` should be a method of HomeUser, as it has nothing to do with the HomeUser class really.

Finally, as indicated on Slack, I found at least one test still passing despite freezing to a date which is way before any SALT proposal.
___
*[cypress/integration/home/home-user.spec.ts, line 157 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym1jiH80toDPnxlzfj:-MywSNujDiQ3INyeHdfs:b-kt2ybz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/integration/home/home-user.spec.ts#L157)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I see the point you are making, I have changed this name.
</blockquote></details>

Oh, now I see where the original name comes from... Sorry, I had thought Biot was a mistake.
___
*[cypress/support/components/home-user.ts, line 34 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MywVgZa1WpX4u-L6j79:-MywVgZa1WpX4u-L6j7A:b-vsh0t0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7fdd727da1e4c5496b4e0e3c4736c84540bde518/cypress/support/components/home-user.ts#L34)):*
> ```XML
> const PRINCIPAL_INVESTIGATOR = '[data-test="principal-investigator"]';
> 
> const PROPOSAL_TABLE_ROWS = '[data-test="proposals-rows"]';
> ```

I think this data-test attribute has a misleading value, as the div it is used on is for a _row_, not for _rows_.
___
*[cypress/support/components/home-user.ts, line 434 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MywWOLr4CXU9BbiIf4Y:-MywWOLr4CXU9BbiIf4Z:bau4ic0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7fdd727da1e4c5496b4e0e3c4736c84540bde518/cypress/support/components/home-user.ts#L434)):*
> ```XML
> 
>   static filteredMyProposals(username: string): void {
>     //const investigators = [];
> ```

Unnecessary comment
___
*[cypress/support/components/home-user.ts, line 448 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MywWE4FDxqyRXEPLDdf:-MywWE4FDxqyRXEPLDdg:bnie0nk) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7fdd727da1e4c5496b4e0e3c4736c84540bde518/cypress/support/components/home-user.ts#L448)):*
> ```XML
>         .then((investigators) => {
>           investigators.each((index, investigator) => {
>             console.log(investigator.textContent, index);
> ```

Unnecessary console.log.
___
*[src/app/home/home-user/home-user.component.html, line 58 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym7T2O3Jk7Cxqqe7sT:-MywWVyUBxpNcDbF-8Oj:bqlckc1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/src/app/home/home-user/home-user.component.html#L58)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Remember I have to load stored input semesters and show them in the text fields if they exist. If I do avoid double-binding, I would have to deal with GUI concerns in the component file which is something you suggested I should do. 
</blockquote></details>

You wouldn't have to -- you would just have to pass the element value to the function called by the change/keyup listener.

But yiou can argue that, if at all, such a change can be made after this PR is accepted. :-)
___
*[src/app/home/home-user/home-user.component.html, line 83 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MywWzoe3BQ5oyu6W9Zs:-MywWzoe3BQ5oyu6W9Zt:bvzkcmf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7fdd727da1e4c5496b4e0e3c4736c84540bde518/src/app/home/home-user/home-user.component.html#L83)):*
> ```HTML
>         class="has-text-danger"
>         data-test="semester-error"
>         style="font-size: 12px"
> ```

This should rather be handled in a stylesheet.
___
*[src/app/home/home-user/home-user.component.ts, line 353 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyOL8uwAexm9vQSJNI0:-MyxREmd8Vb2NQytuFWK:bl3vyk1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/src/app/home/home-user/home-user.component.ts#L353)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Okay then, I have updated this to include all the other proposals you mentioned.
</blockquote></details>

Well, I think you'd still miss MLT, DDT and GWE proposals. But I have a related discussion with Encarni tomorrow. For the moment the safest might be to revert to `===` instead of `includes`.
___
*[src/app/home/home-user/home-user.component.ts, line 388 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyOIOAvBAe5tiC22L9F:-MyxRr3q5CMXbWoqxFgO:bc0ck3u) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/src/app/home/home-user/home-user.component.ts#L388)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

You're probably right but I tried using booleans and it messed everything up, the proposals ended up not showing at all. Since it does not harm the functionality at all I'd ask that we leave it as it is.
</blockquote></details>

I will accept the PR without the change (as you say, it works), but I think it should be changed some time.
___
*[src/app/home/home-user/home-user.component.ts, line 80 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyxQiKj2jWzEEFOEeMx:-MyxQiKj2jWzEEFOEeMy:b-4t7xsy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7fdd727da1e4c5496b4e0e3c4736c84540bde518/src/app/home/home-user/home-user.component.ts#L80)):*
> ```XML
>     this.authService
>       .getUser()
>       .pipe(
> ```

I'm happy to discuss this, but I think your pipe content should rather be content of  [...]

2022-03-25 09:50 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/100)* status: 6 of 13 files reviewed, 14 unresolved discussions (waiting on @hettlage)

___
*[cypress/integration/home/home-user.spec.ts, line 20 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNE_i77GQMUbFHxQWO:-Mz-QDdJ9m8aIs-3PNfH:bfo3zgn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That should give reason for utmost concern. Flakey tests are very problematic. :-/
</blockquote></details>

Let's hope it gets better, might be a lot of work having to change things at this time.
___
*[cypress/integration/home/home-user.spec.ts, line 13 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym-XULA1huc36C0gJC:-Mz-8vU216vlHOlu_AbL:b-l5b1jh) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/integration/home/home-user.spec.ts#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ah, yes, it using the prototype. But I wonder whether you couldn't just use `Date.prototype` then? Another concern is whether the prototype is restored between tests (but that would probably apply to cy.clock as well).

But I don't think you `freezeDate` should be a method of HomeUser, as it has nothing to do with the HomeUser class really.

Finally, as indicated on Slack, I found at least one test still passing despite freezing to a date which is way before any SALT proposal.
</blockquote></details>

The prototype may be restored between tests. And so I moved the `freezeDate` method inside the `beforeEach` hook. This worked but I had to override the current date-time using both `cy.clock` and `Date.prototype` for the tests to pass and also have the other test (year 2000) fail.
___
*[cypress/integration/home/home-user.spec.ts, line 157 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym1jiH80toDPnxlzfj:-Mz-Qe5c5ixwTRqqa991:b-3z2fqh) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/cypress/integration/home/home-user.spec.ts#L157)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oh, now I see where the original name comes from... Sorry, I had thought Biot was a mistake.
</blockquote></details>

But I think you were right by pointing it out.
___
*[cypress/support/components/home-user.ts, line 34 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MywVgZa1WpX4u-L6j79:-Mz-QkTiDUKB2G4jJ3Sa:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7fdd727da1e4c5496b4e0e3c4736c84540bde518/cypress/support/components/home-user.ts#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think this data-test attribute has a misleading value, as the div it is used on is for a _row_, not for _rows_.
</blockquote></details>

Done.
___
*[cypress/support/components/home-user.ts, line 434 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MywWOLr4CXU9BbiIf4Y:-Mz-Ql-F1SSpv2K9eAVl:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7fdd727da1e4c5496b4e0e3c4736c84540bde518/cypress/support/components/home-user.ts#L434)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary comment
</blockquote></details>

Done.
___
*[cypress/support/components/home-user.ts, line 448 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MywWE4FDxqyRXEPLDdf:-Mz-QlP840pi_NoaNglS:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7fdd727da1e4c5496b4e0e3c4736c84540bde518/cypress/support/components/home-user.ts#L448)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary console.log.
</blockquote></details>

Done.
___
*[src/app/home/home-user/home-user.component.html, line 58 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mym7T2O3Jk7Cxqqe7sT:-Mz-QoRVDyiLbn0il8pb:b-7z430k) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41d6023592a98276a15ae449a701eb9a245f1745/src/app/home/home-user/home-user.component.html#L58)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You wouldn't have to -- you would just have to pass the element value to the function called by the change/keyup listener.

But yiou can argue that, if at all, such a change can be made after this PR is accepted. :-)
</blockquote></details>

Thanks! :)
___
*[src/app/home/home-user/home-user.component.html, line 83 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MywWzoe3BQ5oyu6W9Zs:-Mz-QrpQDN5MBd8oZzQY:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7fdd727da1e4c5496b4e0e3c4736c84540bde518/src/app/home/home-user/home-user.component.html#L83)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should rather be handled in a stylesheet.
</blockquote></details>

Done.
___
*[src/app/home/home-user/home-user.component.ts, line 353 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyOL8uwAexm9vQSJNI0:-Mz-Qxhe7KnciHY1yR9P:bwygxsx) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/src/app/home/home-user/home-user.component.ts#L353)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Well, I think you'd still miss MLT, DDT and GWE proposals. But I have a related discussion with Encarni tomorrow. For the moment the safest might be to revert to `===` instead of `includes`.
</blockquote></details>

Noted.
___
*[src/app/home/home-user/home-user.component.ts, line 388 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyOIOAvBAe5tiC22L9F:-Mz-QzoI5YBGFMuutNPp:b-eeywll) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/099c1f0c3063d195e4ef73731b47e5d5c966f65c/src/app/home/home-user/home-user.component.ts#L388)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I will accept the PR without the change (as you say, it works), but I think it should be changed some time.
</blockquote></details>

Noted, thanks!
___
*[src/app/home/home-user/home-user.component.ts, line 80 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyxQiKj2jWzEEFOEeMx:-Mz-QsdjEfOaC_ovNh4V:b-qcbwdg) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7fdd727da1e4c5496b4e0e3c4736c84540bde518/src/app/home/home-user/home-user.component.ts#L80)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm happy to discuss this, but I think your pipe content should rather be content of a function you pass to subscribe.

Also, I doubt the debounce is necessary here.
</blockquote></details>

I am also happy to discuss this but the solutions I tried didn't work out for me.
I have removed the debounce.
___
*[src/app/home/home-user/home-user.component.ts, line 87 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyxPY1q7--8Qphn748h:-Mz-BpRP8q02LeYwrfZu:b-umm30w) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7fdd727da1e4c5496b4e0e3c4736c84540bde518/src/app/home/home-user/home-user.component.ts#L87)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would be a bit worried that if (only) one of the two conditions is true no error is raised.
</blockquote></details>

I have an appointment with an optometrist at 1 pm, will probably be back around 3 pm. Also, I think I may have found a solution to the issue I wanted us to discuss. Let me try it out, if it fails to work we will have a chat in the afternoon when I come back maybe?
___
*[src/app/home/home-user/hom [...]

2022-03-25 09:56 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/100)* status: 6 of 13 files reviewed, 14 unresolved discussions (waiting on @hettlage)

___
*[src/app/home/home-user/home-user.component.ts, line 87 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyxPY1q7--8Qphn748h:-Mz-V5fJDn-eLE49iE6h:bzesvqc) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7fdd727da1e4c5496b4e0e3c4736c84540bde518/src/app/home/home-user/home-user.component.ts#L87)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I have an appointment with an optometrist at 1 pm, will probably be back around 3 pm. Also, I think I may have found a solution to the issue I wanted us to discuss. Let me try it out, if it fails to work we will have a chat in the afternoon when I come back maybe?
</blockquote></details>

Sorry about this comment, it is the message in slack. But I have addressed your original comment.


<!-- Sent from Reviewable.io -->

2022-03-25 13:50 UTC, hettlage requested changes
> Reviewed 6 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/100)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[cypress/integration/home/home-user.spec.ts, line 20 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNE_i77GQMUbFHxQWO:-Mz-ui_M4qwMS3C1qaDB:bsmjnjy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L20)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Let's hope it gets better, might be a lot of work having to change things at this time.
</blockquote></details>

Well, it seems this whole testing business needs investigation... :-(
___
*[cypress/support/utils.ts, line 120 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mz0Kgi92vwjyDkGkA84:-Mz0Kgi92vwjyDkGkA85:b-1n0o0n) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c42135bea669314259c3163679b87aa0d848589d/cypress/support/utils.ts#L120)):*
> ```XML
>   cy.clock(now, ["Date"]);
> 
>   // override Date class methods to return the same year and month
> ```

I don't think you need to override the Date class methods.


<!-- Sent from Reviewable.io -->

2022-03-28 08:56 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/100)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[cypress/integration/home/home-user.spec.ts, line 20 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyNE_i77GQMUbFHxQWO:-MzEY674BtdslFRixWqf:b-veig1z) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1cd88d84f6fe5c7e0d451e5625d922eb04fa6c1f/cypress/integration/home/home-user.spec.ts#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Well, it seems this whole testing business needs investigation... :-(
</blockquote></details>

I agree with you. I am starting to get annoyed of having tests pass when running them with `cypress run` and fail when using `cypress open` without any clear problems.
___
*[cypress/support/utils.ts, line 120 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-Mz0Kgi92vwjyDkGkA84:-MzEewi3DdZy8KNsMnF0:b-tzx7le) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c42135bea669314259c3163679b87aa0d848589d/cypress/support/utils.ts#L120)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you need to override the Date class methods.
</blockquote></details>

If I don't the test fails and I think it is because the `currentSemester` method from the component file uses the Date class methods and these methods are probably not being overridden by `cy.clock`.
___
*[src/app/home/home-user/home-user.component.ts, line 80 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/100#-MyxQiKj2jWzEEFOEeMx:-MzEg_ea-k7jqZoHVk9x:b7j8jqd) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7fdd727da1e4c5496b4e0e3c4736c84540bde518/src/app/home/home-user/home-user.component.ts#L80)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I am also happy to discuss this but the solutions I tried didn't work out for me.
I have removed the debounce.
</blockquote></details>

The solution you suggested during our chat on Friday worked like a charm :1st_place_medal: 


<!-- Sent from Reviewable.io -->

2022-03-29 13:13 UTC, hettlage approved these changes
> Reviewed 1 of 7 files at r8, 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/100)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2022-03-29 13:14 UTC, merged