Edit contact information page
saltastroops/web-manager-2021 pull request #113
Opened 2022-04-28 12:55 UTC by mofokeng-chaka

2022-05-03 09:43 UTC, hettlage requested changes
I sometimes got an alert with a not found error when loading the page.

The sidebar does not disappear when you move to another page. (But we should talk about where to put it.)

It seems the buttons under Edit profile in the sidebar have no effect. (I'm not convinced they are necessary either...)

I'm not 100 % convinced of rotating the button when hiding the sidebar.

The dropdown menu for selecting a user has no effect. Also, it doesn't display the current user when the page is opened.

The dotted border lines should be thinner (and maybe slightly lighter), I think. The same is true for the horizxontral divider lines on the edit contact details form.

The form fields aren't aligned horizontally.

The change all contacts button does nothing.

I don't think you need RxJS for toggling the sidebar.

You are showing *all* institutions, but you should only show those for the selected partner.

The password should be included on the form,. and the form should be renamed (as it is then about user details -- and I don't see why it shouldn't include the user permissions as well).

I don't think the selected user should be stored in session or even local storage.

The copyright notice sometimes ends up in the middle of the form.

> Reviewed 91 of 95 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-:-N18IGzT7MgVDoNFbxod:bxehgsq)* status: all files reviewed, 30 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/app.component.html` line 7 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N17ruEB8TG5XmZM7du-:-N17ruEB8TG5XmZM7du0:boezl4v) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/app.component.html#L7)):*
> ```HTML
> 
> <div id="wm-app">
>   <div id="sidebar">
> ```

It might make more sense to have the sidebar under the menu?
___
*[`src/app/app.component.html` line 13 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N17rdp990cQvwh1vJYU:-N17rdp990cQvwh1vJYV:b-y6yz6r) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/app.component.html#L13)):*
> ```HTML
>       *ngIf="showSidebar"
>     ></wm-sidebar>
>     <div id="hide-sidebar">
> ```

Shouldn't hide-sidebar rather be toggle-sidebar?
___
*[`src/app/app.component.html` line 18 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N17sTEz4GDnCR-XNXtW:-N17sTEz4GDnCR-XNXtX:b-yjohsh) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/app.component.html#L18)):*
> ```HTML
>   </div>
> 
>   <div id="wm-content" [ngStyle]="updateAppStyle()">
> ```

"updateAppStyle" might need a different name -- you are not updating the app?
___
*[`src/app/app.component.scss` line 64 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N17sksC8IVzN0KeMzYv:-N17sksC8IVzN0KeMzYw:b-ge7fcp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/app.component.scss#L64)):*
> ```SCSS
>   height: 50px;
> }
> #hide-sidebar button.active {
> ```

Is ":active" really correct (isn't it "inactive" rather)? Also, wouldn't a class name like this make more sense for the sidebar rather than the button?
___
*[`src/app/app.component.ts` line 33 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N17uzNPDjrCSbNRCSgX:-N17uzNPDjrCSbNRCSgY:b-ildhq4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/app.component.ts#L33)):*
> ```XML
> 
>   ngOnInit(): void {
>     this.sidebarService
> ```

I think this can be simplified. (But this comment goes together with the question of how to handle the sidebar.)
___
*[`src/app/app.component.ts` line 50 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N17tECXAXk_yiEeA0vy:-N17tECXAXk_yiEeA0vz:bu68m1p) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/app.component.ts#L50)):*
> ```XML
> 
>     // Get loaded user details
>     const usr = sessionStorage.getItem("user");
> ```

I think there is too much logic in app.ts now. (But this comment goes together with the question of how to handle the sidebar.)

Also, storing the user in the session needs discussion.
___
*[`src/app/app.component.ts` line 59 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N17tuYE-1uzMIaFgoIA:-N17tuYE-1uzMIaFgoIB:b-ildhq4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/app.component.ts#L59)):*
> ```XML
> 
>     // Detect route changes
>     this.router.events
> ```

I think this can be simplified. (But this comment goes together with the question of how to handle the sidebar.)
___
*[`src/app/edit-contact-info/edit-contact-info.component.html` line 6 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N18-dLC5u0MTK1IjIip:-N18-dLC5u0MTK1IjIiq:b5lv2qn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/edit-contact-info/edit-contact-info.component.html#L6)):*
> ```HTML
>     <hr class="heading-line edit-contact-info-header" />
>     <h2 class="title is-3">
>       Edit contacts for '{{ selectedUser?.givenName }}
> ```

Shouldn't there *always* be a selected user? So `selectedUser?` could be `selectedUser` throughout this file.

Or at least, ofd there is no user, you shouldn't display the form (but rather a loading indicator or something like that)?
___
*[`src/app/edit-contact-info/edit-contact-info.component.html` line 20 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N18-VlE9eEKdXs0NGKV:-N18-VlE9eEKdXs0NGKW:bxxdvhl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/edit-contact-info/edit-contact-info.component.html#L20)):*
> ```HTML
>     <div class="user-info">
>       <label>
>         name:
> ```

I'd suggest that the labels start with a capital letter.
___
*[`src/app/edit-contact-info/edit-contact-info.component.html` line 47 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N18BpX2C2JF0OC3gyWh:-N18BpX2C2JF0OC3gyWi:b-shxa6r) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/edit-contact-info/edit-contact-info.component.html#L47)):*
> ```HTML
>         <select>
>           <option
>             *ngFor="let aff of affiliations"
> ```

Isn't that institutions rather than affiliations?
___
*[`src/app/edit-contact-info/edit-contact-info.component.ts` line 40 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N180M-v3bwwI1TpBlNi:-N180M-v3bwwI1TpBlNj:b-zd63ng) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/edit-contact-info/edit-contact-info.component.ts#L40)):*
> ```XML
>     this.sidebarService.setShowSidebar(true);
>     this.authService.user().subscribe((user) => (this.user = user));
>     this.activatedRoute.paramMap
> ```

I don't think you need to handle users as part of the parameters>? (But again, this begs the question where to put the sidebar.)
___
*[`src/app/edit-contact-info/edit-contact-info.component.ts` line 58 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N182KPk3cgmEB93Wpqb:-N182KPk3cgmEB93Wpqc:b-tb59zb) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/edit-contact-info/edit-contact-info.component.ts#L58)):*
> ```XML
>         this.selectedUser = user ? user : this.user;
>       });
>     this.institutionService.getInstitutions().subscribe((affiliations) => {
> ```

Aren't these institutions rather than affi [...]

2022-05-04 12:43 UTC, mofokeng-chaka reviewed
Most of these points are taken care of in the latest commit.

I have added a password and  "add new contact" button but they are still not yet functional.

I am still not sure why the copyright notice sometimes ended up in the middle of the form, it appears to be fine now.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-:-N1DqQi98Su50vEoau7y:b-i9o9sm)* status: 77 of 103 files reviewed, 30 unresolved discussions (waiting on @hettlage)

___
*[`src/app/app.component.html` line 7 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N17ruEB8TG5XmZM7du-:-N1DY0n-6B5RFa9hs87m:b-8zu7l0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/app.component.html#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might make more sense to have the sidebar under the menu?
</blockquote></details>

No longer necessary.
___
*[`src/app/app.component.html` line 13 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N17rdp990cQvwh1vJYU:-N1DYOfT9jUviL2YHXrG:b-8zu7l0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/app.component.html#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't hide-sidebar rather be toggle-sidebar?
</blockquote></details>

No longer necessary.
___
*[`src/app/app.component.html` line 18 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N17sTEz4GDnCR-XNXtW:-N1DYPWP-SeHfC74XUya:b-8zu7l0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/app.component.html#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"updateAppStyle" might need a different name -- you are not updating the app?
</blockquote></details>

No longer necessary.
___
*[`src/app/app.component.scss` line 64 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N17sksC8IVzN0KeMzYv:-N1DYQrcDEF7I0bFbHuc:b-8zu7l0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/app.component.scss#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is ":active" really correct (isn't it "inactive" rather)? Also, wouldn't a class name like this make more sense for the sidebar rather than the button?
</blockquote></details>

No longer necessary.
___
*[`src/app/app.component.ts` line 33 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N17uzNPDjrCSbNRCSgX:-N1DYaoT2DVQTaYhNXEI:b-8zu7l0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/app.component.ts#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think this can be simplified. (But this comment goes together with the question of how to handle the sidebar.)
</blockquote></details>

No longer necessary.
___
*[`src/app/app.component.ts` line 50 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N17tECXAXk_yiEeA0vy:-N1DYd_e-sz9j-xyn7LX:b-8zu7l0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/app.component.ts#L50)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think there is too much logic in app.ts now. (But this comment goes together with the question of how to handle the sidebar.)

Also, storing the user in the session needs discussion.
</blockquote></details>

No longer necessary.
___
*[`src/app/app.component.ts` line 59 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N17tuYE-1uzMIaFgoIA:-N1DYfr18Luhusf-ZA7a:b-8zu7l0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/app.component.ts#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think this can be simplified. (But this comment goes together with the question of how to handle the sidebar.)
</blockquote></details>

No longer necessary.
___
*[`src/app/edit-contact-info/edit-contact-info.component.html` line 6 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N18-dLC5u0MTK1IjIip:-N1DYiut1ywAI3dYaAHI:b-qi02hg) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/edit-contact-info/edit-contact-info.component.html#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't there *always* be a selected user? So `selectedUser?` could be `selectedUser` throughout this file.

Or at least, ofd there is no user, you shouldn't display the form (but rather a loading indicator or something like that)?
</blockquote></details>

That's true, there should always be a `selectedUser`.

And have also added the logic of displaying a loading indicator in case there's no `selectedUser`
___
*[`src/app/edit-contact-info/edit-contact-info.component.html` line 20 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N18-VlE9eEKdXs0NGKV:-N1DZHXU1kIHHYAP-aaE:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/edit-contact-info/edit-contact-info.component.html#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest that the labels start with a capital letter.
</blockquote></details>

Done.
___
*[`src/app/edit-contact-info/edit-contact-info.component.html` line 47 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N18BpX2C2JF0OC3gyWh:-N1DSi_5-PzlzCRW04ri:b-mzc41b) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/edit-contact-info/edit-contact-info.component.html#L47)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't that institutions rather than affiliations?
</blockquote></details>

It should be but I was doing this because institution "names" are found inside the affiliations array. However, I have changed the approach now.
___
*[`src/app/edit-contact-info/edit-contact-info.component.ts` line 40 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N180M-v3bwwI1TpBlNi:-N1DThJr43uGAcy-zPwh:b-gx9f7b) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/edit-contact-info/edit-contact-info.component.ts#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you need to handle users as part of the parameters>? (But again, this begs the question where to put the sidebar.)
</blockquote></details>

Now that the sidebar is removed, this point is no longer valid.
___
*[`src/app/edit-contact-info/edit-contact-info.component.ts` line 58 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N182KPk3cgmEB93Wpqb:-N1DUNRF1Rk44TcnRQ_z:bs460ho) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/edit-contact-info/edit-contact-info.component.ts#L58)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Aren't these institutions rather than affiliations?
</blockquote></details>

That's true, i have renamed it now.
___
*[`src/app/edit-contact-info/edit-contact-info.component.ts` line 75 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N181X1s8aeh8NeJ2VeU:-N1DV9f77ZXOyfPBIN0R:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/edit-contact-info/edit-contact-info.component.ts#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be null or undefined?
</blockquote></deta [...]

2022-05-04 17:14 UTC, hettlage requested changes
From what I can see, displaying a loading indicator isn't handled properly.

If the (logged-in) user is null, you should show an error rather than the form.

The first entry in the partner and institution comboboxes should not be just empty.

The alignment (and font size?) in the user selection box might need some fine-tuning.

> Reviewed 25 of 25 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-:-N1EjMjG7pRGIoRTpb-S:b-hpeqnj)* status: all files reviewed, 12 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`src/app/home/home-user/home-user.component.ts` line 231 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N183M266dVtD__ZBFMZ:-N1EeSJg2sEXSdt-V6tF:bf7jns2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/home/home-user/home-user.component.ts#L231)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I think it doesn't make any difference I ended up having to use the disabled command on the line to follow. 

Do you have any better suggestions?
</blockquote></details>

Oh, so the type *must* be any or unknown. How annoying. But then (after some googling) I think a rule should be added to the EASLint configuration. See https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-implicit-any-catch.md.
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 80 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1EfHb28zpLrPYkfomg:-N1EfHb28zpLrPYkfomh:b-rganpa) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.html#L80)):*
> ```HTML
>             <option value=""></option>
>             <option
>               *ngFor="let aff of partners"
> ```

aff > partner
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 97 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1EfMhN8_fcsGEvGuwS:-N1EfMhN8_fcsGEvGuwT:b-kmzi7q) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.html#L97)):*
> ```HTML
>               *ngFor="let inst of userInstitutions"
>               [value]="inst"
>               [selected]="inst === selectedInstitute"
> ```

selectedInstitute >selectedInstitution
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 116 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1Eg0A58_sby11SL0TK:-N1Eg0A58_sby11SL0TL:bldiit5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.html#L116)):*
> ```HTML
>         <tr>
>           <td>
>             <button>add new contact</button>
> ```

We should discuss this, as in "discuss the way for moving forward".
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 121 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1EfoiC8rVeRNS2TSSA:-N1EfoiD-9JT9vb0DB8M:btg2tbh) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.html#L121)):*
> ```HTML
>         <tr>
>           <td>
>             <button>change password</button>
> ```

I think the field(s) for changing the password should just be included in the form, without having to click on a button.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1F1-YSDTTPWc4mKuG6:-N1F1-YSDTTPWc4mKuG7:bsh1ql4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L1)):*
> ```XML
> import { Component, OnInit } from "@angular/core";
> ```

The form as such might need discussion.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 39 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1F0iNT2nkKuvR6QXe_:-N1F0iNU-ZywmuQnh74Z:b-gw6rg6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L39)):*
> ```XML
>     this.authService.user().subscribe((user) => {
>       if (user) {
>         this.user = user;
> ```

I strongly suspect `this.user` is unnecessary.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 47 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1EgUO10V14jYtjr1m5:-N1EgUO10V14jYtjr1m6:b-48pe7a) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L47)):*
> ```XML
>     this.userService
>       .getUsers()
>       .pipe(debounceTime(100))
> ```

Why do you have a debounce here? Isn't the service called only once?
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 62 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1EhiG9Aunysv6tY6jz:-N1EhiG9Aunysv6tY6k-:bn6xfr1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L62)):*
> ```XML
>         this.userInstitutions = this.filterInstitutions(this.institutions);
>       });
>     this.institutionService.getInstitutions().subscribe((institutions) => {
> ```

This might need discussion. The list of institutions depends on the selected partner, not on the user.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 74 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1EhxIh3zGCHl2z0Afs:-N1EhxIh3zGCHl2z0Aft:bn6xfr1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L74)):*
> ```XML
>   }
> 
>   filterInstitutions(institutions: Institution[]): string[] {
> ```

This might need discussion. The list of institutions depends on the selected partner, not on the user.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 94 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1EiaNxCR0l2SSUuW6X:-N1EiaNxCR0l2SSUuW6Y:b-ynypfw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L94)):*
> ```XML
>   }
> 
>   get selectedUserId(): number {
> ```

I would consider returning null or undefined if no user is selected.


<!-- Sent from Reviewable.io -->

2022-05-06 07:51 UTC, mofokeng-chaka reviewed
I think I need your help handling the loading indicator properly, it is still not displaying, not sure whether it's because things happen fast so it's not shown. Or maybe I need to overlay it somehow?

I changed the way I was handling the user as well, I am not expecting the user to be null – if the user is null, implies they are not logged in and as such, they will be redirected to the login page.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-:-N1NIseoC0uXpDrYgQBf:b-vy1qac)* status: 97 of 103 files reviewed, 12 unresolved discussions (waiting on @hettlage)

___
*[`src/app/home/home-user/home-user.component.ts` line 231 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N183M266dVtD__ZBFMZ:-N1I4zMWDXTUe4HFnSJo:bfq3j6v) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1756c593b9265add1d7aff81ece72c44403818ef/src/app/home/home-user/home-user.component.ts#L231)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oh, so the type *must* be any or unknown. How annoying. But then (after some googling) I think a rule should be added to the EASLint configuration. See https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-implicit-any-catch.md.
</blockquote></details>

Thanks for sharing this.
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 80 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1EfHb28zpLrPYkfomg:-N1I98GFETSRZ2z0N2HP:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.html#L80)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

aff > partner
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 97 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1EfMhN8_fcsGEvGuwS:-N1I9Fle6Y6vtlmKObGh:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.html#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

selectedInstitute >selectedInstitution
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 116 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1Eg0A58_sby11SL0TK:-N1NKAvn-hFpTlVXGtYI:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.html#L116)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

We should discuss this, as in "discuss the way for moving forward".
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 121 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1EfoiC8rVeRNS2TSSA:-N1NIiGE4CvDEP9kq-ta:b-bsdmt6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.html#L121)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the field(s) for changing the password should just be included in the form, without having to click on a button.
</blockquote></details>

I have added a submit button as per our discussion but it is still not yet functional awaiting the SDB discussion and changes.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1F1-YSDTTPWc4mKuG6:-N1NKOEzEFP7-nLYmtYa:b-beh0b2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The form as such might need discussion.
</blockquote></details>

I have added a form controller now and I can load user details directly to it.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 39 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1F0iNT2nkKuvR6QXe_:-N1NKasq6tBKP-x9RgbC:b8je3cr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I strongly suspect `this.user` is unnecessary.
</blockquote></details>

No longer necessary, I changed the code a bit so that it won't be shown if there's no user.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 47 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1EgUO10V14jYtjr1m5:-N1I9sCX73XEnS8rDdFa:bbf1nd2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L47)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you have a debounce here? Isn't the service called only once?
</blockquote></details>

Yes, this service is only called once so I don't need the debounce.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 62 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1EhiG9Aunysv6tY6jz:-N1N7p1J-mwYablANeph:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L62)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This might need discussion. The list of institutions depends on the selected partner, not on the user.
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 74 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1EhxIh3zGCHl2z0Afs:-N1N7o49EYKcSc8NzsYF:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L74)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This might need discussion. The list of institutions depends on the selected partner, not on the user.
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 94 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1EiaNxCR0l2SSUuW6X:-N1IAi3d0aMkw9LLL2Yg:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L94)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would consider returning null or undefined if no user is selected.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-06 15:50 UTC, hettlage requested changes
Let's chat about this on Monday.

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-:-N1P37NE0XMO8aBA6E1u:b-1avgce)* status: all files reviewed, 12 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 2 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1OmGKN4tOIMyRBUzcW:-N1OmGKN4tOIMyRBUzcX:b-9np25a) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.html#L2)):*
> ```HTML
> <div class="edit-contact-info">
>   <div *ngIf="user$ | async; else loading_indicator">
> ```

From what I see, you only indicate loading while the user is logging in, but not when select another user.

I'm pretty sure you need a variable indicating loading status.
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 9 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1OktK474URNeQiflqu:-N1OktK474URNeQiflqv:b-wuiiu6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.html#L9)):*
> ```HTML
>         <tr>
>           <td>
>             <span class="title is-5">Select user</span>
> ```

Only administrators should be able to see and switch users.
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 75 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1NmL321JY9kCVzUnGf:-N1NmL321JY9kCVzUnGg:blr14ij) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.html#L75)):*
> ```HTML
>             <td>Partner:</td>
>             <td>
>               <select>
> ```

Aren't you missing a formControlName here>?
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 109 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1NmURf5vgJ8R7uCVOy:-N1NmURf5vgJ8R7uCVOz:bt339nw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.html#L109)):*
> ```HTML
>             <td>Password:</td>
>             <td>
>               <input type="password" id="password" formControlName="password" />
> ```

You might consider adding a retype password field.
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 128 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P-eWR70LKeZq2yO2l:-N1P-eWR70LKeZq2yO2m:bantm9i) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.html#L128)):*
> ```HTML
>   </div>
>   <ng-template #loading_indicator>
>     <div class="loading-indicator">
> ```

I don't think the loading spinner is positioned properly - it doesn't look centred to me.
___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 25 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1Oo35h3icgfUnkGfQ4:-N1Oo35h3icgfUnkGfQ5:b5wk014) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.scss#L25)):*
> ```SCSS
> 
> .user-profile input {
>   border-style: solid;
> ```

I think the border looks a bit odd - I'd retain the native L&F as much as possible? But if you need a border, I think a gray one might be better.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P-yHj7SV-mzW2yXdM:-N1P-yHj7SV-mzW2yXdN:bcdlyi0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L1)):*
> ```XML
> import { Component, OnInit } from "@angular/core";
> ```

You aren't updating the institutions when the partner is changed.

You don't update the partner/institutions when a new user is selected.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 51 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1OlPIK0xvES2vS8WJ9:-N1OlMYI4CLcfEE83_q9:b4qswas) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L51)):*
> ```XML
>       }),
>     );
>     this.userService.getUsers().subscribe((users) => {
> ```

The query should only be made if you are an admin. See method 1 
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 51 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P15YL6YEA4DvM-2Ns:-N1P15YL6YEA4DvM-2Nt:b-9va5de) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L51)):*
> ```XML
>       }),
>     );
>     this.userService.getUsers().subscribe((users) => {
> ```

If you are subscribing to a stream, you must make sure that you unsubscribe when the component is destroyed (cf. Method 1 in https://blog.bitsrc.io/6-ways-to-unsubscribe-from-observables-in-angular-ab912819a78f?gi=98dc4a6446a1).
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 70 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1OygmY1Mxsop9Bp6tM:-N1OygmY1Mxsop9Bp6tN:baxko1q) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L70)):*
> ```XML
>       this.institutions = institutions;
>       this.userInstitutions = this.filterInstitutions();
>       const p = institutions.map((institution) => {
> ```

I think you are making your life unnecessarily difficult, as you are basing selection on the partner rather than the partner code.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 72 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1OzBBZ5sUDwjBGBflR:-N1OzBBZ5sUDwjBGBflS:bi3yuez) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L72)):*
> ```XML
>       const p = institutions.map((institution) => {
>         const partnerCode =
>           institution.partnerCode as unknown as keyof typeof Partner;
> ```

Does it really have to be `as unknown as key type Partner`? Wouldn't `as key type Partner` be enough?
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 84 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P2gqu72St2UVz97G7:-N1P2gqv1RXbKgLqeije:bkw0cxe) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L84)):*
> ```XML
>       (k) => Partner[k as unknown as keyof typeof Partner] == partner,
>     );
>     const filteredIns = this.institutions.filter(
> ```

While in practical terms it probably doesn't make a difference, the code begs the question whether it might not make sense to create a map of partner codes and corresponding institutions, rather than filtering all the time?


<!-- Sent from Reviewable.io -->

2022-05-09 07:12 UTC, hettlage requested changes
> Reviewed 2 of 32 files at r6, 32 of 32 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113)* status: all files reviewed, 14 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/styles.scss` line 2 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1be63gCCAEQZW-Gv00:-N1be63gCCAEQZW-Gv01:b-mxgec4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e99ef9791b039b80fb78d8b50f543e13da7a2894/src/styles.scss#L2)):*
> ```SCSS
> /* You can add global styles to this file, and also import other style files */
> // Variables overriding Bulma values. These must be set before Bulma is imported.
> ```

Why have you deleted this line?
___
*[`src/styles.scss` line 11 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1be9aC9atYjHClCtdr:-N1be9aC9atYjHClCtds:bjrb4u8) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e99ef9791b039b80fb78d8b50f543e13da7a2894/src/styles.scss#L11)):*
> ```SCSS
> $size-6: 0.8rem;
> 
> $navbar-burger-color: #f1f1f1;
> ```

Why have you deleted these lines?
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 51 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1OlPIK0xvES2vS8WJ9:-N1bd2gj1f0BX8pwllIr:b-aj4ye8) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The query should only be made if you are an admin. See method 1 
</blockquote></details>

(I think the cryptic "See method 1" was typed here erroneously. Sorry.)


<!-- Sent from Reviewable.io -->

2022-05-09 07:51 UTC, mofokeng-chaka reviewed
Yes please, especially showing the loading indicator when you select a user.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-:-N1YaJjF3jXQAmCfOuI4:b-9xc7x7)* status: 99 of 103 files reviewed, 14 unresolved discussions (waiting on @hettlage)

___
*[`src/styles.scss` line 2 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1be63gCCAEQZW-Gv00:-N1bm2XO61YC__hH9Hc3:bj5xttl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e99ef9791b039b80fb78d8b50f543e13da7a2894/src/styles.scss#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why have you deleted this line?
</blockquote></details>

I didn't it must have been a mistake I made when I was fixing conflicts.
___
*[`src/styles.scss` line 11 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1be9aC9atYjHClCtdr:-N1bmDZA4GtthXcEkyfI:bs43tlh) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e99ef9791b039b80fb78d8b50f543e13da7a2894/src/styles.scss#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why have you deleted these lines?
</blockquote></details>

I didn't it must have been a mistake I made when I was fixing conflicts
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 2 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1OmGKN4tOIMyRBUzcW:-N1Y_fEo7vs4-x2IuDrV:b-ji6u0t) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.html#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

From what I see, you only indicate loading while the user is logging in, but not when select another user.

I'm pretty sure you need a variable indicating loading status.
</blockquote></details>

I have introduced a variable now but I still cannot show the indicator when selecting a user. I need your help with this.
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 9 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1OktK474URNeQiflqu:-N1Y_4ds3Cb3yihfrATa:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.html#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Only administrators should be able to see and switch users.
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 75 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1NmL321JY9kCVzUnGf:-N1Y_82P01AF1L62-FyF:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.html#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Aren't you missing a formControlName here>?
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 109 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1NmURf5vgJ8R7uCVOy:-N1Y_9F00NbDzdDTk45f:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.html#L109)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You might consider adding a retype password field.
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 128 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P-eWR70LKeZq2yO2l:-N1Y_AHv34LqOtgE6k2w:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.html#L128)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the loading spinner is positioned properly - it doesn't look centred to me.
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 25 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1Oo35h3icgfUnkGfQ4:-N1Y_C155PHTyGVwa-Eh:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.scss#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the border looks a bit odd - I'd retain the native L&F as much as possible? But if you need a border, I think a gray one might be better.
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P-yHj7SV-mzW2yXdM:-N1Y_FyjCthD57LtYt1F:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You aren't updating the institutions when the partner is changed.

You don't update the partner/institutions when a new user is selected.
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 51 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1OlPIK0xvES2vS8WJ9:-N1Y_Ga21jsSisxN6EKN:befvyqo) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

(I think the cryptic "See method 1" was typed here erroneously. Sorry.)
</blockquote></details>

Noted, and I have addressed the query issue.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 51 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P15YL6YEA4DvM-2Ns:-N1Y_HYH9qlFP67WJ_rx:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If you are subscribing to a stream, you must make sure that you unsubscribe when the component is destroyed (cf. Method 1 in https://blog.bitsrc.io/6-ways-to-unsubscribe-from-observables-in-angular-ab912819a78f?gi=98dc4a6446a1).
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 70 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1OygmY1Mxsop9Bp6tM:-N1Y_Ku44yFGk5oMpLzV:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L70)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think you are making your life unnecessarily difficult, as you are basing selection on the partner rather than the partner code.
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 72 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1OzBBZ5sUDwjBGBflR:-N1Y_MzQ80oqsVsbN_N8:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L72)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Does it really have to be `as unknown as key type Partner`? Wouldn't `as key type Partner` be enough?
</blockquote></details>

Done.
___
*[`src/app/manag [...]

2022-05-09 11:16 UTC, hettlage requested changes
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113)* status: all files reviewed, 16 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`src/styles.scss` line 2 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1be63gCCAEQZW-Gv00:-N1bvpMV5y0oZ9zsmP2O:b-374l1j) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e99ef9791b039b80fb78d8b50f543e13da7a2894/src/styles.scss#L2)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I didn't it must have been a mistake I made when I was fixing conflicts.
</blockquote></details>

It still seems to be gone?
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 128 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P-eWR70LKeZq2yO2l:-N1cX3XM2pBZ4hu8U0jW:b-b4ozgr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.html#L128)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I would suggest to show the loading indicator on top of the form (and blur the existing form content).
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P-yHj7SV-mzW2yXdM:-N1cAc7t5kYhxBKyIeuy:b-dpd6bg) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L1)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

From what I see, the institutions still aren't updated when you change the partner?
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 51 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P15YL6YEA4DvM-2Ns:-N1c9uuLBrREiHSCt2Ix:bs7zh60) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L51)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see this?
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 70 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1OygmY1Mxsop9Bp6tM:-N1c9bgVB7o1PRHKadJF:bs7zh60) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L70)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see this?
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 72 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1OzBBZ5sUDwjBGBflR:-N1cAFWfAzY7gCWi802C:b-sbz8ny) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L72)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see any change?
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 26 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cBujM0RFdpGlmtc1k:-N1cBujM0RFdpGlmtc1l:bmjcime) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L26)):*
> ```XML
>   partners!: string[];
>   partnerInstitutions!: string[];
>   institutionsMapping!: { [partnerCode: string]: string | string[] };
> ```

Why can there value be a string? Shouldn't this always be a list? Also, have you considered using a Map?
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 28 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cBfZI1-CJBA8rBfhn:-N1cBfZJ0y3mPo2IQYx5:bdoyada) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L28)):*
> ```XML
>   institutionsMapping!: { [partnerCode: string]: string | string[] };
>   userProfile!: FormGroup;
>   isAdministrator = false;
> ```

I don't think there is a need for having a variable for this?
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 55 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cC6rhCTtGMTvAUyy1:-N1cC6rhCTtGMTvAUyy2:b8xkx3d) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L55)):*
> ```XML
>       }),
>     );
>     this.user$
> ```

There should be no need to subscribe to the same stream (user$) twice.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 61 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cRnr64-kRQcgANc-L:-N1cRnr64-kRQcgANc-M:b5jgjrs) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L61)):*
> ```XML
>           if (user.roles.includes("Administrator")) {
>             this.isAdministrator = true;
>             return this.userService.getUsers().pipe(take(1));
> ```

Why do you need the `take(1)`?
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 77 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cQxaK0BuiOD5NdR4V:-N1cQxaK0BuiOD5NdR4W:b-jlup92) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L77)):*
> ```XML
>         catchError((err) => {
>           window.alert(err);
>           this.loading = true;
> ```

Shouldn't that be `this.loading = false`?
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 82 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cSBfz6cTPGi9mk-oV:-N1cSBg-2AnDlAG7Yrrq:b-4i6yqw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L82)):*
> ```XML
>       )
>       .subscribe((user) => {
>         if (user) {
> ```

You should handle the case of a `null` user as well.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 94 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cSQNM-65-MFBwvcsM:-N1cSQNM-65-MFBwvcsN:b5jgjrs) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L94)):*
> ```XML
>     this.institutionService
>       .getInstitutions()
>       .pipe(take(1))
> ```

Why do you need the `take(1)`?
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 97 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cSwgN7xYeGl2asX5x:-N1cSwgN7xYeGl2asX5y:bvi8g0y) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L97)):*
> ```XML
>       .subscribe((institutions) => {
>         this.institutionsMapping = institutions.reduce(
>           (r: { [key: string]: string | string[] }, a) => {
> ```

This might be a case where a good old `for` loop is the better choice.

And why is `string` (a [...]

2022-05-09 16:44 UTC, mofokeng-chaka reviewed
The loading spinner is working well now. On second thought, I think it is best to show it only on the form and not next to the select element because when one selects a user, their full names are immediately shown on the select element – the delay happens only on the form.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-:-N1dTtbj1_xZtmfZ8714:blx3wcp)* status: 100 of 103 files reviewed, 16 unresolved discussions (waiting on @hettlage)

___
*[`src/styles.scss` line 2 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1be63gCCAEQZW-Gv00:-N1cZGfi0fmXZHtXwJnD:b-x6mgpq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e99ef9791b039b80fb78d8b50f543e13da7a2894/src/styles.scss#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It still seems to be gone?
</blockquote></details>

That's weird, I did add it back and it shows on my side.
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 128 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P-eWR70LKeZq2yO2l:-N1dUaeq0pvnK0OM0Ewu:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.html#L128)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest to show the loading indicator on top of the form (and blur the existing form content).
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P-yHj7SV-mzW2yXdM:-N1cnckm38_azeS11RZC:bdd7dhf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

From what I see, the institutions still aren't updated when you change the partner?
</blockquote></details>

It is now updated.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 51 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P15YL6YEA4DvM-2Ns:-N1cYRgg6vfWaFW0NUSo:b9lzb0p) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see this?
</blockquote></details>

I added a `take` operator to the pipe, I think it does address the issue of unsubscribing because it ensures that the subscription only happens once and is exited after.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 70 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1OygmY1Mxsop9Bp6tM:-N1coUZSBWLFl23Tev1J:bcpk8jl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L70)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see this?
</blockquote></details>

You're probably right about making life difficult, but because I need partners not partner codes I think it is best I work with them throughout and then map back to partner codes when necessary. Otherwise, even if I work with partner codes I would still need to map to partners before displaying anything to the user.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 72 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1OzBBZ5sUDwjBGBflR:-N1cY1x90cunA95jkpOK:bg2ksyi) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L72)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see any change?
</blockquote></details>

There was one instance that I missed, should be changed now.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 26 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cBujM0RFdpGlmtc1k:-N1cb12v29-TVz0LdP-d:b65dmk2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why can there value be a string? Shouldn't this always be a list? Also, have you considered using a Map?
</blockquote></details>

You're right, the list is always returned here. I didn't consider using a Map
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 28 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cBfZI1-CJBA8rBfhn:-N1cal6WA2qrpijBy5Wr:bft87eq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think there is a need for having a variable for this?
</blockquote></details>

I think I do, otherwise, I would have to handle this in the template because I have to hide the user selection for other users except for admins.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 55 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cC6rhCTtGMTvAUyy1:-N1dTjgU57ycMe88zRZ-:b-8zu7l0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L55)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should be no need to subscribe to the same stream (user$) twice.
</blockquote></details>

No longer necessary.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 61 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cRnr64-kRQcgANc-L:-N1c_ie31Nn47I1UkqUH:bfbl50p) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L61)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you need the `take(1)`?
</blockquote></details>

This operator ensures that the subscription only happens once and is exited after.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 77 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cQxaK0BuiOD5NdR4V:-N1ccVc7BmIbKuwHOdmc:bmwtcq4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't that be `this.loading = false`?
</blockquote></details>

That's correct.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 82 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cSBfz6cTPGi9mk-oV:-N1dTryK47tgxzzNmra8:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L82)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should handle the case of a `null` user as well.
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 94 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cSQNM-65-MFBwvcsM:-N1cZyzZ72A6Cd2-CVdt:bfbl50p) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a69 [...]

2022-05-10 07:44 UTC, hettlage requested changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113)* status: all files reviewed, 9 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/styles.scss` line 2 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1be63gCCAEQZW-Gv00:-N1girMl98FyOKTQMwND:b5lmiie) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e99ef9791b039b80fb78d8b50f543e13da7a2894/src/styles.scss#L2)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

That's weird, I did add it back and it shows on my side.
</blockquote></details>

Nope, I've double-checked, and I definitely cannot seer the line below.



_Code quote:_
```SCSS
// Variables overriding Bulma values. These must be set before Bulma is imported.
```
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 128 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P-eWR70LKeZq2yO2l:-N1gjmIq4pYf0THb30DG:bfm73l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.html#L128)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think you are blurring the content, though, are you?

Also, it might be worth adding a (small) loading spinner to the right of the user selection dropdown while the list of users is being loaded.
___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 90 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1gkrtX3_Br-3QPeoJ-:-N1gkrtY5-pywymwTnir:b-5pgumu) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d54d5ddb9b3bb80adb154c3c131de95ba97c7688/src/app/manage-user-profile/manage-user-profile.component.scss#L90)):*
> ```SCSS
>   align-items: center;
>   justify-content: center;
>   top: 435px;
> ```

I don't think the line `top: 435px` is necessary?

Also, this is duplicating code from `block-view.component.scss`, so it should rather be moved from both oil;ers into the global styles file.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P-yHj7SV-mzW2yXdM:-N1gnzvsC7CwdjoiuZ2A:b-dwvypz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L1)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

It is now updated.
</blockquote></details>

They are, but when testing it, I spotted three new problems:

* The partners aren't sorted in the partner dropdown menu (and Other doesn't appear last in the list).
* No departments are shown in the institutions dropdown menu (which means that some institutions appear to be in there twice -- look at the UK institutions).
* When you change the partner, you update the institutions list. But you don't update the selectedUser, which means there is a mismatch between UI and underlying model.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 70 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1OygmY1Mxsop9Bp6tM:-N1glSud9jvqjmzNF6_h:b5lsyic) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L70)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

You're probably right about making life difficult, but because I need partners not partner codes I think it is best I work with them throughout and then map back to partner codes when necessary. Otherwise, even if I work with partner codes I would still need to map to partners before displaying anything to the user.
</blockquote></details>

As for the need to map to partners before displaying anything to the user, that is true of course, but given you have the map already, this would one easy if you add a `value` attribute to the `option` elements?

At least it should make the `onSelectPartner` method more straightforward!
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 28 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cBfZI1-CJBA8rBfhn:-N1glti56uuKph5riGg1:b-j2xfhi) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L28)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I think I do, otherwise, I would have to handle this in the template because I have to hide the user selection for other users except for admins.
</blockquote></details>

But I see you got rid ion the variable...? :-)
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 97 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cSwgN7xYeGl2asX5x:-N1grcN8CKWBi582F6ix:bflgwqi) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L97)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

You're probably right but I think the reducer does this job perfectly because I am able to get a list of all institutions with the same partner code easily. Having to loop over more than 300 entries individually is a bit tedious because I think I would have to map institutions by partner code first before grouping them by partner code.

You're correct about the type, it should be Partner
</blockquote></details>

The reason why a for loop *might* be better here is that using reduce forces you to copy lists over and over again. The complexity of the for loop would be comparable:

```
        this.institutionsMapping = new Map();
        for (const institution of institutions) {
          const partnerCode = institution.partnerCode;
          if (this.institutionsMapping.has(partnerCode)) {
            this.institutionsMapping.get(partnerCode).push(institution.institution);
          } else {
            this.institutionsMapping.set(partnerCode, []);
          }
        }
```

But when creating this code, I noticed a more serious issue: You are selecting an institution by name, which is not unique (see comment about departments above). So you should select the whole `Institution` object.

Also, the presence of `institution.institution` in the above code raises the question whether the `institution` property could do with a better name, such as `name`?
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 103 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cTl6QEoBkOFkT5I9W:-N1gr9WYCMVyuMCbaH2w:bx8aaeo) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L103)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

That's correct.
</blockquote></details>

Then why do you need this code rather than just

`this.partners = Partner`

or (maybe better)

`this.Partner = Partner`

?
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 110 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cUF_IC9LyB4EVGjdw:-N1gqXd43U2cUGeY-nVk:bq9nkd8) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L110)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquo [...]

2022-05-10 11:18 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113)* status: 98 of 105 files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[`src/styles.scss` line 2 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1be63gCCAEQZW-Gv00:-N1hOzyr782RkK346Uqp:bfyjan6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e99ef9791b039b80fb78d8b50f543e13da7a2894/src/styles.scss#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Nope, I've double-checked, and I definitely cannot seer the line below.
</blockquote></details>

I was not aware you are referring to the above comment, it should be added now.
___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 128 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P-eWR70LKeZq2yO2l:-N1hRendB2EQv3jrDoYu:b-ns8vy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.html#L128)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you are blurring the content, though, are you?

Also, it might be worth adding a (small) loading spinner to the right of the user selection dropdown while the list of users is being loaded.
</blockquote></details>

The content is now being blurred.

I also managed to add the loading spinner but I am struggling to make it small.
___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 90 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1gkrtX3_Br-3QPeoJ-:-N1h1MtO-HXwLPxtpOaD:b-ecsv21) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d54d5ddb9b3bb80adb154c3c131de95ba97c7688/src/app/manage-user-profile/manage-user-profile.component.scss#L90)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the line `top: 435px` is necessary?

Also, this is duplicating code from `block-view.component.scss`, so it should rather be moved from both oil;ers into the global styles file.
</blockquote></details>

It is necessary because I am only showing the loading spinner on top of the form only not the whole page. 
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P-yHj7SV-mzW2yXdM:-N1hfjmsDNSou3J8bOMe:bf1csax) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

They are, but when testing it, I spotted three new problems:

* The partners aren't sorted in the partner dropdown menu (and Other doesn't appear last in the list).
* No departments are shown in the institutions dropdown menu (which means that some institutions appear to be in there twice -- look at the UK institutions).
* When you change the partner, you update the institutions list. But you don't update the selectedUser, which means there is a mismatch between UI and underlying model.
</blockquote></details>

- The partners are now sorted in the dropdown. Taking into account your latest comments it will be a bit challenging to move "Other" to be the last in the list because now I am using the enum type rather than the list of keys. 
- Departments are now shown in the institutions dropdown.
- The selected user is now updated when a partner is changed.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 70 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1OygmY1Mxsop9Bp6tM:-N1hYSgf3D7ve1q7TPWk:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.ts#L70)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As for the need to map to partners before displaying anything to the user, that is true of course, but given you have the map already, this would one easy if you add a `value` attribute to the `option` elements?

At least it should make the `onSelectPartner` method more straightforward!
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 28 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cBfZI1-CJBA8rBfhn:-N1hGvypAOhrP5d4Zt6C:bqqpn8n) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But I see you got rid ion the variable...? :-)
</blockquote></details>

Yep, and my comment is no longer valid.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 97 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cSwgN7xYeGl2asX5x:-N1hO19s7zEaWUM9aviL:bkh95xc) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The reason why a for loop *might* be better here is that using reduce forces you to copy lists over and over again. The complexity of the for loop would be comparable:

```
        this.institutionsMapping = new Map();
        for (const institution of institutions) {
          const partnerCode = institution.partnerCode;
          if (this.institutionsMapping.has(partnerCode)) {
            this.institutionsMapping.get(partnerCode).push(institution.institution);
          } else {
            this.institutionsMapping.set(partnerCode, []);
          }
        }
```

But when creating this code, I noticed a more serious issue: You are selecting an institution by name, which is not unique (see comment about departments above). So you should select the whole `Institution` object.

Also, the presence of `institution.institution` in the above code raises the question whether the `institution` property could do with a better name, such as `name`?
</blockquote></details>

I have changed the code accordingly, the whole `Institution` object is now selected and the property `institution` is now `name'
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 103 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cTl6QEoBkOFkT5I9W:-N1hGkBf9wKDhJQ1tgMl:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L103)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Then why do you need this code rather than just

`this.partners = Partner`

or (maybe better)

`this.Partner = Partner`

?
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 110 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1cUF_IC9LyB4EVGjdw:-N1hGowmBMBVLFpapszX:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/96fc1db0ce65a6938be7b53ca7e778a024c33ada/src/app/manage-user-profile/manage-user-profile.component.ts#L110)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ach, I guess I was unclear. I think (or at least I hope) I meant that you should rather select proposal codes (not partners), as indicated in another comment. If you stick to partners, the variable name *should* be `serlectedPartner`.
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 92 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1gpl5q7OfUGfodK-YD:-N1h9nFuCQOZQ [...]

2022-05-11 09:30 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113)* status: 101 of 105 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 128 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P-eWR70LKeZq2yO2l:-N1j9OmI-3xQsQ2bt9yN:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d37c66fd58da809972afd618daccfc72c4b32139/src/app/manage-user-profile/manage-user-profile.component.html#L128)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comment below -- opt for another spinner I'd say.
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 90 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1gkrtX3_Br-3QPeoJ-:-N1mOu5q8CczRmEMMouF:b-8c3zlp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d54d5ddb9b3bb80adb154c3c131de95ba97c7688/src/app/manage-user-profile/manage-user-profile.component.scss#L90)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But setting `top` to some "magic" value is not the best solution then. As absolute position happens relative to the nearest ancestor with the CSS rule `position: relative`, the better way is to make sure the parent element has that rule.
</blockquote></details>

I am not sure I understand you correctly but I have set `position: absolute`.
___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 90 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1iQW7v7IJkQF6OL_7y:-N1j9jWXE_pwA1XkAenR:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9955bda57c06dddb5bc342bde76023efe34224ab/src/app/manage-user-profile/manage-user-profile.component.scss#L90)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd say you need a separate loading spinner with the correct size. 

See https://loading.io/css/.
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P-yHj7SV-mzW2yXdM:-N1mKmAE-FhJKrQ0BOXb:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

* To sort the "Other" problem, the best might be to sort the partners with a custom sort method (or similar) in the TypeScript file, i.re. not with a pipe in the template file. (This has the added benefit that you could use the department as a secondary sort key.)
* I'd suggest to enclose the department (if there is one) in parentheses,  as in "University of Wakanda (Department of Aviation and Rocket Science)".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-12 07:15 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113)* status: all files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 117 at r11](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1nYcT6-QfJThA4BiUZ:-N1r5cfe6fkWvjaiwgUG:b-ymbbnz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/28bfda3e08e1b74d5229ace933425b4c65c6c118/src/app/manage-user-profile/manage-user-profile.component.html#L117)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Paragraph pages are not allowed here.
</blockquote></details>

I have removed it now.
___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 90 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1gkrtX3_Br-3QPeoJ-:-N1r5ggB5G5N5OQZXPrr:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d54d5ddb9b3bb80adb154c3c131de95ba97c7688/src/app/manage-user-profile/manage-user-profile.component.scss#L90)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See the "position: absolute" section on https://www.w3schools.com/css/css_positioning.asp. Otherwise, let's chat tomorrow.
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 93 at r11](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1nWDC90mU4-zeK9Bgr:-N1r5hvX3HshdhFXBh6V:bqwfuma) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/28bfda3e08e1b74d5229ace933425b4c65c6c118/src/app/manage-user-profile/manage-user-profile.component.scss#L93)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The same problem as above. But in this case you might not need absolute positioning, as yiu just wants to display the spinner next to the dropdown menu.
</blockquote></details>

I think I do need the absolute positioning, if I remove I am not able to control the position of the spinner with `top` and/or `left` properties.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1P-yHj7SV-mzW2yXdM:-N1r6H3A8QPu-gwshbqb:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f371644348ea25f0f9bcb850beec93c3ec15d6b6/src/app/manage-user-profile/manage-user-profile.component.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

From all I can see, the partners are still not sorted (apart from "Other" coming last now).
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 173 at r11](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1nV0cK7WF6iLErd7Md:-N1r6HsM79rGF83v5Ddp:b-5hwsf7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/28bfda3e08e1b74d5229ace933425b4c65c6c118/src/app/manage-user-profile/manage-user-profile.component.ts#L173)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"addDepartment" is arguably misleading; you are not adding anything.

Also, it might be slightly more natural to have a method which outputs both the name and department.
</blockquote></details>

I have changed the name to `showInstitution` now and have made the method output both the institution name and department.
___
*[`src/app/shared/small-loading-spinner/small-loading-spinner.component.html` line 1 at r12](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1nYGr63hEQO-ZfDOkW:-N1r6ZRhA04h-21m2lm5:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e4f86d3e75d5dd08b63d3f9983c3de09a90c83dc/src/app/shared/small-loading-spinner/small-loading-spinner.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be more consistent if both spinners are of the same type?

Also, the spinner probably could be a bit smaller?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-12 08:39 UTC, hettlage requested changes
> Reviewed 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113)* status: all files reviewed, 5 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 90 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1gkrtX3_Br-3QPeoJ-:-N1rOCBHAYA31h68RSCb:b-9egho7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d54d5ddb9b3bb80adb154c3c131de95ba97c7688/src/app/manage-user-profile/manage-user-profile.component.scss#L90)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still the `top`, though. I guess we'll have to discuss this. :-)
___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 93 at r11](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1nWDC90mU4-zeK9Bgr:-N1rOR_rC3clmILjSzXT:b2dq4tu) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/28bfda3e08e1b74d5229ace933425b4c65c6c118/src/app/manage-user-profile/manage-user-profile.component.scss#L93)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I think I do need the absolute positioning, if I remove I am not able to control the position of the spinner with `top` and/or `left` properties.
</blockquote></details>

Let's discuss this.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 173 at r11](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1nV0cK7WF6iLErd7Md:-N1rP3hv06sbtVho1QI-:bysiueq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/28bfda3e08e1b74d5229ace933425b4c65c6c118/src/app/manage-user-profile/manage-user-profile.component.ts#L173)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I have changed the name to `showInstitution` now and have made the method output both the institution name and department.
</blockquote></details>

I know this is pedantic, but the method doesn't show anything. So I'd say the name should be some like `institutionString`.
___
*[`src/app/shared/small-loading-spinner/small-loading-spinner.component.scss` line 2 at r13](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1rPYwREudp3yScU0V9:-N1rPYwREudp3yScU0VA:b3tem3f) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/cc26eb9c6cf65d6f8c2b07950da9e8842ca56cb8/src/app/shared/small-loading-spinner/small-loading-spinner.component.scss#L2)):*
> ```SCSS
> /* Taken from https://loading.io/css/ */
> @keyframes ldio-z8iu6izmgd {
> ```

Isn't that a bit of a cryptic name...? :-)


<!-- Sent from Reviewable.io -->

2022-05-12 11:39 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113)* status: 103 of 109 files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 90 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1gkrtX3_Br-3QPeoJ-:-N1rVna86o7a50hpuEET:b-1ginjb) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d54d5ddb9b3bb80adb154c3c131de95ba97c7688/src/app/manage-user-profile/manage-user-profile.component.scss#L90)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I still the `top`, though. I guess we'll have to discuss this. :-)
</blockquote></details>

I do need it, otherwise, the loading spinner shows under the selection element.
___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 93 at r11](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1nWDC90mU4-zeK9Bgr:-N1s2aE5ERNNZc0Cw4PR:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/28bfda3e08e1b74d5229ace933425b4c65c6c118/src/app/manage-user-profile/manage-user-profile.component.scss#L93)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Let's discuss this.
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.ts` line 173 at r11](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1nV0cK7WF6iLErd7Md:-N1rWZ-N-4PogQlnHZWO:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/28bfda3e08e1b74d5229ace933425b4c65c6c118/src/app/manage-user-profile/manage-user-profile.component.ts#L173)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I know this is pedantic, but the method doesn't show anything. So I'd say the name should be some like `institutionString`.
</blockquote></details>

Done.
___
*[`src/app/shared/small-loading-spinner/small-loading-spinner.component.scss` line 2 at r13](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1rPYwREudp3yScU0V9:-N1rh53T1CMakoNy_5Qk:bg6ae32) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/cc26eb9c6cf65d6f8c2b07950da9e8842ca56cb8/src/app/shared/small-loading-spinner/small-loading-spinner.component.scss#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't that a bit of a cryptic name...? :-)
</blockquote></details>

It is, i have changed it now.


<!-- Sent from Reviewable.io -->

2022-05-13 08:08 UTC, hettlage requested changes
> Reviewed 4 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113)* status: 107 of 109 files reviewed, 3 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 6 at r14](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1wPk_f04lf7CrzXv6S:-N1wPk_f04lf7CrzXv6T:b-4fnzy8) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9693dfd94c1b364e57ef54b4a05e63870952f421/src/app/manage-user-profile/manage-user-profile.component.html#L6)):*
> ```HTML
>     <hr class="heading-line edit-contact-info-header" />
>     <div id="select-user" *ngIf="user.roles.includes('Administrator')">
>       <table>
> ```

The alignment isn't perfect, and you don't need a table. Here is how you could achieve vertical centre alignment and get rid of the magic number for the div width.

HTML:

```
    <div id="select-user" *ngIf="user.roles.includes('Administrator')">
      <div>
        <span class="title is-5">Select user</span>
      </div>
      <div>
        <select (change)="onSelectUser($event)">
          <option
            *ngFor="let u of users"
            [value]="u.id"
            [selected]="u.id === selectedUserId"
          >
            {{ u.familyName }}, {{ u.givenName }}
          </option>
        </select>
      </div>
      <div>
        <wm-small-loading-spinner></wm-small-loading-spinner>
      </div>
    </div>
```

CSS:

```
#select-user {
  height: 58px;
  padding: 0 5px 0 20px;
  display: inline-grid;
  align-items: center;
  grid-template-columns: auto auto auto;
  border: 0.15rem dotted rgba(0, 0, 0, 0.5);
}

#select-user select {
  margin-left: 20px;
}
```

Note there still is a somewhat magic width value of 58px, but you could avoid that by adding top and bottom padding,

Also note that the code requires the height of the spinner to be correct (see my comment there).
___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 93 at r11](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1nWDC90mU4-zeK9Bgr:-N1sh_zj2tpVwC1XmAik:bqn2ddy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/28bfda3e08e1b74d5229ace933425b4c65c6c118/src/app/manage-user-profile/manage-user-profile.component.scss#L93)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The dropdown menu 
___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 33 at r14](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1wReUo7_d1v3YOo_BH:-N1wReUo7_d1v3YOo_BI:bktth6a) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9693dfd94c1b364e57ef54b4a05e63870952f421/src/app/manage-user-profile/manage-user-profile.component.scss#L33)):*
> ```SCSS
> 
> select {
>   height: 30px;
> ```

I don't think an explicit height should be set for the input and select element; I think they (the input elements -- the select seems unaffected by the height) look a bit bulky, and (from what I can see) all works fine without the height property.
___
*[`src/app/shared/small-loading-spinner/small-loading-spinner.component.scss` line 82 at r14](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1wP9DxCa4ulB5E-sRY:-N1wP9E-8Fxi7Tq2-l3v:bx2mfbw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9693dfd94c1b364e57ef54b4a05e63870952f421/src/app/shared/small-loading-spinner/small-loading-spinner.component.scss#L82)):*
> ```SCSS
> .small-loading-spinner {
>   width: 51px;
>   height: 51px;
> ```

The height is way too large; it probably is something like 25px.


<!-- Sent from Reviewable.io -->

2022-05-13 08:55 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113)* status: 105 of 109 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 6 at r14](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1wPk_f04lf7CrzXv6S:-N1wcISV7MuYHFgzduS-:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9693dfd94c1b364e57ef54b4a05e63870952f421/src/app/manage-user-profile/manage-user-profile.component.html#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The alignment isn't perfect, and you don't need a table. Here is how you could achieve vertical centre alignment and get rid of the magic number for the div width.

HTML:

```
    <div id="select-user" *ngIf="user.roles.includes('Administrator')">
      <div>
        <span class="title is-5">Select user</span>
      </div>
      <div>
        <select (change)="onSelectUser($event)">
          <option
            *ngFor="let u of users"
            [value]="u.id"
            [selected]="u.id === selectedUserId"
          >
            {{ u.familyName }}, {{ u.givenName }}
          </option>
        </select>
      </div>
      <div>
        <wm-small-loading-spinner></wm-small-loading-spinner>
      </div>
    </div>
```

CSS:

```
#select-user {
  height: 58px;
  padding: 0 5px 0 20px;
  display: inline-grid;
  align-items: center;
  grid-template-columns: auto auto auto;
  border: 0.15rem dotted rgba(0, 0, 0, 0.5);
}

#select-user select {
  margin-left: 20px;
}
```

Note there still is a somewhat magic width value of 58px, but you could avoid that by adding top and bottom padding,

Also note that the code requires the height of the spinner to be correct (see my comment there).
</blockquote></details>

Done.
___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 33 at r14](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1wReUo7_d1v3YOo_BH:-N1wXFA2D05CsKjfYQx4:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9693dfd94c1b364e57ef54b4a05e63870952f421/src/app/manage-user-profile/manage-user-profile.component.scss#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think an explicit height should be set for the input and select element; I think they (the input elements -- the select seems unaffected by the height) look a bit bulky, and (from what I can see) all works fine without the height property.
</blockquote></details>

Done.
___
*[`src/app/shared/small-loading-spinner/small-loading-spinner.component.scss` line 82 at r14](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1wP9DxCa4ulB5E-sRY:-N1wcK3IA9Yr-uheslQ4:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9693dfd94c1b364e57ef54b4a05e63870952f421/src/app/shared/small-loading-spinner/small-loading-spinner.component.scss#L82)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The height is way too large; it probably is something like 25px.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-16 09:19 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113)* status: 106 of 109 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 33 at r14](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N1wReUo7_d1v3YOo_BH:-N2B9GIJDJDVbHnEoo05:baktfm1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9693dfd94c1b364e57ef54b4a05e63870952f421/src/app/manage-user-profile/manage-user-profile.component.scss#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Thanks. They still look bulky, though. Do we need a font size of 14px (which seems to be ignored for select, anyway, at least on Safari)?
</blockquote></details>

No, i don't think it is needed.
___
*[`src/app/shared/small-loading-spinner/small-loading-spinner.component.scss` line 80 at r14](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N2B0dPO9DaSHCiWcco7:-N2B9MIM7tdy5z1g7oCC:bbdin0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9693dfd94c1b364e57ef54b4a05e63870952f421/src/app/shared/small-loading-spinner/small-loading-spinner.component.scss#L80)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It seems that the small loading spinner isn't spinning?
</blockquote></details>

It is spinning now.


<!-- Sent from Reviewable.io -->

2022-05-16 09:25 UTC, hettlage requested changes
> Reviewed 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 96 at r15](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N2BATZO0jjUiDinqTM2:-N2BATZP2m5tKdL373UU:bylo66w) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c09b7f457c9bd91b286acb95c074ab38a30720b9/src/app/manage-user-profile/manage-user-profile.component.scss#L96)):*
> ```SCSS
> 
> .users-loading {
>   padding-top: 15px;
> ```

Now the spinner is not aligned any longer...

By the way, there is a bit of a jump of the page content when the spinner disappears. :(


<!-- Sent from Reviewable.io -->

2022-05-16 10:44 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`src/app/manage-user-profile/manage-user-profile.component.scss` line 96 at r15](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N2BATZO0jjUiDinqTM2:-N2BSjeo4_SN7xjw6p7q:biv7whe) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c09b7f457c9bd91b286acb95c074ab38a30720b9/src/app/manage-user-profile/manage-user-profile.component.scss#L96)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Now the spinner is not aligned any longer...

By the way, there is a bit of a jump of the page content when the spinner disappears. :(
</blockquote></details>

It is now aligned and the jump is also taken care of.


<!-- Sent from Reviewable.io -->

2022-05-16 21:09 UTC, hettlage requested changes
> Reviewed 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 21 at r17](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N2Dgr3v6daweHt9h6fr:-N2Dgr3wCypmHfZLYIkF:bd699l2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2ee20be2e32b15ddbf520d542677a4d594be555d/src/app/manage-user-profile/manage-user-profile.component.html#L21)):*
> ```HTML
>       </div>
>       <div *ngIf="!users" class="users-loading">
>         <div style="position: absolute">
> ```

Given that all the other styles are defined in an scss file, I'd suggest to move this rule there as well.


<!-- Sent from Reviewable.io -->

2022-05-17 07:39 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113)* status: 106 of 109 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`src/app/manage-user-profile/manage-user-profile.component.html` line 21 at r17](https://reviewable.io/reviews/saltastroops/web-manager-2021/113#-N2Dgr3v6daweHt9h6fr:-N2FtM4NDrXlOu4Jbkos:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2ee20be2e32b15ddbf520d542677a4d594be555d/src/app/manage-user-profile/manage-user-profile.component.html#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given that all the other styles are defined in an scss file, I'd suggest to move this rule there as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-17 07:51 UTC, hettlage approved these changes
> Reviewed 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/113)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2022-05-17 07:52 UTC, merged