Grid to table
saltastroops/web-manager-2021 pull request #114
Opened 2022-05-06 10:44 UTC by Eb-Zeero

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/web-manager-2021/114)

2022-05-06 17:21 UTC, hettlage requested changes
I think quite a few table entries should be left-aligned, but it might be easier to discuss this in person.

Also, I think you don't fully exploit the fact that tables don't need a fixed width -- some of the tables still seem a bit wide.

We should also discuss spacing between tables.

The filter column(s) in the RSS spectroscopy table aren't aligned properly.

I wonder whether you could use coloured table headers instead of the coloured squares for the HRS detectors. Or maybe use different table (table header?) backgrounds?

Partner and institution are missing in the Investigators table.

> Reviewed 53 of 53 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/114#-:-N1PN0ZuA7rHt_1YJqvD:b-majhdf)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`src/app/home/home-user/home-user.component.html` line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/114#-N1PN5v10mtOZKw8jjHA:-N1PN5v10mtOZKw8jjHB:b-uw2v1n) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ef7309e365d809b1a4bd71848d08335b8217f573/src/app/home/home-user/home-user.component.html#L1)):*
> ```HTML
> <!--<h1 class="title is-1">Web Manager</h1>-->
> ```

Is this code (still) commented out on purpose?


<!-- Sent from Reviewable.io -->

2022-05-09 13:18 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/114)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`src/app/home/home-user/home-user.component.html` line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/114#-N1PN5v10mtOZKw8jjHA:-N1c6Wur4myhpKAfrbzF:bebruqq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ef7309e365d809b1a4bd71848d08335b8217f573/src/app/home/home-user/home-user.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is this code (still) commented out on purpose?
</blockquote></details>

no it wasn't. Just needed to minimize the scroll while debuging now back


<!-- Sent from Reviewable.io -->

2022-05-10 09:56 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/114)* status: 53 of 56 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`src/styles.scss` line 76 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/114#-N1d1PNg2Vvblh8_PnIR:-N1hD_xV9rjREX3gkfZ6:b-6tsrvi) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c2d66e9f37752ad56bcdf1b1636f6a4f4f847c5/src/styles.scss#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why have you renamed this? Would there be a more meaningful addition than "1"? :)
</blockquote></details>

Can we discuss before I remove this code it is not in use now
___
*[`src/app/types/proposal.ts` line 6 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/114#-N1d2GUg3f9s6djAPMMt:-N1hDZMoBKm-n_e3MsER:b-7ql1td) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c2d66e9f37752ad56bcdf1b1636f6a4f4f847c5/src/app/types/proposal.ts#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why is this no PartnerName any longer?
</blockquote></details>

fixed


<!-- Sent from Reviewable.io -->

2022-05-10 15:41 UTC, hettlage requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/114)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`src/styles.scss` line 76 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/114#-N1d1PNg2Vvblh8_PnIR:-N1ic8iGEU6rF8-A7Euj:brkero5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c2d66e9f37752ad56bcdf1b1636f6a4f4f847c5/src/styles.scss#L76)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Can we discuss before I remove this code it is not in use now
</blockquote></details>

Sure, we can discuss. But I don't see a problem with removing the code if it isn't needed any longer.


<!-- Sent from Reviewable.io -->

2022-05-16 09:25 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/114)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`src/styles.scss` line 76 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/114#-N1d1PNg2Vvblh8_PnIR:-N2B8hhqDkvHIT1JwoDs:b-gf6jfq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c2d66e9f37752ad56bcdf1b1636f6a4f4f847c5/src/styles.scss#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sure, we can discuss. But I don't see a problem with removing the code if it isn't needed any longer.
</blockquote></details>

discussed


<!-- Sent from Reviewable.io -->

2022-05-16 09:25 UTC, Eb-Zeero reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/114#-:-N2BB-DU618GMQT1BuAp:bnfp4nl)* status: 15 of 57 files reviewed, 2 unresolved discussions (waiting on @hettlage)



<!-- Sent from Reviewable.io -->

2022-05-16 21:01 UTC, hettlage requested changes
> Reviewed 42 of 42 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/114)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/app/proposal/blocks/block-summaries/block-summaries.component.html` line 94 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/114#-N2Dc4Cj0pXbpBpKWXHG:-N2Dc4Ck7dDZJahYz3Vt:b-xhuf3c) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c8f8d99a59296c315363b1f5784750c664769d7a/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L94)):*
> ```HTML
>         [attr.data-test]="blockDataTestAttribute(b)"
>       >
>         <td data-test="block-id" [attr.rowspan]="b.instruments.length + 1">{{ b.id }}</td>
> ```

You should add a comment why rowspan must be b.instruments.length + 1, as I don't think this ids intuitively clear.
___
*[`src/app/proposal/instruments/rss/rss-spectroscopy/rss-spectroscopy.component.html` line 18 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/114#-N2Dd5UX3jNEDH7SdVq0:-N2Dd5UX3jNEDH7SdVq1:bctvjxx) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c8f8d99a59296c315363b1f5784750c664769d7a/src/app/proposal/instruments/rss/rss-spectroscopy/rss-spectroscopy.component.html#L18)):*
> ```HTML
>     <tr class="double-boarder">
>       <th>Camera station</th>
>       <td>n/a</td>
> ```

This shouldn't be n/a... :-/

(I've raised an issue, so not need for immediate action.)


<!-- Sent from Reviewable.io -->

2022-05-17 10:27 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/114)* status: 55 of 57 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/blocks/block-summaries/block-summaries.component.html` line 94 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/114#-N2Dc4Cj0pXbpBpKWXHG:-N2GYmls9uFf-6a7b6do:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c8f8d99a59296c315363b1f5784750c664769d7a/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L94)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should add a comment why rowspan must be b.instruments.length + 1, as I don't think this ids intuitively clear.
</blockquote></details>

Done.
___
*[`src/app/proposal/instruments/rss/rss-spectroscopy/rss-spectroscopy.component.html` line 18 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/114#-N2Dd5UX3jNEDH7SdVq0:-N2Fyq7OAkxdmTZDrX3I:ba46fdp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c8f8d99a59296c315363b1f5784750c664769d7a/src/app/proposal/instruments/rss/rss-spectroscopy/rss-spectroscopy.component.html#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This shouldn't be n/a... :-/

(I've raised an issue, so not need for immediate action.)
</blockquote></details>

there so many like this and I added a todo,  this one I just forgot to add a todo


<!-- Sent from Reviewable.io -->

2022-05-17 11:28 UTC, hettlage requested changes
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/114)* status: 56 of 57 files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`src/app/proposal/blocks/block-summaries/block-summaries.component.html` line 95 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/114#-N2GksS77pqqrWLCH2sm:-N2GksS77pqqrWLCH2sn:bbztkja) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/daa7b5002a986cb43ddc7e74e5c87a4208daf435/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L95)):*
> ```HTML
>       >
> <!--    HTML will place one tr next to this one and if there are two rows it will place the next row below it-->
> <!--    the length + 1 is to accommodate to this-->
> ```

How about:

The instrument setups are defined in separate table rows, but need to be displayed to the right of the other columns. This means the other column must extend across their own row as well as the instrument setup rows; hence the need for a rowspan of b.instruments.length + 1.
___
*[`src/app/proposal/blocks/block-summaries/block-summaries.component.html` line 156 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/114#-N2Gklhm5hMgEodTOMTR:-N2Gklhm5hMgEodTOMTS:br4trnh) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/daa7b5002a986cb43ddc7e74e5c87a4208daf435/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L156)):*
> ```HTML
>           </div>
>         </td>
> <!--    HTML will place one tr next to this one and if there are two rows it will place the next row below it-->
> ```

I don't the comment needs to be repeated.


<!-- Sent from Reviewable.io -->

2022-05-17 14:20 UTC, hettlage reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/114)* status: 56 of 57 files reviewed, all discussions resolved (waiting on @hettlage)



<!-- Sent from Reviewable.io -->

2022-05-17 14:23 UTC, merged