Progress report 2
saltastroops/web-manager-2021 pull request #126
Opened 2022-06-23 08:54 UTC by Eb-Zeero

2022-06-23 14:37 UTC, hettlage requested changes
> Reviewed 6 of 46 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/126)* status: 6 of 46 files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`src/app/util.ts` line 13 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5FtA3tA5mYFeTfXOc7:-N5FtA3u2ml-JrsYdze7:bljvwgm) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/270411b4a747aac9225e152a8768f924a1fc09bd/src/app/util.ts#L13)):*
> ```XML
>    The given datetime must be timezone-aware.
>    */
>   const shifted = addHours(addMinutes(t, t.getTimezoneOffset()), 12)
> ```

Ib don't think there is a need to use any timezone information, as long as you stick to getUTC* methods.
___
*[`src/app/util.ts` line 28 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5Fu4pS9YeMtucXAuUu:-N5Fu4pS9YeMtucXAuUv:b3mkm7j) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/270411b4a747aac9225e152a8768f924a1fc09bd/src/app/util.ts#L28)):*
> ```XML
> export function getNextSemester(): string {
>   const today = new Date()
>   return semesterOfDatetime(addMonths(today, 6))
> ```

Is this working properly? What would 31 October + 6 months be? 30 April or 1 May?

It might be safer to get the current semester and use this to get the next?
___
*[`src/app/service/real/real-proposal.service.ts` line 100 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5Fzj75DIcUiRoKUQMi:-N5Fzj75DIcUiRoKUQMj:b2p5chn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/270411b4a747aac9225e152a8768f924a1fc09bd/src/app/service/real/real-proposal.service.ts#L100)):*
> ```XML
>   ): Observable<RequestChangeReasons> {
>     const uri =
>       environment.apiUrl + '/progress/2022-1-SCI-005/2022-1'
> ```

Proposal and semester should not be hardcoded.
___
*[`src/app/service/real/real-proposal.service.ts` line 104 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5FzSjL0re-RaO_44Vu:-N5FzSjL0re-RaO_44Vv:bak02zn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/270411b4a747aac9225e152a8768f924a1fc09bd/src/app/service/real/real-proposal.service.ts#L104)):*
> ```XML
>       // proposalCode + "/" +
>       // semester;
>     return this.http.get<RequestChangeReasons>(uri).pipe(
> ```

RequestChangeReasons sounds like a wrong name for the type.


<!-- Sent from Reviewable.io -->

2022-06-23 18:32 UTC, hettlage requested changes
> Reviewed 34 of 46 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/126)* status: all files reviewed, 22 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`src/app/proposal/general/proposal-progress/proposal-progress.component.html` line 1 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5G3nbwDT7gxGqvf_qb:-N5G3nbwDT7gxGqvf_qc:brghh0u) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/270411b4a747aac9225e152a8768f924a1fc09bd/src/app/proposal/general/proposal-progress/proposal-progress.component.html#L1)):*
> ```HTML
> <div>
> ```

The component isn't handling errors.
___
*[`src/app/proposal/general/proposal-progress/proposal-progress.component.scss` line 5 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GShch-F0r3JamcrMl:-N5GShch-F0r3JamcrMm:bozsbj4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/proposal-progress.component.scss#L5)):*
> ```SCSS
> .progress-report-view {
>   border: 1px solid $table-border-color;
>   //background-color: #f2f6fc;
> ```

Remove commented out line?
___
*[`src/app/proposal/general/proposal-progress/proposal-progress.component.ts` line 41 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5G0p557GuO3vWrveXq:-N5G0p557GuO3vWrveXr:b-9l9507) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/270411b4a747aac9225e152a8768f924a1fc09bd/src/app/proposal/general/proposal-progress/proposal-progress.component.ts#L41)):*
> ```XML
>         (data) => {
>           this.progressReport = {...data};
>           this.showForm = true;
> ```

Shouldn't you set this.loading to false?
___
*[`src/app/proposal/general/proposal-progress/proposal-progress.component.ts` line 17 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GSxQv1OV_xcECNxpm:-N5GSxQwCTnVun4WPLYC:b-p98u1l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/proposal-progress.component.ts#L17)):*
> ```XML
> export class ProposalProgressComponent implements OnInit {
>   @Input() proposal!: Proposal;
>   progressReport!: ProposalProgress;
> ```

For consistency, this variable probably should be called proposalProgress.
___
*[`src/app/proposal/general/proposal-progress/proposal-progress.component.ts` line 21 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GTeJS1F_h09qb68O0:-N5GTeJS1F_h09qb68O1:bbfjzwl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/proposal-progress.component.ts#L21)):*
> ```XML
>   error: string | undefined;
>   loading = false;
>   requestedAmount!: {
> ```

This variable isn't used, is it?
___
*[`src/app/proposal/general/proposal-progress/proposal-progress.component.ts` line 37 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GTqHp7FZWGxMmJ6wi:-N5GTqHp7FZWGxMmJ6wj:b-dwd6r5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/proposal-progress.component.ts#L37)):*
> ```XML
> 
>     this.proposalService
>       .getProgressReport(this.proposal.proposalCode, getNextSemester())
> ```

What happens if the progress report does not exist yet?
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 1 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5G56z16JKIOH3UuYY6:-N5G56z16JKIOH3UuYY7:b-vg0v6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/270411b4a747aac9225e152a8768f924a1fc09bd/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L1)):*
> ```HTML
> <div class="progress-report-form">
> ```

Error handling doesn't work properly for:

- the partner time request fields
- the description of observing constraints
- the reasons request has changed
- the summary of the proposal status
- the strategy changes

[Added later:] Some of these aren't shown because of ".errors" issues reported below.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 2 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GVLv_7_B3hN2soO0u:-N5GVLv_7_B3hN2soO0v:b-x7kr9w) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L2)):*
> ```HTML
> <div class="progress-report-form">
>   <h2 class="title is-5">Requests for next semester {{ nextSemester }}</h2>
> ```

Maybe better:

Requests for next semester ({{ nextSemester }})

(i.e. parentheses around the semester)
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 59 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GUl3b3MlFrznAM6gd:-N5GUl3b3MlFrznAM6ge:b-1gcjwn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L59)):*
> ```HTML
>                 data-test="error"
>               >
>                 Requesting from partner is required
> ```

Maybe better: The percentage for the partners is required

There should also be a check that the sum of percentages is 100 %.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 168 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5Gp0or4FCulVorfcZ4:-N5Gp0or4FCulVorfcZ5:b-u86hm1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L168)):*
> ```HTML
>                 'is-danger':
>                   (f.whyTimeRequestChanged.dirty || submitted) &&
>                   f.whyTimeRequestChanged.errors
> ```

f.whyTimeRequestChanged may be undefined and hence .errors may not exist, which causes all sorts of havoc in the form... :-(
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 182 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GokSg3unie7I1GA3N:-N5GokSh6Vmk39BkRPyh:be5uzg6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L182)):*
> ```HTML
>                 data-test="error"
>               >
>                 Reasons why the time request has changed is required.
> ```

Better: The reasons for the time request change are required.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 32 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GW03S9iwLxNCP_rv5:-N5GW03S9iwLxNCP_rv6:b9gqeuv) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L32)):*
> ```XML
>   constructor(private formBuilder: FormBuilder) { }
> 
>   ngOnInit(): void {
> ```

What about the partner percentages?
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 81 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5Gbl2l2QOPzAFm1qhC:-N5Gbl2l2QOPzAFm1qhD:b-c5pft [...]

2022-06-30 09:09 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/126)* status: 37 of 47 files reviewed, 22 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`src/app/proposal/general/proposal-progress/proposal-progress.component.html` line 1 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5G3nbwDT7gxGqvf_qb:-N5kESf1EcAyyRHBGD-n:bqgm1w0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/270411b4a747aac9225e152a8768f924a1fc09bd/src/app/proposal/general/proposal-progress/proposal-progress.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The component isn't handling errors.
</blockquote></details>

now it is
___
*[`src/app/proposal/general/proposal-progress/proposal-progress.component.scss` line 5 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GShch-F0r3JamcrMl:-N5_f7Yo60a90Kwv3EmU:b-6ib298) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/proposal-progress.component.scss#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Remove commented out line?
</blockquote></details>

it will mean you are happy with the the current view.
___
*[`src/app/proposal/general/proposal-progress/proposal-progress.component.ts` line 41 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5G0p557GuO3vWrveXq:-N5_g2Rl9ETfKELDacwl:b-pdx6k) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/270411b4a747aac9225e152a8768f924a1fc09bd/src/app/proposal/general/proposal-progress/proposal-progress.component.ts#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't you set this.loading to false?
</blockquote></details>

it have to be true to display the form
___
*[`src/app/proposal/general/proposal-progress/proposal-progress.component.ts` line 17 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GSxQv1OV_xcECNxpm:-N5_fWX-CyVBVN5GYfrO:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/proposal-progress.component.ts#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For consistency, this variable probably should be called proposalProgress.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-progress/proposal-progress.component.ts` line 21 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GTeJS1F_h09qb68O0:-N5JylXvEiIlwpRwbxj9:b6ligf6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/proposal-progress.component.ts#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This variable isn't used, is it?
</blockquote></details>

It is used by the component
___
*[`src/app/proposal/general/proposal-progress/proposal-progress.component.ts` line 37 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GTqHp7FZWGxMmJ6wi:-N5_fZyX5QRrAsJy46Fi:b1i06aj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/proposal-progress.component.ts#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What happens if the progress report does not exist yet?
</blockquote></details>

currently nulls are returned i.e progress report will always be something due to some previews info
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 1 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5G56z16JKIOH3UuYY6:-N5kCc4F5JSjEzA0a6EU:b-vop904) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/270411b4a747aac9225e152a8768f924a1fc09bd/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Error handling doesn't work properly for:

- the partner time request fields
- the description of observing constraints
- the reasons request has changed
- the summary of the proposal status
- the strategy changes

[Added later:] Some of these aren't shown because of ".errors" issues reported below.
</blockquote></details>

All is fixed.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 2 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GVLv_7_B3hN2soO0u:-N5JzDdl8gXgbGjfl5lq:b-camb20) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better:

Requests for next semester ({{ nextSemester }})

(i.e. parentheses around the semester)
</blockquote></details>

thanks for (i.e)
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 59 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GUl3b3MlFrznAM6gd:-N5_gRtA-UvXoqPTXPiY:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: The percentage for the partners is required

There should also be a check that the sum of percentages is 100 %.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 168 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5Gp0or4FCulVorfcZ4:-N5kDmbrA_qUsnqruN0X:b-dzhhj6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L168)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

f.whyTimeRequestChanged may be undefined and hence .errors may not exist, which causes all sorts of havoc in the form... :-(
</blockquote></details>

issue fixed now
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 182 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GokSg3unie7I1GA3N:-N5_ggTj7tFxTbHITgqb:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L182)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Better: The reasons for the time request change are required.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 32 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GW03S9iwLxNCP_rv5:-N5kDsW4Arvbw0vu87LT:b-7n8u7z) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What about the partner percentages?
</blockquote></details>

handled out side of of the form
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component [...]

2022-07-04 18:54 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/126)* status: all files reviewed, 23 unresolved discussions (waiting on @hettlage)

___
*[`src/app/utils.ts` line 294 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5oG131Enj3PVmDefXP:-N5tU3b1BhbliTHmXZnd:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/56759fb0f3aba5a99143cd98f7cb2bf3202ab844/src/app/utils.ts#L294)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is a JavaScript function for this already: `iaNaN`
</blockquote></details>

removed
___
*[`src/app/proposal/general/proposal-progress/proposal-progress.component.scss` line 5 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GShch-F0r3JamcrMl:-N5tajnw4SWPEnd3_VrR:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/proposal-progress.component.scss#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ah, you may have a point regarding the background colour. But if you use a background, it should be different from the table background. Maybe something like #eeeeee?
</blockquote></details>

Done.



_Code quote:_
```SCSS
background-color: #f2f6fc;
```
___
*[`src/app/proposal/general/proposal-progress/proposal-progress.component.ts` line 41 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5G0p557GuO3vWrveXq:-N5tcHy55RNdYmV9YyA5:b-9uz4ht) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/270411b4a747aac9225e152a8768f924a1fc09bd/src/app/proposal/general/proposal-progress/proposal-progress.component.ts#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ah, but I said `this.loading`, not `this.showForm`... ;-)
</blockquote></details>

yes sorry
___
*[`src/app/proposal/general/proposal-progress/proposal-progress.component.ts` line 21 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GTeJS1F_h09qb68O0:-N5tbGhbE4Wu-mwPYDWF:bc5osmq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/proposal-progress.component.ts#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But it is only set to be an empty array?
</blockquote></details>

Ahh sorry I thoght it was the form component
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 1 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5G56z16JKIOH3UuYY6:-N68vA3Y7U8qOysS5_z0:b-ljwcle) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/270411b4a747aac9225e152a8768f924a1fc09bd/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L1)):*
the seeing error only shows after submiting sence the user anter valid.
> The reason for a time request change is only required if there actually is a change. [Feel free to raise an issue if you want to fix this later.]
I belive this is for South African partners only.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 50 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5oNoCwAsqCL55Jcj7q:-N682LPi4GPRvmnehng2:bvxrnbv) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/56759fb0f3aba5a99143cd98f7cb2bf3202ab844/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L50)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why the `|| submitted`?
</blockquote></details>

Yes not here
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 54 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5oNsSMCEEB-GUqZQmG:-N685HC61Kfn6zTLRqeK:bt7xozf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/56759fb0f3aba5a99143cd98f7cb2bf3202ab844/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L54)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why the `|| submitted`?
</blockquote></details>

yes not here
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 216 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5oOM02CkHF6i1SdE66:-N68Ux1uBA217cNWYM7s:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/56759fb0f3aba5a99143cd98f7cb2bf3202ab844/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L216)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Summary > The summary
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 247 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5oOHGC68Y-cOs3hghv:-N68UzRf7b6_S5Go6kxA:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/56759fb0f3aba5a99143cd98f7cb2bf3202ab844/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L247)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The strategy changes are required,
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 81 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5Gbl2l2QOPzAFm1qhC:-N69Ye_a68M1LVwU08rg:br83tkb) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L81)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This error might be misleading; the form might be invalid for other reasons.
</blockquote></details>

So far this is all I need to bring out else will come when new erros arise 
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 82 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GbvPE1QlYdPEhLRss:-N69Yve5DJz34l2oOUIV:b-bs8h4w) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L82)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For reasons unknown to me the error message is not displayed.

[Added later:] I've figured it out. It's the .errors issue reported above for the template file.
</blockquote></details>

thi sshould be solved now.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 56 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5oxIUGCVgCLrWeeBVL:-N69XlkU-Xy_lPiW3sgO:b-2k42d5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/56759fb0f3aba5a99143cd98f7cb2bf3202ab844/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L56)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm a bit worried about handling the perf engages outside the form (builder). Maybe https://www.telerik.com/blogs/angular-basics-creating-dynamic-forms-using-formarray-angular helps?
</blockquote></details>

I might be getting this wrong.
I am creating a form and I need a name to be dynamic..
can you please explane more about this.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form [...]

2022-07-05 12:08 UTC, hettlage requested changes
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/126)* status: all files reviewed, 16 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 1 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5G56z16JKIOH3UuYY6:-N6D6hj88-86LI0P8KsY:b-w2pv6k) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/270411b4a747aac9225e152a8768f924a1fc09bd/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L1)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

the seeing error only shows after submiting sence the user anter valid.
> The reason for a time request change is only required if there actually is a change. [Feel free to raise an issue if you want to fix this later.]
I belive this is for South African partners only.
</blockquote></details>

New/existing issues:

* The time request field for OTH accepts values not equal to 0.
* You get no error if the time request percentages don't add up to 100.
* If you choose "Select" for the transparency, there is no error.
* The reason for a time request change is only required if there actually is a change. [Feel free to raise an issue if you want to fix this later.]
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 59 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GUl3b3MlFrznAM6gd:-N6DBtHx4_ZTW0I6PnkH:b-nuiez4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L59)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This might not be working yet?
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 54 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6D4iNREnXd7lJViAKA:-N6D4iNS0srkmzxWaPKT:b-j1feas) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b868f19eecb8a05773e963699c5f30a121cd761d/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L54)):*
> ```HTML
>               [ngClass]="{
>                   'is-danger':
>                     (requestedPercentageError[p.partnerCode] && p.partnerCode !== 'OTH')
> ```

That looks odd. An error should be an error, irrespective of the partner.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 58 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6D4rZk7Y61yXzdOfoj:-N6D4rZk7Y61yXzdOfok:b-j1feas) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b868f19eecb8a05773e963699c5f30a121cd761d/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L58)):*
> ```HTML
>             />
>             <p
>               *ngIf="requestedPercentageError[p.partnerCode] && p.partnerCode !== 'OTH'"
> ```

That looks odd. An error should be an error, irrespective of the partner.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 261 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6DBNwi3dlQm6tURp03:-N6DBNwi3dlQm6tURp04:b-kk55pb) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b868f19eecb8a05773e963699c5f30a121cd761d/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L261)):*
> ```HTML
>                 data-test="error"
>               >
>                 The strategy changes is required
> ```

changes is > changes are
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 81 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5Gbl2l2QOPzAFm1qhC:-N6DFDs65ybAQ-qwpYZL:b-gqisyz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L81)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

So far this is all I need to bring out else will come when new erros arise 
</blockquote></details>

Oh, I see. The problem is that the rest his checked elsewhere.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 56 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5oxIUGCVgCLrWeeBVL:-N6DEEU6AJE04jUc14qQ:blqrxvn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/56759fb0f3aba5a99143cd98f7cb2bf3202ab844/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L56)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I might be getting this wrong.
I am creating a form and I need a name to be dynamic..
can you please explane more about this.
</blockquote></details>

Can we chat about this?
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 96 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6DFOxE4M1EVWV9SZ_S:-N6DFOxFDxRqix4-xV98:b-8azo63) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/56759fb0f3aba5a99143cd98f7cb2bf3202ab844/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L96)):*
> ```XML
>       }
>     })
>     this.progressReport.partnerRequestedPercentages.forEach(r => {
> ```

Aren't these lines just a duplicate of the lines above?
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 101 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6DFYIBE4gcyYQ5nbBS:-N6DFYIBE4gcyYQ5nbBT:b-kj5z8l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/56759fb0f3aba5a99143cd98f7cb2bf3202ab844/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L101)):*
> ```XML
>         return
>       }
>       if(r.requestedPercentage) {
> ```

Aren't these lines unnecessary?
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 159 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5ovCH350FWL3BoN8Ix:-N6DDP1C7AxxlcXV5WyZ:baggsw2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/56759fb0f3aba5a99143cd98f7cb2bf3202ab844/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L159)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'd still use

```
The requested percentage for ${partnerCode} is required.
```

or

```
The requested percentage for the partner ${partnerCode} is required.
```
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 162 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6DDuPw9rnoDhPuS6eV:-N6DDuPw9rnoDhPuS6eW:b-qsjfbn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/56759fb0f3aba5a99143cd98f7cb2bf3202ab844/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L162)):*
> ```XML
>     } else {
>       if (!parseFloat(value)) {
>         this.requestedPercentageError[partnerCode] = "Partner requested percentag [...]

2022-07-08 12:05 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/126)* status: 44 of 47 files reviewed, 16 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 1 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5G56z16JKIOH3UuYY6:-N6SfsAq5pZWrLuoKYT8:b-pqvipy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/270411b4a747aac9225e152a8768f924a1fc09bd/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

New/existing issues:

* The time request field for OTH accepts values not equal to 0.
* You get no error if the time request percentages don't add up to 100.
* If you choose "Select" for the transparency, there is no error.
* The reason for a time request change is only required if there actually is a change. [Feel free to raise an issue if you want to fix this later.]
</blockquote></details>

* now disabled
* now there is an error
* select is now disabled
* will raise an issue
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 59 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GUl3b3MlFrznAM6gd:-N6O-XMm1La3KtSnzadI:b-qtg0p6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This might not be working yet?
</blockquote></details>

this is checked when you submit the form.
to avoid having an error when you are chaging percentage values 
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 54 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6D4iNREnXd7lJViAKA:-N6O-F442FBHvdoV9jV7:b-xopysj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b868f19eecb8a05773e963699c5f30a121cd761d/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L54)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That looks odd. An error should be an error, irrespective of the partner.
</blockquote></details>

disabling the input now.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 58 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6D4rZk7Y61yXzdOfoj:-N6O-KlO2ynejUOsGZoS:bjjybl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b868f19eecb8a05773e963699c5f30a121cd761d/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L58)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That looks odd. An error should be an error, irrespective of the partner.
</blockquote></details>

input is now disabled
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 261 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6DBNwi3dlQm6tURp03:-N6O-yFrBkBshGLdwfsV:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b868f19eecb8a05773e963699c5f30a121cd761d/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L261)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

changes is > changes are
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 81 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5Gbl2l2QOPzAFm1qhC:-N6O0cT47Hd0GGB8BoTx:b2nign6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L81)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oh, I see. The problem is that the rest his checked elsewhere.
</blockquote></details>

yes
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 96 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6DFOxE4M1EVWV9SZ_S:-N6O0Vve92C175vqvtc5:b-tfmgq6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/56759fb0f3aba5a99143cd98f7cb2bf3202ab844/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L96)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Aren't these lines just a duplicate of the lines above?
</blockquote></details>

yes it was removed
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 101 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6DFYIBE4gcyYQ5nbBS:-N6O0uEeCJp3h0Ci5IFl:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/56759fb0f3aba5a99143cd98f7cb2bf3202ab844/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L101)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Aren't these lines unnecessary?
</blockquote></details>

removed
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 159 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5ovCH350FWL3BoN8Ix:-N6N3xb63hVY9NV5fJaz:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/56759fb0f3aba5a99143cd98f7cb2bf3202ab844/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L159)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd still use

```
The requested percentage for ${partnerCode} is required.
```

or

```
The requested percentage for the partner ${partnerCode} is required.
```

</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 162 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6DDuPw9rnoDhPuS6eV:-N6Nzufz5BzD_ROHFoJs:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/56759fb0f3aba5a99143cd98f7cb2bf3202ab844/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L162)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: The percentage should be a non-negative number.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 20 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6DBd2L9ikmiB7ZIXvi:-N6O01R6-17gR0xWRC7_:brpmqc3) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b868f19eecb8a05773e963699c5f30a121cd761d/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Note used anywhere?
</blockquote></details>

removed.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 135 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6D8yRn4QrlH4KgnFtp:-N6O13xJDOqxtxGRSVWj:b-w7ba6n) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b868f19eecb8a05773e963699c5f30a121cd761d/src/app/proposal/general/proposal-progress/progress-request-form/progress-req [...]

2022-07-08 13:16 UTC, hettlage requested changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/126)* status: all files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 1 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5G56z16JKIOH3UuYY6:-N6Sq5WTEzv1nNsKaQFB:bhyvg5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/270411b4a747aac9225e152a8768f924a1fc09bd/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L1)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

* now disabled
* now there is an error
* select is now disabled
* will raise an issue
</blockquote></details>

The "adding up to 100 %" error handling needs tweaking.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 59 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GUl3b3MlFrznAM6gd:-N6Swpj80KrU9LumWu7_:bfxi739) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L59)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

this is checked when you submit the form.
to avoid having an error when you are chaging percentage values 
</blockquote></details>

But isn't this inconsistent with the way the other errors are handled?
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 47 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6SqviZAw9BWQwq-FPr:-N6SqviZAw9BWQwq-FPs:bfwqzuj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c57660a701dc6cb3efcceeca2cf09afc5970bd2/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L47)):*
> ```HTML
>         >
>           <tr class="row" [formGroupName]="i">
>             <td>Requested from {{ t.value.name }}</td>
> ```

Nitpicking perhaps, but shouldn't `name` rather be `partnerCode`?
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 130 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6SrXS9DuNQn9Pp52n0:-N6SrXSA60idSUb0GQBP:b-hrmqqo) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c57660a701dc6cb3efcceeca2cf09afc5970bd2/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L130)):*
> ```HTML
>                 formControlName="transparency"
>               >
>                 <option [ngValue]="''" disabled>Select</option>
> ```

This might be counter-intuitive if no transparency value has been chosen yet.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 32 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6SrlAt2AXTz7khFuK2:-N6SrlAt2AXTz7khFuK3:b-p382hz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c57660a701dc6cb3efcceeca2cf09afc5970bd2/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L32)):*
> ```XML
> 
>   ngOnInit(): void {
>     let variable: FormGroup[] = []
> ```

Maybe choose another variable name?
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 33 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6Sru--8brEsb7ethXC:-N6Sru--8brEsb7ethXD:bx7tb1r) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c57660a701dc6cb3efcceeca2cf09afc5970bd2/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L33)):*
> ```XML
>   ngOnInit(): void {
>     let variable: FormGroup[] = []
>     this.progressReport.partnerRequestedPercentages.forEach(p => {
> ```

You could have used `map` instead... ;-)
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 48 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6SsGFt7qXeNNfDYARE:-N6SsGFt7qXeNNfDYARF:bot2vq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c57660a701dc6cb3efcceeca2cf09afc5970bd2/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L48)):*
> ```XML
> 
>     this.progressReport.partnerRequestedPercentages.forEach((r) => {
>       if (r.partnerCode === "RSA") {
> ```

Sorry, I had missed that. I'm pretty sure these fields should *always* be displayed.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 103 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6Ssh39-_qRi5gzhQV6:-N6Ssh39-_qRi5gzhQV7:bydpr2b) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c57660a701dc6cb3efcceeca2cf09afc5970bd2/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L103)):*
> ```XML
>   changeTransparency(e: Event): void {
>     if((e.target as HTMLSelectElement).value === ""){
>       this.f.transparency.setValue((e.target as HTMLSelectElement).value, {
> ```

Aren't you doing the same here in both cases?
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 125 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6SuCXq8QAGeEwmlpgj:-N6SuCXrEWSlAywGPsM2:bu2yduu) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c57660a701dc6cb3efcceeca2cf09afc5970bd2/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L125)):*
> ```XML
>   }
> 
>   validateForm(): void {
> ```

`validateForm` might be misleading -- you are only validating the sum of percentages here.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 128 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6Sw2is5WEvfQMFD8Wj:-N6Sw2is5WEvfQMFD8Wk:bpw3mxa) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c57660a701dc6cb3efcceeca2cf09afc5970bd2/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L128)):*
> ```XML
>     let totalRequestedPercentage = 0
>     this.partnerRequestedPercentages?.controls.forEach(p => {
>       if(p.value.name !== "OTH") {
> ```

I don't think you should exclude OTH here -- if for whatever reason the percentage was non-zero for OTH, not should be added.
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 129 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6SswkHAMsHyk3fIzWw:-N6SswkHAMsHyk3fIzWx:b-qahkc7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c57660a701dc6cb3efcceeca2cf09afc5970bd2/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L129)):*
> ```XML
>     this.partnerRequestedPercentages?.controls.forEach(p => {
>       if(p.value.name !== "OTH") {
>         totalRequestedPercentage += Number(p.value.requestedPercentages) | 0
> ```

Shouldn't `|`be `||`?


<!-- Sent from Reviewable.io -->

2022-07-08 19:05 UTC, hettlage requested changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/126)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 130 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6SrXS9DuNQn9Pp52n0:-N6UA4EeAx7RY8CAbChN:b-c334nl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c57660a701dc6cb3efcceeca2cf09afc5970bd2/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L130)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

select will show
</blockquote></details>

But it will be show as disabled (won't it), and that might be misinterpreted as meaning that the whole dropdown menu is disabled.


<!-- Sent from Reviewable.io -->

2022-07-11 07:19 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/126)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 59 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N5GUl3b3MlFrznAM6gd:-N6g7DCeDzNtJoNmlkyw:bjy1gy9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1053c43728ef69e3225dd7da52dad9b016855a99/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But isn't this inconsistent with the way the other errors are handled?
</blockquote></details>

this is now fixed
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 130 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6SrXS9DuNQn9Pp52n0:-N6g7-mB9aZS3qZ9YsAg:b-46soih) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c57660a701dc6cb3efcceeca2cf09afc5970bd2/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L130)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But it will be show as disabled (won't it), and that might be misinterpreted as meaning that the whole dropdown menu is disabled.
</blockquote></details>

it doesn't show disabled..
it only prevent users from selecting it


<!-- Sent from Reviewable.io -->

2022-07-11 08:20 UTC, hettlage approved these changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/126)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 130 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/126#-N6SrXS9DuNQn9Pp52n0:-N6gKroU34_BtbB5NSU0:b-gb73lr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c57660a701dc6cb3efcceeca2cf09afc5970bd2/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L130)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

it doesn't show disabled..
it only prevent users from selecting it

</blockquote></details>

Indeed. My bad.


<!-- Sent from Reviewable.io -->

2022-07-11 08:44 UTC, Eb-Zeero reviewed
> Reviewed 27 of 27 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/126)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2022-07-11 09:16 UTC, hettlage approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/126)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2022-07-11 09:53 UTC, merged