Block summary
saltastroops/web-manager-2021 pull request #20
Opened 2021-05-19 10:53 UTC by Eb-Zeero

2021-05-19 12:56 UTC, hettlage requested changes
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/20)* status: all files reviewed, 14 unresolved discussions (waiting on @Eb-Zeero)

___
*[frontend/src/app/types.ts, line 16 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3Sw9D5TrhPcNbS3q3:-Ma3Sw9D5TrhPcNbS3q4:bg6uvnk) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/types.ts#L16)):*
> ```XML
> }
> 
> interface Instrument {
> ```

I don't think there should be an interface for this.

maximumLunarPhase does not belong to the instrument.
___
*[frontend/src/app/types.ts, line 21 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3T9wlEgW_OoG7olBi:-Ma3T9wlEgW_OoG7olBj:b-gwbhn0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/types.ts#L21)):*
> ```XML
>   configMode: string
> }
> export interface Block {
> ```

We should discuss the name.
___
*[frontend/src/app/types.ts, line 26 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3U1EY31phYSiBLDj-:-Ma3U1EY31phYSiBLDj0:bv0fzxv) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/types.ts#L26)):*
> ```XML
>   obsTime: number
>   priority: number
>   totalBlockVisits: number
> ```

totalBlockVisits --> requestedBlockVisits
___
*[frontend/src/app/types.ts, line 27 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3U71qBHxGgEURiYrW:-Ma3U71qBHxGgEURiYrX:b-6ehxid) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/types.ts#L27)):*
> ```XML
>   priority: number
>   totalBlockVisits: number
>   blockVisited: number
> ```

blockVisited ---> doneVisits
___
*[frontend/src/app/types.ts, line 28 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3UANX-cguCy6YIGp6:-Ma3UANX-cguCy6YIGp7:b-ji4kr1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/types.ts#L28)):*
> ```XML
>   totalBlockVisits: number
>   blockVisited: number
>   tonight: boolean
> ```

tonight ---> observableTonight
___
*[frontend/src/app/types.ts, line 29 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3UJe90LGm4pELZiHV:-Ma3UJe90LGm4pELZiHW:b-5yynxr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/types.ts#L29)):*
> ```XML
>   blockVisited: number
>   tonight: boolean
>   remaining: number
> ```

remaining ---> remainingNights
___
*[frontend/src/app/proposal/proposal.component.html, line 10 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3Uo5jBQ1__NbknTBW:-Ma3Uo5jBQ1__NbknTBX:b-5ieaq3) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/proposal.component.html#L10)):*
> ```HTML
> 
> 
> <div *ngIf="proposal | async as p">
> ```

Can be simplified -- you only need the ngIf once. (Every async would make its own HTTP request, so it's worth simplifying. :-) )
___
*[frontend/src/app/proposal/target-summary/target-summary.component.html, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3VG3285HZ2xFaqGJy:-Ma3VG3285HZ2xFaqGJz:b1f8ta5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.html#L1)):*
> ```HTML
> <div>
> ```

This is a _block_ summary, not a target summary, and you should change the names accordingly.
___
*[frontend/src/app/proposal/target-summary/target-summary.component.html, line 22 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3gFPvC0a3iQ8uPb3W:-Ma3gFPvC0a3iQ8uPb3X:b-65ooon) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.html#L22)):*
> ```HTML
>     <div>Max Lunar Phase</div>
>     <div>Instrument</div>
>     <div>ConfigMode</div>
> ```

ConfigMode --> Config Mode
___
*[frontend/src/app/proposal/target-summary/target-summary.component.html, line 30 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3ZH3s23S0PNFGU9ch:-Ma3ZH3s23S0PNFGU9ci:bqa7gqb) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.html#L30)):*
> ```HTML
>       <div>{{b.priority}}</div>
>       <div>{{b.blockVisited}}/{{b.totalBlockVisits}}</div>
>       <div *ngIf="b.tonight"><mat-icon class="icon-green">done</mat-icon></div>
> ```

I wonder whether that cannot be generalised?
___
*[frontend/src/app/proposal/target-summary/target-summary.component.html, line 38 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3fa4Y8YlV2V-qbe_N:-Ma3fa4Y8YlV2V-qbe_O:bo2nyqi) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.html#L38)):*
> ```HTML
>       </div>
>       <div>
>         <mat-icon *ngIf="b.transparency === 'Any'">cloud_circle</mat-icon>
> ```

I like the idea of icons. But can we discuss the icons used?
___
*[frontend/src/app/proposal/target-summary/target-summary.component.scss, line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3XxIc51RIH05ldPZr:-Ma3XxIc51RIH05ldPZs:bjwkxli) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.scss#L8)):*
> ```SCSS
> 
> .top-row >div {
>   background: #666;
> ```

Might need some discussion.
___
*[frontend/src/app/proposal/target-summary/target-summary.component.scss, line 15 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3Yk066xaLfqETID4I:-Ma3Yk066xaLfqETID4J:b-6ct4f0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.scss#L15)):*
> ```SCSS
> .block-row {
>   display: grid;
>   grid-template-columns:15% repeat(7, 7.857142857%) 3.333333% repeat(2, 8.333333%) 10%;
> ```

The grid-template-columns values can be simplified.
___
*[frontend/src/app/proposal/target-summary/target-summary.component.ts, line 13 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3Z3c42Y44qeS4NnyI:-Ma3Z3c42Y44qeS4NnyJ:b-lc5ydm) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.ts#L13)):*
> ```XML
>   @Input() blocks!: Block[];
>   @Input() proposalCode!: string;
>   apiUrl = environment.apiUrl
> ```

Why do you need the API URL?


<!-- Sent from Reviewable.io -->

2021-05-19 14:53 UTC, Eb-Zeero reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-:-Ma44i29BWwuuFm8xoqJ:bnfp4nl)* status: all files reviewed, 14 unresolved discussions (waiting on @hettlage)

___
*[frontend/src/app/types.ts, line 16 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3Sw9D5TrhPcNbS3q3:-Ma43jdE49gRbuxghgOE:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/types.ts#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think there should be an interface for this.

maximumLunarPhase does not belong to the instrument.
</blockquote></details>

Done.
___
*[frontend/src/app/types.ts, line 21 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3T9wlEgW_OoG7olBi:-Ma43lAo824gVE0JdktM:bb7s9zc) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/types.ts#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

We should discuss the name.
</blockquote></details>

yes
___
*[frontend/src/app/types.ts, line 26 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3U1EY31phYSiBLDj-:-Ma44-Je4Y9ZDAF3W84r:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/types.ts#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

totalBlockVisits --> requestedBlockVisits
</blockquote></details>

Done.
___
*[frontend/src/app/types.ts, line 27 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3U71qBHxGgEURiYrW:-Ma44-ghE1_DGOLvooes:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/types.ts#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

blockVisited ---> doneVisits
</blockquote></details>

Done.
___
*[frontend/src/app/types.ts, line 28 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3UANX-cguCy6YIGp6:-Ma447mIBWKL3ShhYYt3:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/types.ts#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

tonight ---> observableTonight
</blockquote></details>

Done.
___
*[frontend/src/app/types.ts, line 29 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3UJe90LGm4pELZiHV:-Ma448AU4b8M2O86TKUn:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/types.ts#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

remaining ---> remainingNights
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/proposal.component.html, line 10 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3Uo5jBQ1__NbknTBW:-Ma44fnn3htr311-XiP0:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/proposal.component.html#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can be simplified -- you only need the ngIf once. (Every async would make its own HTTP request, so it's worth simplifying. :-) )
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/target-summary/target-summary.component.html, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3VG3285HZ2xFaqGJy:-Ma45vx93FgHDwOMI_IK:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is a _block_ summary, not a target summary, and you should change the names accordingly.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/target-summary/target-summary.component.html, line 22 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3gFPvC0a3iQ8uPb3W:-Ma46-oPCLH5yt_kOjpZ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.html#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

ConfigMode --> Config Mode
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/target-summary/target-summary.component.html, line 30 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3ZH3s23S0PNFGU9ch:-Ma46Sqt1vXSoLV65Yh3:b27qcns) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.html#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I wonder whether that cannot be generalised?
</blockquote></details>

help me please
___
*[frontend/src/app/proposal/target-summary/target-summary.component.html, line 38 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3fa4Y8YlV2V-qbe_N:-Ma46AV088j81sBp36fs:b-k73z76) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.html#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I like the idea of icons. But can we discuss the icons used?
</blockquote></details>

thanks
___
*[frontend/src/app/proposal/target-summary/target-summary.component.scss, line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3XxIc51RIH05ldPZr:-Ma46CPb4PyWFwGzLmbW:b-7j86r2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.scss#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Might need some discussion.
</blockquote></details>

sure,
___
*[frontend/src/app/proposal/target-summary/target-summary.component.scss, line 15 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3Yk066xaLfqETID4I:-Ma46IYz5GvDJOa6sZJA:b-x8jvk5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.scss#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The grid-template-columns values can be simplified.
</blockquote></details>

can we discuss this
___
*[frontend/src/app/proposal/target-summary/target-summary.component.ts, line 13 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3Z3c42Y44qeS4NnyI:-Ma46MV5-Dp8zajPaNDx:b-t37jwq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.ts#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you need the API URL?
</blockquote></details>

for the href


<!-- Sent from Reviewable.io -->

2021-05-19 19:05 UTC, hettlage requested changes
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/20)* status: all files reviewed, 17 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/src/app/types.ts, line 25 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma4zUDQDfPFBGXjaGyJ:-Ma4zUDQDfPFBGXjaGyK:b-gl45qa) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e218194b3510b6111c0cd78180a018bc399f5a4b/frontend/src/app/types.ts#L25)):*
> ```XML
>   observableTonight: boolean
>   remainingNights: number
>   maximum_seeing: number
> ```

maximun_seeing ---> maximumnSeeing
___
*[frontend/src/app/proposal/proposal.component.html, line 2 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma4zls-7fJvaXrmQ7Hj:-Ma4zls-7fJvaXrmQ7Hk:b-o94v7q) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e218194b3510b6111c0cd78180a018bc399f5a4b/frontend/src/app/proposal/proposal.component.html#L2)):*
> ```HTML
> <div *ngIf="proposal | async as p">
>   <div>
> ```

I don't think this div is needed.
___
*[frontend/src/app/proposal/proposal.component.html, line 5 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma4zqzqA6b5mdBKh43d:-Ma4zqzqA6b5mdBKh43e:b-o94v7q) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e218194b3510b6111c0cd78180a018bc399f5a4b/frontend/src/app/proposal/proposal.component.html#L5)):*
> ```HTML
>     <h1>This is proposal {{ proposalCode }}.</h1>
>   </div>
>   <div>
> ```

I don't think this div is needed.
___
*[frontend/src/app/proposal/proposal.component.html, line 8 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma4zwyN4Oim9dk3ACdS:-Ma4zwyN4Oim9dk3ACdT:b-o94v7q) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e218194b3510b6111c0cd78180a018bc399f5a4b/frontend/src/app/proposal/proposal.component.html#L8)):*
> ```HTML
>     <wm-investigators [investigators]="p.investigators"></wm-investigators>
>   </div>
>   <div >
> ```

I don't think this div is needed.
___
*[frontend/src/app/proposal/block-summary/block-summary.component.html, line 34 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma5-bTS0LKYMfDPBGV9:-Ma5-bTS0LKYMfDPBGVA:b-2j3tzn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e218194b3510b6111c0cd78180a018bc399f5a4b/frontend/src/app/proposal/block-summary/block-summary.component.html#L34)):*
> ```HTML
>       <div>{{b.remainingNights}}</div>
>       <div>{{b.maximum_seeing}}</div>
>       <div>
> ```

This works fine. But you might consider combining the text and the icon in a single column and setting the text width.
___
*[frontend/src/app/proposal/target-summary/target-summary.component.scss, line 15 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3Yk066xaLfqETID4I:-Ma5-8D-9J_YSmvf5s54:b-7l9hk5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.scss#L15)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

can we discuss this
</blockquote></details>

Absolutely. :-)
___
*[frontend/src/app/proposal/target-summary/target-summary.component.ts, line 13 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3Z3c42Y44qeS4NnyI:-Ma5-J2f3aTeWiz4mkAz:br5ypt1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.ts#L13)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

for the href
</blockquote></details>

But href would link to web pages, not API endpoints?


<!-- Sent from Reviewable.io -->

2021-05-20 15:24 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/20)* status: 4 of 8 files reviewed, 17 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/src/app/types.ts, line 25 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma4zUDQDfPFBGXjaGyJ:-Ma7ztUx1dJZM9rdskUJ:bnejapp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e218194b3510b6111c0cd78180a018bc399f5a4b/frontend/src/app/types.ts#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

maximun_seeing ---> maximumnSeeing
</blockquote></details>

did the opposite on evry naming as it was the opposite for investigator table
___
*[frontend/src/app/proposal/proposal.component.html, line 2 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma4zls-7fJvaXrmQ7Hj:-Ma8-O7k5wkZvYu4DlKi:b-bqpfjy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e218194b3510b6111c0cd78180a018bc399f5a4b/frontend/src/app/proposal/proposal.component.html#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this div is needed.
</blockquote></details>

fo rnow you are correct all the tables will be restyled in the future
___
*[frontend/src/app/proposal/proposal.component.html, line 5 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma4zqzqA6b5mdBKh43d:-Ma8-Wtn86t2T4LW1hHU:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e218194b3510b6111c0cd78180a018bc399f5a4b/frontend/src/app/proposal/proposal.component.html#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this div is needed.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/proposal.component.html, line 8 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma4zwyN4Oim9dk3ACdS:-Ma8-XMF0KiFPTuQiCUw:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e218194b3510b6111c0cd78180a018bc399f5a4b/frontend/src/app/proposal/proposal.component.html#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this div is needed.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/target-summary/target-summary.component.scss, line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3XxIc51RIH05ldPZr:-Ma9L5Q1DhNEmdP39Rzn:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.scss#L8)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

sure,
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/target-summary/target-summary.component.ts, line 13 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-Ma3Z3c42Y44qeS4NnyI:-Ma9Mxal-NvRbYHJ0MNn:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/da2111891ee5d5d24c88d79fa17fc0b32a5152e4/frontend/src/app/proposal/target-summary/target-summary.component.ts#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But href would link to web pages, not API endpoints?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-21 10:18 UTC, hettlage requested changes
> Reviewed 3 of 4 files at r3, 6 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/20)* status: 6 of 11 files reviewed, 14 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/src/styles.scss, line 34 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDIgYq1s1JyDHvp1bm:-MaDIgYrEbSTun3DN3mo:b-6mgxzi) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/styles.scss#L34)):*
> ```SCSS
> }
> .headers > div {
>   background: cornflowerblue;
> ```

Another candidate for a variable, perhaps. But let's discuss this.
___
*[frontend/src/app/proposal/block-summary/block-summaries.component.html, line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDL5hyBfFYvEq8vJgT:-MaDL5hyBfFYvEq8vJgU:b-vuhak4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/app/proposal/block-summary/block-summaries.component.html#L1)):*
> ```HTML
> <div>
> ```

You've renamed the files, but not the parent folder. :)
___
*[frontend/src/app/proposal/block-summary/block-summaries.component.html, line 35 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDORoC3iGIA8jhxj9v:-MaDORoC3iGIA8jhxj9w:bok1c1h) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/app/proposal/block-summary/block-summaries.component.html#L35)):*
> ```HTML
>       <div class="spanned">
>         <span>{{b.transparency}}</span>
>         <span>
> ```

This span is unnecessary.
___
*[frontend/src/app/proposal/block-summary/block-summaries.component.html, line 36 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDOefu07bsv_DRkhHq:-MaDOefu07bsv_DRkhHr:b7z91r1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/app/proposal/block-summary/block-summaries.component.html#L36)):*
> ```HTML
>         <span>{{b.transparency}}</span>
>         <span>
>           <mat-icon *ngIf="b.transparency === 'Any'">cloud_circle</mat-icon>
> ```

It might be slightly cleaner to use a dedicated component for the icon. (But let's discuss this first.)
___
*[frontend/src/app/proposal/block-summary/block-summaries.component.scss, line 16 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDN0FSARc8_NzmmUTN:-MaDN0FSARc8_NzmmUTO:bej4wph) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/app/proposal/block-summary/block-summaries.component.scss#L16)):*
> ```SCSS
> .block-row {
>   display: grid;
>   grid-template-columns:15% repeat(8, 1fr) 18%;
> ```

The transparency column should be wider.
___
*[frontend/src/app/proposal/block-summary/block-summaries.component.scss, line 30 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDMtX9EakjHjis2YEw:-MaDMtX9EakjHjis2YEx:b8x6a5a) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/app/proposal/block-summary/block-summaries.component.scss#L30)):*
> ```SCSS
>   color: green;
> }
> .spanned {
> ```

Consider a different t name, such as "transparency".
___
*[frontend/src/app/proposal/block-summary/block-summaries.component.ts, line 3 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDNrYCDxd6Gk06p-pD:-MaDNrYCDxd6Gk06p-pE:b7qs9as) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/app/proposal/block-summary/block-summaries.component.ts#L3)):*
> ```XML
> import {Component, Input, OnInit} from '@angular/core';
> import {BlockSummary} from "../../types";
> import {environment} from "../../../environments/environment";
> ```

Unnecessary import


<!-- Sent from Reviewable.io -->

2021-05-21 10:34 UTC, hettlage requested changes
> Reviewed 5 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/20)* status: all files reviewed, 13 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/src/app/proposal/block-summary/block-summaries.component.html, line 35 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDORoC3iGIA8jhxj9v:-MaDRdlS5wdCvhlQ1rH0:b42025q) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/app/proposal/block-summary/block-summaries.component.html#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This span is unnecessary.
</blockquote></details>

Oh. Ist seems it _is_ necessary. Sorry,
___
*[frontend/src/app/proposal/block-summary/block-summaries.component.scss, line 34 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDUAja4Hg_6v9NsQu0:-MaDUAja4Hg_6v9NsQu1:b9dhoox) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/app/proposal/block-summary/block-summaries.component.scss#L34)):*
> ```SCSS
>   grid-template-columns:70% 30%;
> }
> .instrument-section {
> ```

How about the following instead of having the instrument-section class? 

```
.instrument-container  {
  > div {
    display: grid;
    grid-template-columns:30% 70%;
  }

  > :nth-child(n+2) {
    border-top: .01em solid white;
  }
}
```


<!-- Sent from Reviewable.io -->

2021-05-21 12:54 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/20)* status: all files reviewed, 13 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/src/styles.scss, line 34 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDIgYq1s1JyDHvp1bm:-MaDxJJJ9WTMPTUfkJSk:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/styles.scss#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Another candidate for a variable, perhaps. But let's discuss this.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/block-summary/block-summaries.component.html, line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDL5hyBfFYvEq8vJgT:-MaDxRjK-Qgi_FEiwCPa:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/app/proposal/block-summary/block-summaries.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You've renamed the files, but not the parent folder. :)
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/block-summary/block-summaries.component.html, line 35 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDORoC3iGIA8jhxj9v:-MaDx_EfAAxjVxqrx24M:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/app/proposal/block-summary/block-summaries.component.html#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oh. Ist seems it _is_ necessary. Sorry,
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/block-summary/block-summaries.component.html, line 36 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDOefu07bsv_DRkhHq:-MaDxchBDl38iIm3uj1H:ba1qqkx) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/app/proposal/block-summary/block-summaries.component.html#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be slightly cleaner to use a dedicated component for the icon. (But let's discuss this first.)
</blockquote></details>

yes we need to
___
*[frontend/src/app/proposal/block-summary/block-summaries.component.scss, line 16 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDN0FSARc8_NzmmUTN:-MaDySeG2U4HS6pdmShr:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/app/proposal/block-summary/block-summaries.component.scss#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The transparency column should be wider.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/block-summary/block-summaries.component.scss, line 30 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDMtX9EakjHjis2YEw:-MaDyYwl7mxQ1ewGZRbs:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/app/proposal/block-summary/block-summaries.component.scss#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Consider a different t name, such as "transparency".
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/block-summary/block-summaries.component.scss, line 34 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDUAja4Hg_6v9NsQu0:-MaDzM8vE4Mzynx6ErDv:b-zajzs2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/app/proposal/block-summary/block-summaries.component.scss#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

How about the following instead of having the instrument-section class? 

```
.instrument-container  {
  > div {
    display: grid;
    grid-template-columns:30% 70%;
  }

  > :nth-child(n+2) {
    border-top: .01em solid white;
  }
}
```
</blockquote></details>

it is not working
___
*[frontend/src/app/proposal/block-summary/block-summaries.component.ts, line 3 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDNrYCDxd6Gk06p-pD:-MaDzRB1-Ot26GEWivzj:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/app/proposal/block-summary/block-summaries.component.ts#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary import
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-21 14:15 UTC, hettlage requested changes
> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/20)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[frontend/src/styles.scss, line 34 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaDIgYq1s1JyDHvp1bm:-MaE8AqoEvNP6d08cNsi:b-h3ef2c) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/03575568183867be77edacce0b9c34272e05fb1c/frontend/src/styles.scss#L34)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

How about a name without "blue"? :)
___
*[frontend/src/styles.scss, line 39 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/20#-MaEAIBd6JuasmcZn7y1:-MaEAIBd6JuasmcZn7y2:b-5r2zcz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/0cb7ead184f55fd434d67b144e2fea427b8fa8b5/frontend/src/styles.scss#L39)):*
> ```SCSS
>   text-align: left;
>   font-weight: bolder;
>   font-size: 18px;
> ```

Using rem might be better


<!-- Sent from Reviewable.io -->

2021-05-21 18:06 UTC, merged