Block observing conditions
saltastroops/web-manager-2021 pull request #45
Opened 2021-06-28 19:39 UTC by saltastroops

2021-07-01 14:51 UTC, hettlage requested changes
> Reviewed 9 of 12 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/45)* status: all files reviewed, 32 unresolved discussions (waiting on @saltastroops)

___
*[frontend/src/app/types.ts, line 152 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWGg9B5KK9HRlxwLoF:-MdWGg9B5KK9HRlxwLoG:blsfu7f) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L152)):*
> ```XML
>   observationTime: number;
> }
> export interface Iterations {
> ```

I don't think you can group these properties together. They probably appear elsewhere already as well:

wait: defined on block level
visits/attempted/done/shutterOpenTime: follow from observations (block visits)
___
*[frontend/src/app/types.ts, line 159 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWGGKk4ZNxaqmVL-kR:-MdWGGKk4ZNxaqmVL-kS:bjnx63e) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L159)):*
> ```XML
>   shutterOpenTime: number;
> }
> export interface Probability {
> ```

Maybe better: ObservationProbabilities
___
*[frontend/src/app/types.ts, line 167 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWGQde3iq_rX19pISn:-MdWGQde3iq_rX19pISo:beo9zsm) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L167)):*
> ```XML
>   total: number;
> }
> export interface Observability {
> ```

Maybe better: ObservingWindow
___
*[frontend/src/app/types.ts, line 168 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXUW8YAzvlLYUICicj:-MdXUW8YAzvlLYUICick:btu6kst) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L168)):*
> ```XML
> }
> export interface Observability {
>   startWindow: Date;
> ```

startWindow --> start
___
*[frontend/src/app/types.ts, line 169 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXUYnF7fQLAkDW9bWl:-MdXUYnF7fQLAkDW9bWm:b-yvvg7u) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L169)):*
> ```XML
> export interface Observability {
>   startWindow: Date;
>   endWindow: Date;
> ```

endWindow ---> end
___
*[frontend/src/app/types.ts, line 170 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWHHb63MGfUx5sXtdT:-MdWHHb63MGfUx5sXtdU:b1m7gzz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L170)):*
> ```XML
>   startWindow: Date;
>   endWindow: Date;
>   type: string;
> ```

Should be an enum.
___
*[frontend/src/app/types.ts, line 173 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWryrd7ucP5OxV7cJo:-MdWryrd7ucP5OxV7cJp:btku36d) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L173)):*
> ```XML
> }
> 
> export interface BlockGeneralDetails {
> ```

Do you need a BlockGeneralDetails type in addition a Block type?
___
*[frontend/src/app/types.ts, line 177 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWsLV-EedCYfo7-rEW:-MdWsLV-EedCYfo7-rEX:b-n14jod) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L177)):*
> ```XML
>   iterations: Iterations;
>   overheads: number;
>   totalObservationTime: number;
> ```

Is that per visit or for all visits? Maybe call it observationTime and ensure it is per visit?
___
*[frontend/src/app/types.ts, line 179 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWs96wEwZjfUnzOXNT:-MdWs96xAgdsHubc5HRI:bowqlkv) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L179)):*
> ```XML
>   totalObservationTime: number;
>   priority: number;
>   comments: string;
> ```

Isn't that "comment"?
___
*[frontend/src/app/proposal/proposal.component.html, line 62 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXY6PrCfrX-PFsnF37:-MdXY6PrCfrX-PFsnF38:bbiy1l9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/proposal.component.html#L62)):*
> ```HTML
>   <!--  TODO: Allocation is semester dependent will fix it -->
>   
>   <div *ngIf="block | async as b" class="block">
> ```

The ngIf should nee unnecessary
___
*[frontend/src/app/proposal/proposal.component.ts, line 7 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWtKlT8D6GMysEsL_4:-MdWtKlT8D6GMysEsL_5:b-f7oqg7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/proposal.component.ts#L7)):*
> ```XML
> import {Block, Proposal} from '../types';
> import { MockProposalService } from '../mock/service/mock-proposal.service';
> import {BlockService} from '../service/block.service';
> ```

This component should not query for the block.
___
*[frontend/src/app/proposal/proposal.component.ts, line 17 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWtWrP-ztJ3EnQWE9o:-MdWtWrP-ztJ3EnQWE9p:b-gaag9l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/proposal.component.ts#L17)):*
> ```XML
> export class ProposalComponent implements OnInit {
>   proposalCode = '';
>   blockCode = 0;
> ```

Should not be necessary.
___
*[frontend/src/app/proposal/proposal.component.ts, line 19 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWtiIECNRLBoiZTyAV:-MdWtiIECNRLBoiZTyAW:b-gaag9l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/proposal.component.ts#L19)):*
> ```XML
>   blockCode = 0;
>   proposal!: Observable<Proposal>;
>   block!: Observable<Block>;
> ```

Should not be necessary.
___
*[frontend/src/app/proposal/proposal.component.ts, line 24 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWtq3g1wLg_ZAK_qh0:-MdWtq3g1wLg_ZAK_qh1:b-gaag9l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/proposal.component.ts#L24)):*
> ```XML
>     private route: ActivatedRoute,
>     private proposalService: ProposalService,
>     private blockService: BlockService
> ```

Should not be necessary.
___
*[frontend/src/app/proposal/proposal.component.ts, line 31 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWtrsL5D2SLWkX4anQ:-MdWtrsL5D2SLWkX4anR:b-gaag9l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/proposal.component.ts#L31)):*
> ```XML
>     this.proposalCode = routeParams.get('proposal-code') || '';
>     this.proposal = this.proposalService.getProposal(this.proposalCode);
>     this.block = this.blockService.getBlock(9999);
> ```

Should not be necessary.
___
*[frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.html, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXMO9sEePr3gWxRiF6:-MdXMO9sEePr3gWxRiF7:b9ysqck) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.html#L1)):*
> ```HTML
> <div class="table">
> ```

I think the name "observing-conditions" is too narrow for this component's content.
___
*[frontend/src/app/proposal/block/observing-co [...]

2021-07-02 10:07 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/45)* status: 4 of 12 files reviewed, 32 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[frontend/src/app/types.ts, line 159 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWGGKk4ZNxaqmVL-kR:-MdaIFZ_-rvtM6n4milT:b-sel15) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L159)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: ObservationProbabilities
</blockquote></details>



done
___
*[frontend/src/app/types.ts, line 167 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWGQde3iq_rX19pISn:-MdaIHPW-K3ywLoUbkrp:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L167)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: ObservingWindow
</blockquote></details>

done
___
*[frontend/src/app/types.ts, line 168 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXUW8YAzvlLYUICicj:-MdaIO7G-wg2q9kusE01:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L168)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

startWindow --> start
</blockquote></details>

done
___
*[frontend/src/app/types.ts, line 169 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXUYnF7fQLAkDW9bWl:-MdaIOzA2tn6Ax7Icrkg:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L169)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

endWindow ---> end
</blockquote></details>

done
___
*[frontend/src/app/types.ts, line 170 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWHHb63MGfUx5sXtdT:-MdaJVvqEAB7wh3USfRs:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L170)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be an enum.
</blockquote></details>

done
___
*[frontend/src/app/types.ts, line 177 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWsLV-EedCYfo7-rEW:-MdaMHUe1JYfcB1WVJzQ:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L177)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is that per visit or for all visits? Maybe call it observationTime and ensure it is per visit?
</blockquote></details>

done
___
*[frontend/src/app/types.ts, line 179 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWs96wEwZjfUnzOXNT:-MdaMIZZ5JBdSBU9r7-S:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L179)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't that "comment"?
</blockquote></details>

done
___
*[frontend/src/app/proposal/proposal.component.ts, line 7 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWtKlT8D6GMysEsL_4:-MdaPtiy9kfY52wgHx8F:b8glwjc) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/proposal.component.ts#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This component should not query for the block.
</blockquote></details>

Ahh yes I missed that
___
*[frontend/src/app/proposal/proposal.component.ts, line 17 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWtWrP-ztJ3EnQWE9o:-MdaPyCHEGvDdiNEfzQY:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/proposal.component.ts#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should not be necessary.
</blockquote></details>

done
___
*[frontend/src/app/proposal/proposal.component.ts, line 19 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWtiIECNRLBoiZTyAV:-MdaPzsq2o-F9vG3ng4_:b2nign6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/proposal.component.ts#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should not be necessary.
</blockquote></details>

yes
___
*[frontend/src/app/proposal/proposal.component.ts, line 24 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWtq3g1wLg_ZAK_qh0:-MdaQ-uh3RJ70wNROAHi:b2nign6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/proposal.component.ts#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should not be necessary.
</blockquote></details>

yes
___
*[frontend/src/app/proposal/proposal.component.ts, line 31 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWtrsL5D2SLWkX4anQ:-MdaQ1-iExlY0WotasRo:b2nign6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/proposal.component.ts#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should not be necessary.
</blockquote></details>

yes
___
*[frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.html, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXMO9sEePr3gWxRiF6:-MdaRphTELN20zsH2Yhg:b-3gkrav) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the name "observing-conditions" is too narrow for this component's content.
</blockquote></details>

please lets discuss
___
*[frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.html, line 85 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXK8k3Ack5YtUvY-Ew:-MdaRvg3EL7v1Ko1S-kT:b3kre) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.html#L85)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should be placed somewhere else.
</blockquote></details>

?
___
*[frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts, line 16 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXU3dh2cfEO28E-m5R:-MdaSVeuAnZIqR4Noe3x:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better just tonight(), start and end?
</blockquote></details>

done
___
*[frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts, line 18 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXWGNJ3PgG6bKXJ8wc:-MdaSZQMB4tI9KTIis4v:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockq [...]

2021-07-05 12:13 UTC, Eb-Zeero requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/45)* status: 4 of 12 files reviewed, 33 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[frontend/src/app/types.ts, line 173 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWryrd7ucP5OxV7cJo:-MdqMG8K9DRCpGEy7cR0:bqxmxnc) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L173)):*
> ObservingWindow
removed
___
*[frontend/src/app/types.ts, line 158 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdal96y9FwXyOGsYKdr:-Mdal96z-qJ5Xx9sS0da:b-yu42qq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b36b526514e9f38433d3f0b469ee84bd8af033e4/frontend/src/app/types.ts#L158)):*
> ```XML
>   attempted: number;
>   done: number;
>   shutterOpenTime: number;
> ```

difference between the obsTime and overheads
___
*[frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts, line 30 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXWaPT2VyrqWuNjarW:-Mdq_E335OusRj7PSBD7:b-hiojed) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts#L30)):*
> This should only be based on the strict observing windows.
done
___
*[frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts, line 31 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXUhpB8RGmGwaSV-n1:-Mdq_I2MA6TcdDVLf2Uw:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

o.endWindow > this.... ---> o.endWindow >= this....
</blockquote></details>

done
___
*[frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts, line 34 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXVl4KC0EMdCtojp20:-Mdq_K5F25S4r3FADoVo:bnad4ke) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why don't you return null in this case?
</blockquote></details>

udefined is returned
___
*[frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts, line 37 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXWrBqAuBliKD9ri6I:-Mdq_Q-V38RF4sk_WdLA:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

< ---> <=

You should check which window types are included.
</blockquote></details>

done
___
*[frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts, line 39 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXXZPa8wJrIovd_4PD:-Mdq_S9A78UYdJELZdMT:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts#L39)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

> Why don't you return null in this case?
done
</blockquote></details>

done
___
*[frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts, line 41 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXXlzG-INIt2RxlEla:-Mdq_UNCEllxm-zH9smc:b-v12xga) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Use a date-fns function.
</blockquote></details>

using moment will remove date fns


<!-- Sent from Reviewable.io -->

2021-07-05 15:11 UTC, hettlage requested changes
> Reviewed 2 of 8 files at r3, 37 of 37 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/45)* status: all files reviewed, 35 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[frontend/package.json, line 23 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdrDDFZ0vlytwuocBpv:-MdrDDFZ0vlytwuocBpw:b-gaag9l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/package.json#L23)):*
> ```JSON
>     "@testing-library/angular": "^10.8.1",
>     "bulma": "^0.9.2",
>     "moment": "^2.29.1",
> ```

Should not be necessary.
___
*[frontend/src/app/types.ts, line 170 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWHHb63MGfUx5sXtdT:-MdqxEuv9CRPQgWmM0Pa:bsrusud) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L170)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

done
</blockquote></details>

I still see string as the type...
___
*[frontend/src/app/types.ts, line 181 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdqxSHXDAAdl1ps086j:-MdqxSHXDAAdl1ps086k:bew4aac) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L181)):*
> ```XML
>   comments: string;
>   observabilities: Observability[];
>   probability: Probability;
> ```

probability ---> probabilities
___
*[frontend/src/app/mock/service/mock-block.service.ts, line 21 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdqxpW_950HSoCy5YkG:-MdqxpW_950HSoCy5YkH:b-mwusgo) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/mock/service/mock-block.service.ts#L21)):*
> ```XML
>       id,
>       name: `Block-${id}`,
>       ...blockGeneralDetails
> ```

This works, but at some point in the future you might wonder where this blockGeneralDetails comes from... :-)
___
*[frontend/src/app/proposal/block/block.component.html, line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdqyfps1lDiSjx_YDF5:-Mdqyfps1lDiSjx_YDF6:b-x6ucyz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/block.component.html#L10)):*
> ```HTML
>     <wm-probability-table></wm-probability-table>
>   </div>
>   <wm-block-comment
> ```

The name looks a bit odd, given that only one third of the content is a block comment... I have no better name, though.
___
*[frontend/src/app/proposal/block/block.component.html, line 14 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdqyGMr0Pe0xbD8bUua:-MdqyGMr0Pe0xbD8bUub:b10sgvx) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/block.component.html#L14)):*
> ```HTML
>     [priority]="block.priority"
>     [lastModified]="block.lastModified"></wm-block-comment>
>   <wm-observing-window [observingWindows]="block.observingWindows"></wm-observing-window>
> ```

wm-observing-window ---> wm-observing-windows
___
*[frontend/src/app/proposal/block/block-comment/block-comment.component.ts, line 9 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdqzXmt4hQFWEDVsyWV:-MdqzXmt4hQFWEDVsyWW:b-etsgk8) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/block-comment/block-comment.component.ts#L9)):*
> ```XML
> })
> export class BlockCommentComponent implements OnInit {
>   @Input() comment!: string;
> ```

The comment might be null.
___
*[frontend/src/app/proposal/block/iterations/iterations.component.ts, line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdr--mU8gBOMgYiH2Qt:-Mdr--mU8gBOMgYiH2Qu:bs03653) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/iterations/iterations.component.ts#L10)):*
> ```XML
> })
> export class IterationsComponent implements OnInit {
>   @Input() iterations!: Iterations;
> ```

Wasn't the Iterations type supposed to go away?
___
*[frontend/src/app/proposal/block/observing-window/observing-window.component.html, line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdr8geoBrbOXrLXZ_Q4:-Mdr8geoBrbOXrLXZ_Q5:bqn5yhi) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/observing-window/observing-window.component.html#L1)):*
> ```HTML
> <div>
> ```

Having the table spread across the whole window might be detrimental for large window widths.

The windows aren't sorted by date/time.

The times before 10:00 should have a leading 0 (so that the times are aligned).
___
*[frontend/src/app/proposal/block/observing-window/observing-window.component.html, line 31 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdr9TYGDrbXMi3OP2_V:-Mdr9TYGDrbXMi3OP2_W:b-wfx1su) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/observing-window/observing-window.component.html#L31)):*
> ```HTML
>         <div>{{observationNight(o) | dfnsFormat: "d MMMM yyyy"}}</div>
>         <div>{{o.start | dfnsFormat: "H:mm:ss" }} - {{o.end | dfnsFormat: "H:mm:ss" }}</div>
>         <div>{{(o.end.setDate(o.end.getDate()) - o.start.setDate(o.start.getDate()))/1000}}</div>
> ```

This looks odd... Why do you need the setDate?
___
*[frontend/src/app/proposal/block/observing-window/observing-window.component.ts, line 18 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdr9dq5CE7ZYldNg-vB:-Mdr9dq5CE7ZYldNg-vC:b9ygpn4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/observing-window/observing-window.component.ts#L18)):*
> ```XML
> 
>   ngOnInit(): void {
>     this.blockObservableTonight = this.tonightsObservingWindow();
> ```

this.tonightsObservingWindows is always truthy.
___
*[frontend/src/app/proposal/block/observing-window/observing-window.component.ts, line 21 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdrBBrtD5uN7ldkrvtC:-MdrBBrtD5uN7ldkrvtD:bf6b5wh) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/observing-window/observing-window.component.ts#L21)):*
> ```XML
>   }
>   tonight(): {start: Date, end: Date} {
>     let night = moment(new Date());
> ```

You can add/subtract with date-fns: https://date-fns.org/v2.22.1/docs/add
___
*[frontend/src/app/proposal/block/observing-window/observing-window.component.ts, line 32 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdrBS9h8rVBGJBsEK73:-MdrBS9h8rVBGJBsEK74:b36sql3) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/observing-window/observing-window.component.ts#L32)):*
> ```XML
>   tonightsObservingWindow(): ObservingWindow | undefined {
>     const night = this.tonight();
>     return this.observingWindows.find(o => (o.end >= night.start &&
> ```

You should add a TODO that this might have to take the window type into account.
___
*[frontend/src/app/proposal/block/observing-window/observing-window.component.ts, line 35 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdrBg-5BQGLUPRXYFtj:-MdrBg-5BQGLUPRXYFtk:bamgptp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/observing-window/observing-w [...]

2021-07-06 09:03 UTC, Eb-Zeero approved these changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/45)* status: all files reviewed, 34 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[frontend/package.json, line 23 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdrDDFZ0vlytwuocBpv:-Mdv0_0v6qspKUtksvpk:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/package.json#L23)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should not be necessary.
</blockquote></details>

removed
___
*[frontend/src/app/mock/service/mock-block.service.ts, line 21 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdqxpW_950HSoCy5YkG:-MdujVldAFzeZ3kW4TeI:b-7rsi37) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/mock/service/mock-block.service.ts#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This works, but at some point in the future you might wonder where this blockGeneralDetails comes from... :-)
</blockquote></details>

This is a mocked data as you say it will all go
___
*[frontend/src/app/proposal/proposal.component.html, line 62 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXY6PrCfrX-PFsnF37:-MdujhNmApXet1yFw0mc:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/proposal.component.html#L62)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The ngIf should nee unnecessary
</blockquote></details>

removed
___
*[frontend/src/app/proposal/block/block.component.html, line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdqyfps1lDiSjx_YDF5:-Mdv1Pl9DuzY6JnSD7af:b1z321u) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/block.component.html#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name looks a bit odd, given that only one third of the content is a block comment... I have no better name, though.
</blockquote></details>

reanmed to priority-comment
___
*[frontend/src/app/proposal/block/block.component.html, line 14 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdqyGMr0Pe0xbD8bUua:-Mdv1S6y18_E0XMig3KP:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/block.component.html#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

wm-observing-window ---> wm-observing-windows
</blockquote></details>

done
___
*[frontend/src/app/proposal/block/block-comment/block-comment.component.ts, line 9 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdqzXmt4hQFWEDVsyWV:-Mdv1VTu57MSNmVVhb9v:b-7ql1td) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/block-comment/block-comment.component.ts#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The comment might be null.
</blockquote></details>

fixed
___
*[frontend/src/app/proposal/block/iterations/iterations.component.ts, line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdr--mU8gBOMgYiH2Qt:-MdumHQq428OcaqWvCBH:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/iterations/iterations.component.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wasn't the Iterations type supposed to go away?
</blockquote></details>

removed
___
*[frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts, line 27 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXTUtk414_9UlbVLIS:-MdumSCnCxkCD-5V_nwy:b3kre) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should only be based on the strict observing windows.

o.end
</blockquote></details>

?
___
*[frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts, line 41 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdXXlzG-INIt2RxlEla:-Mdv1au50EsS86e70cFl:blyplad) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/proposal/block/observing-conditions/observing-conditions.component.ts#L41)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

using moment will remove date fns
</blockquote></details>

removed moment
___
*[frontend/src/app/proposal/block/observing-window/observing-window.component.html, line 31 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdr9TYGDrbXMi3OP2_V:-Mdv1fPW241HQY3xWMaT:b-t0swcf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/observing-window/observing-window.component.html#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This looks odd... Why do you need the setDate?
</blockquote></details>

uding date fns now
___
*[frontend/src/app/proposal/block/observing-window/observing-window.component.ts, line 21 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdrBBrtD5uN7ldkrvtC:-Mdv1r68B3guf8Vw7ucM:b-nl7js) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/observing-window/observing-window.component.ts#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You can add/subtract with date-fns: https://date-fns.org/v2.22.1/docs/add
</blockquote></details>

I was using ng-date-fns now both are installed
___
*[frontend/src/app/proposal/block/observing-window/observing-window.component.ts, line 32 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdrBS9h8rVBGJBsEK73:-Mdv254N-IJQ9CC-dHSb:bx2guas) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/observing-window/observing-window.component.ts#L32)):*
> TODO that this might have to take the window type into account.
you need to reexplain this it is confusing me now
___
*[frontend/src/app/proposal/block/observing-window/observing-window.component.ts, line 35 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdrBg-5BQGLUPRXYFtj:-Mdv2BIx1It9tHtFGWnf:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/observing-window/observing-window.component.ts#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

toggleObservingWindow ---> toggleObservingWindows
</blockquote></details>

done
___
*[frontend/src/app/proposal/block/observing-window/observing-window.component.ts, line 35 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdrBmLs9Lm5qxNAYeib:-Mdv2RP-AW_lAcJsTzrX:b-7tfmjp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/observing-window/observing-window.component.ts#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to add an empty line between the methods.
</blockquote></details>

added
___
 [...]

2021-07-06 10:09 UTC, hettlage requested changes
> Reviewed 18 of 18 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/45)* status: all files reviewed, 17 unresolved discussions (waiting on @Eb-Zeero, @hettlage, and @saltastroops)

___
*[frontend/src/app/types.ts, line 170 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWHHb63MGfUx5sXtdT:-MdvGICZ-v7WINZjY-qp:b-wnyv98) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L170)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I still see string as the type...
</blockquote></details>

Can we discuss this?
___
*[frontend/src/app/types.ts, line 173 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWryrd7ucP5OxV7cJo:-MdvE0plAfsWwLWUxd23:b-kgwme6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L173)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

> ObservingWindow
removed
</blockquote></details>

But do you actually use the interface anywhere?
___
*[frontend/src/app/mock/service/mock-block.service.ts, line 21 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdqxpW_950HSoCy5YkG:-MdvG23b1rVy1PH7Gaze:b-wnyv98) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/mock/service/mock-block.service.ts#L21)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

This is a mocked data as you say it will all go
</blockquote></details>

Can we discuss this?
___
*[frontend/src/app/proposal/block/iterations/iterations.component.ts, line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdr--mU8gBOMgYiH2Qt:-MdvExiuDh0ieN4gcHmL:b-wnyv98) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/iterations/iterations.component.ts#L10)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

removed
</blockquote></details>

Can we discuss this?
___
*[frontend/src/app/proposal/block/block-comment/block-comment.component.html, line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdv6fRJBf0-5vFm4PSP:-Mdv6fRJBf0-5vFm4PSQ:btit691) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/block-comment/block-comment.component.html#L10)):*
> ```HTML
>     <div>{{priority}}</div>
>     <div>
>       <p>{{comment | nl2br}}</p>
> ```

Why have you removed this?
___
*[frontend/src/app/proposal/block/observing-windows/observing-windows-component.component.ts, line 7 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdv8blm4KsLmKtI6CrJ:-Mdv8blm4KsLmKtI6CrK:b3tcgk2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3673caa0ffc6aa3088ee3fd596314491ab334933/frontend/src/app/proposal/block/observing-windows/observing-windows-component.component.ts#L7)):*
> ```XML
> @Component({
>   selector: 'wm-observing-windows',
>   templateUrl: './observing-windows-component.component.html',
> ```

Why did you add "-component" to the name?
___
*[frontend/src/app/proposal/block/observing-windows/observing-windows-component.component.ts, line 15 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdv8QEz95KLCtOpO_CR:-Mdv8QF-DXCoAxt9BSLa:b-7rnzau) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3673caa0ffc6aa3088ee3fd596314491ab334933/frontend/src/app/proposal/block/observing-windows/observing-windows-component.component.ts#L15)):*
> ```XML
>   showObservingWindow = false;
>   blockObservableTonight: ObservingWindow | undefined = undefined;
>   differenceInSeconds = differenceInSeconds;
> ```

If this is necessary, you might add a comment why.
___
*[frontend/src/app/proposal/block/observing-windows/observing-windows-component.component.ts, line 53 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdv85EICjOZopCmQh6Z:-Mdv85EICjOZopCmQh6_:bywt954) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3673caa0ffc6aa3088ee3fd596314491ab334933/frontend/src/app/proposal/block/observing-windows/observing-windows-component.component.ts#L53)):*
> ```XML
> 
>   sortedObservingWindow(): ObservingWindow[] {
>     return this.observingWindows.sort((a, b) => (a.start <= b.start) ? 1 : -1);
> ```

How about: (a, b) => a.start - b.start (which covers equality as well ;-) )


<!-- Sent from Reviewable.io -->

2021-07-06 11:01 UTC, Eb-Zeero approved these changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/45)* status: all files reviewed, 17 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[frontend/src/app/types.ts, line 173 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdWryrd7ucP5OxV7cJo:-MdvJHKW9NVqOMTJsFxY:b-jkbog3) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8c9812353170fa646503a6ae1b2d562a96f21988/frontend/src/app/types.ts#L173)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But do you actually use the interface anywhere?
</blockquote></details>

no and removed
___
*[frontend/src/app/mock/service/mock-block.service.ts, line 21 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-MdqxpW_950HSoCy5YkG:-MdvJQ262nj5D81VVNXm:b2nign6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/mock/service/mock-block.service.ts#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we discuss this?
</blockquote></details>

yes
___
*[frontend/src/app/proposal/block/iterations/iterations.component.ts, line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdr--mU8gBOMgYiH2Qt:-MdvJVIW4zJfOos5vLhi:b2nign6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/iterations/iterations.component.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we discuss this?
</blockquote></details>

yes
___
*[frontend/src/app/proposal/block/block-comment/block-comment.component.html, line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdv6fRJBf0-5vFm4PSP:-MdvTU3B2dJ-FgsOfzsd:bn1u4w4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/block-comment/block-comment.component.html#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why have you removed this?
</blockquote></details>

comment showed the tag instead of breking the comment
___
*[frontend/src/app/proposal/block/observing-window/observing-window.component.ts, line 18 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdr9dq5CE7ZYldNg-vB:-MdvKJI1Bmvh7tR4XxSi:b-p9popo) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/observing-window/observing-window.component.ts#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

this.tonightsObservingWindows is always truthy.
</blockquote></details>

is it 
___
*[frontend/src/app/proposal/block/observing-windows/observing-windows-component.component.ts, line 7 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdv8blm4KsLmKtI6CrJ:-MdvJubS64-x5BgBJw09:bb793p5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3673caa0ffc6aa3088ee3fd596314491ab334933/frontend/src/app/proposal/block/observing-windows/observing-windows-component.component.ts#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why did you add "-component" to the name?
</blockquote></details>

mistake removed
___
*[frontend/src/app/proposal/block/observing-windows/observing-windows-component.component.ts, line 15 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdv8QEz95KLCtOpO_CR:-MdvK5QhEeeSCey57WZN:b-33khgw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3673caa0ffc6aa3088ee3fd596314491ab334933/frontend/src/app/proposal/block/observing-windows/observing-windows-component.component.ts#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If this is necessary, you might add a comment why.
</blockquote></details>

I can explain why on our discussion


<!-- Sent from Reviewable.io -->

2021-07-07 07:19 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/45)* status: 34 of 40 files reviewed, 17 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[frontend/src/app/proposal/block/block-comment/block-comment.component.html, line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdv6fRJBf0-5vFm4PSP:-MdvfleS-RualYyEd6XD:bqetged) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/block-comment/block-comment.component.html#L10)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

comment showed the tag instead of breking the comment
</blockquote></details>

now fixed
___
*[frontend/src/app/proposal/block/observing-window/observing-window.component.html, line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdr8geoBrbOXrLXZ_Q4:-Mdznn8-3pUOcKZSYS16:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/09cc0ccc61832503ab8309d7834053383b693d0f/frontend/src/app/proposal/block/observing-window/observing-window.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Having the table spread across the whole window might be detrimental for large window widths.

The windows aren't sorted by date/time.

The times before 10:00 should have a leading 0 (so that the times are aligned).


</blockquote></details>

done
___
*[frontend/src/app/proposal/block/observing-windows/observing-windows-component.component.ts, line 53 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Mdv85EICjOZopCmQh6Z:-MdzoNzpD8ZJxOnPFPnx:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3673caa0ffc6aa3088ee3fd596314491ab334933/frontend/src/app/proposal/block/observing-windows/observing-windows-component.component.ts#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

How about: (a, b) => a.start - b.start (which covers equality as well ;-) )
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-07-07 13:47 UTC, mofokeng-chaka requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/45)* status: 25 of 41 files reviewed, 18 unresolved discussions (waiting on @Eb-Zeero, @hettlage, and @saltastroops)

___
*[frontend/src/app/proposal/block/priority-comment/priority-comment.component.html, line 12 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/45#-Me0CYis44a5ZGoouJFQ:-Me0CYis44a5ZGoouJFR:b-xbxa08) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2521e31fe1944993fef67f97019e3207232c1fc4/frontend/src/app/proposal/block/priority-comment/priority-comment.component.html#L12)):*
> ```HTML
>       <p [innerHTML]="comment | nl2br"></p>
>     </div>  <!--      Todo comments to discuss  -->
>     <div><button class="button">Edit block</button></div>
> ```

I think the table will look better with the button centred across the column


<!-- Sent from Reviewable.io -->

2021-07-08 08:08 UTC, hettlage approved these changes
> Reviewed 2 of 6 files at r7, 10 of 11 files at r8, 6 of 6 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/45)* status: all files reviewed, 1 unresolved discussion (waiting on @saltastroops)



<!-- Sent from Reviewable.io -->

2021-07-08 08:14 UTC, merged