Some of the rss Tables
saltastroops/web-manager-2021 pull request #48
Opened 2021-07-01 11:10 UTC by Eb-Zeero

2021-07-08 13:02 UTC, hettlage requested changes
> Reviewed 49 of 49 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/48)* status: all files reviewed, 17 unresolved discussions (waiting on @Eb-Zeero)

___
*[frontend/src/styles.scss, line 144 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me52REU2QVOTxbJ-TFk:-Me52REU2QVOTxbJ-TFl:b-9ft4gl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/styles.scss#L144)):*
> ```SCSS
>   grid-template-columns: repeat(2, 1fr);
> }
> .has-3-columns {
> ```

For consistency: .has-3-columns --> .has-three-columns
___
*[frontend/src/app/types.ts, line 155 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me57abd4tglQ0me51rN:-Me57abd4tglQ0me51rO:b6w7qnm) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L155)):*
> ```XML
> }
> 
> export type Instrument = 'RSS' | 'Salticam' | 'HRS' | 'BVIT';
> ```

We might have to chat about the types... :-)
___
*[frontend/src/app/types.ts, line 159 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me54hdj3Ebd4SWyqIqF:-Me54hdkDTvrPaplFANY:bb71a5e) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L159)):*
> ```XML
> export type ConfigurationType = 'Science' | 'Calibration' | 'Acquisition';
> 
> export interface Spectroscopy {
> ```

This is only valid for RSS. You should consider splitting the file.
___
*[frontend/src/app/types.ts, line 171 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me54_eZ46xYbF2snqTP:-Me54_eZ46xYbF2snqTQ:bqidb1m) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L171)):*
> ```XML
>   barcode: string;
> }
> export type RoSpeed = 'Slow';
> ```

Can you check in the SDB what the other possible values are?
___
*[frontend/src/app/types.ts, line 177 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me559Tf4ycrlSQavgAR:-Me559Tf4ycrlSQavgAS:bfe4kv6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L177)):*
> ```XML
> export interface Detector {
>   iterations: number;
>   roSpeed: RoSpeed;
> ```

"ro" should be spelled out both in the property and the type name.
___
*[frontend/src/app/types.ts, line 192 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me55Psf6B6RrQjNs6dY:-Me55Psf6B6RrQjNs6dZ:b-wfzpyg) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L192)):*
> ```XML
> }
> 
> export interface Calibrations {
> ```

Maybe better Calibration or CalibrationSetup?
___
*[frontend/src/app/types.ts, line 197 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me55kCX8bH9oumVSb92:-Me55kCX8bH9oumVSb93:b-mpc8cj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L197)):*
> ```XML
> }
> 
> export interface BlockConfiguration {
> ```

Why do you call this BlockConfiguration?
___
*[frontend/src/app/types.ts, line 203 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me55qJSC81P0dB6NgdA:-Me55qJSC81P0dB6NgdB:b-warzoo) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L203)):*
> ```XML
>   overhead: number;
>   chargedTime: number;
>   guideMethod: string | null;
> ```

That would be an enum, I guess.
___
*[frontend/src/app/types.ts, line 211 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me560M64oVluTZrfeDR:-Me560M64oVluTZrfeDS:b-nb42ha) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L211)):*
> ```XML
> }
> export interface InstrumentConfiguration {
>   configurationNumber: number;
> ```

There is no configuration number. (This is just a running number, I think.)
___
*[frontend/src/app/proposal/block/rss-science-configuration/rss-science-configuration.component.html, line 5 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me57vO--03NtejkiiKc:-Me57vO--03NtejkiiKd:b3zvfxn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/block/rss-science-configuration/rss-science-configuration.component.html#L5)):*
> ```HTML
>     <div class="has-text-centered">General</div>
>   </div>
>   <div class="row has-two-columns"><div>MinSN</div><div>0</div></div>
> ```

There are hardcoded values.
___
*[frontend/src/app/proposal/block-view/block-view.component.html, line 35 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me58FenE-vrTYYldLHw:-Me58FenE-vrTYYldLHx:b93tb3l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/block-view/block-view.component.html#L35)):*
> ```HTML
>   (select)="selectBlock($event)"
> ></wm-block-selection>
> ```

Unnecessary empty lines.
___
*[frontend/src/app/proposal/instruments/instrument-view/instrument-view.component.html, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me58yrY1lF-dmYz74C4:-Me58yrY1lF-dmYz74C5:bcspiye) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/instruments/instrument-view/instrument-view.component.html#L1)):*
> ```HTML
> <p>instrument-view works!</p>
> ```

Is this component needed?
___
*[frontend/src/app/proposal/instruments/rss/arc-bible-table/arc-bible-table.component.ts, line 10 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me599ns8zbFXk5flnwQ:-Me599ns8zbFXk5flnwR:b-uwnyz8) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/instruments/rss/arc-bible-table/arc-bible-table.component.ts#L10)):*
> ```XML
> })
> export class ArcBibleTableComponent implements OnInit {
>   @Input() arcBibles: ArcBible[] | undefined | null;
> ```

arcBible --> arcBibleEntries

ArcBible ---> ArcBibleEntry
___
*[frontend/src/app/proposal/instruments/rss/rss-calibration-table/rss-calibration-table.component.ts, line 10 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me59VAoBviRG4pKpwMM:-Me59VApB7w0LKnKD_hb:be4glmi) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/instruments/rss/rss-calibration-table/rss-calibration-table.component.ts#L10)):*
> ```XML
> })
> export class RssCalibrationTableComponent implements OnInit {
>   @Input() calibrations: Calibrations[] | null | undefined;
> ```

Can these really be null or undefined.

Also, are they calibrations or calibrationSetups?
___
*[frontend/src/app/proposal/instruments/rss/slit-mask/slit-mask-table.component.ts, line 5 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me5AuHb1_cN4sdvawpA:-Me5AuHb1_cN4sdvawpB:b-g5xmo8) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/instruments/rss/slit-mask/slit-mask-table.component.ts#L5)):*
> ```XML
> 
> @Component({
>   selector: 'wm-slit-mask-table',
> ```

It's rather wm-rss-salit-mask.
___
*[frontend/src/app/proposal/instruments/rss/slit-mask/slit-mask-table.component.ts, line 10 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me5AaZo9zX27SqC7mcT:-Me5AaZo9zX27SqC7mcU:b-42tfun) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/instruments/rss/slit-mas [...]

2021-07-08 13:56 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/48)* status: 23 of 51 files reviewed, 17 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/src/styles.scss, line 144 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me52REU2QVOTxbJ-TFk:-Me5FQhu0E7NWTbAzGt5:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/styles.scss#L144)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For consistency: .has-3-columns --> .has-three-columns
</blockquote></details>

Done.
___
*[frontend/src/app/types.ts, line 171 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me54_eZ46xYbF2snqTP:-Me5LzO1EIhdgQ1a3HmO:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L171)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can you check in the SDB what the other possible values are?
</blockquote></details>

Done.
___
*[frontend/src/app/types.ts, line 192 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me55Psf6B6RrQjNs6dY:-Me5FkL05wVFHB2yvhVg:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L192)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better Calibration or CalibrationSetup?
</blockquote></details>

Done.
___
*[frontend/src/app/types.ts, line 197 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me55kCX8bH9oumVSb92:-Me5MAfo84OWuUEm3W3X:b90s7p0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L197)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you call this BlockConfiguration?
</blockquote></details>

I migh tbe mixing up names help
___
*[frontend/src/app/types.ts, line 211 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me560M64oVluTZrfeDR:-Me5GVdp8_GfJNrfdMrF:b-2zy55w) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L211)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is no configuration number. (This is just a running number, I think.)
</blockquote></details>

called runningNumber now.
___
*[frontend/src/app/proposal/block-view/block-view.component.html, line 35 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me58FenE-vrTYYldLHw:-Me5HNX26_r9Cw0m93TY:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/block-view/block-view.component.html#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary empty lines.
</blockquote></details>

removed
___
*[frontend/src/app/proposal/instruments/rss/arc-bible-table/arc-bible-table.component.ts, line 10 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me599ns8zbFXk5flnwQ:-Me5Hl86-5cqMbNdAxWO:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/instruments/rss/arc-bible-table/arc-bible-table.component.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

arcBible --> arcBibleEntries

ArcBible ---> ArcBibleEntry
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/instruments/rss/rss-calibration-table/rss-calibration-table.component.ts, line 10 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me59VAoBviRG4pKpwMM:-Me5Hv040Ly0nvetsYzx:b-e8fg2z) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/instruments/rss/rss-calibration-table/rss-calibration-table.component.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can these really be null or undefined.

Also, are they calibrations or calibrationSetups?
</blockquote></details>

Not sure I believe I will get the list of Configs. consting of Science, Aquisition and calibration.
and only Calibration setup have calibration res they do not.
___
*[frontend/src/app/proposal/block/rss-science-configuration/rss-science-configuration.component.html, line 5 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me57vO--03NtejkiiKc:-Me5H-fH6EnDhYSy-daF:bhvino4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/block/rss-science-configuration/rss-science-configuration.component.html#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There are hardcoded values.
</blockquote></details>

this should have been removed
___
*[frontend/src/app/proposal/instruments/instrument-view/instrument-view.component.html, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me58yrY1lF-dmYz74C4:-Me5HQsrCTb1VsWXWo-F:bslwpbv) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/instruments/instrument-view/instrument-view.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is this component needed?
</blockquote></details>

not any more
___
*[frontend/src/app/proposal/instruments/rss/slit-mask/slit-mask-table.component.ts, line 5 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me5AuHb1_cN4sdvawpA:-Me5K4az4O92m2d04yur:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/instruments/rss/slit-mask/slit-mask-table.component.ts#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It's rather wm-rss-salit-mask.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/instruments/use-in-table/use-in-table.component.ts, line 5 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me5C9lM2MyXdSgJzBTy:-Me5KR508ESl05sqMkGr:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/instruments/use-in-table/use-in-table.component.ts#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"used" note "use", I'd suggest.

Can we chat about the component names in general?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-08 14:08 UTC, hettlage requested changes
> Reviewed 28 of 28 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/48)* status: all files reviewed, 15 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/src/app/types.ts, line 204 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me5PheUBZnAzirPKQEk:-Me5PheUBZnAzirPKQEl:b-tsibpz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L204)):*
> ```XML
>   chargedTime: number;
>   guideMethod: string | null;
>   spectroscopy: Spectroscopy | null | undefined;
> ```

We should chat about these `null | undefined`...
___
*[frontend/src/app/types.ts, line 211 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me560M64oVluTZrfeDR:-Me5PwQWEYZ6GNUef0JT:bsvg0j9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L211)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

called runningNumber now.
</blockquote></details>

I meant it is not necessary... :)
___
*[frontend/src/app/proposal/block-view/block-view.component.spec.ts, line 46 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me5QH0h519Buu01Jtc5:-Me5QH0h519Buu01Jtc6:bkhh5ty) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9388a6b6c42e72259c281dab9b223a674812f28e/frontend/src/app/proposal/block-view/block-view.component.spec.ts#L46)):*
> ```XML
> }
> 
> function block(id: number): any {
> ```

I would rather cast the return value.
___
*[frontend/src/app/proposal/instruments/rss/arc-bible-table/arc-bible-table.component.ts, line 10 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me599ns8zbFXk5flnwQ:-Me5QWktB2snaApHiO94:b-oxb408) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/instruments/rss/arc-bible-table/arc-bible-table.component.ts#L10)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ArcBibleEntries ---> ArcBibleEntry
___
*[frontend/src/app/proposal/instruments/rss/rss-cofiguration-view/rss-configuration-view.component.html, line 7 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me5Qhqq-o2tloeahf9n:-Me5Qhqq-o2tloeahf9o:b-bf4i57) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9388a6b6c42e72259c281dab9b223a674812f28e/frontend/src/app/proposal/instruments/rss/rss-cofiguration-view/rss-configuration-view.component.html#L7)):*
> ```HTML
>   <wm-detector-table [detector]="instrumentConfiguration.configuration.detector"></wm-detector-table>
>   <wm-spectroscopy-table [spectroscopy]="instrumentConfiguration.configuration.spectroscopy"></wm-spectroscopy-table>
>   <wm-rss-salit-mask [salitMask]="instrumentConfiguration.configuration.slitMask"></wm-rss-salit-mask>
> ```

wm-rss-salit-mask ---> wm-rss-slit-mask

salitMask ---> slitMask
___
*[frontend/src/app/proposal/instruments/rss/slit-mask/slit-mask-table.component.ts, line 5 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me5AuHb1_cN4sdvawpA:-Me5QzA627v0GQ7_Ed4h:bhim23c) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/instruments/rss/slit-mask/slit-mask-table.component.ts#L5)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oops. Sorry, "salit" was a typo.


<!-- Sent from Reviewable.io -->

2021-07-19 13:07 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/48)* status: all files reviewed, 15 unresolved discussions (waiting on @hettlage)

___
*[frontend/src/app/types.ts, line 155 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me57abd4tglQ0me51rN:-Meygx0s6oGl_5xsw338:bjmgd4c) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L155)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

We might have to chat about the types... :-)
</blockquote></details>

Will fix after discussion in the new pr
___
*[frontend/src/app/types.ts, line 159 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me54hdj3Ebd4SWyqIqF:-MeydTSBD-MMNIBCJxc0:bb6un1j) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L159)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is only valid for RSS. You should consider splitting the file.
</blockquote></details>

Done
___
*[frontend/src/app/types.ts, line 177 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me559Tf4ycrlSQavgAR:-Meyh30XC55szNzonzUK:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L177)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"ro" should be spelled out both in the property and the type name.
</blockquote></details>

Done.
___
*[frontend/src/app/types.ts, line 203 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me55qJSC81P0dB6NgdA:-Meyh5FW2pXOFa2zo4kQ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L203)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That would be an enum, I guess.
</blockquote></details>

Done.
___
*[frontend/src/app/types.ts, line 204 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me5PheUBZnAzirPKQEk:-Meyh6FQEIq5A-sQepof:bss4a2b) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L204)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

We should chat about these `null | undefined`...
</blockquote></details>

Removed.
___
*[frontend/src/app/types.ts, line 211 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me560M64oVluTZrfeDR:-MeyhCN85o7eJGGAI56V:b3kre) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L211)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I meant it is not necessary... :)
</blockquote></details>

?
___
*[frontend/src/app/proposal/block-view/block-view.component.spec.ts, line 46 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me5QH0h519Buu01Jtc5:-Meyfg4mAcHA-NWleBi_:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9388a6b6c42e72259c281dab9b223a674812f28e/frontend/src/app/proposal/block-view/block-view.component.spec.ts#L46)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would rather cast the return value.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/instruments/rss/arc-bible-table/arc-bible-table.component.ts, line 10 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me599ns8zbFXk5flnwQ:-Meyg5MNASDzBZZ4f4Iz:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/instruments/rss/arc-bible-table/arc-bible-table.component.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

ArcBibleEntries ---> ArcBibleEntry
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/instruments/rss/rss-cofiguration-view/rss-configuration-view.component.html, line 7 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me5Qhqq-o2tloeahf9n:-MeygTot-n6Qqnmus-om:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9388a6b6c42e72259c281dab9b223a674812f28e/frontend/src/app/proposal/instruments/rss/rss-cofiguration-view/rss-configuration-view.component.html#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

wm-rss-salit-mask ---> wm-rss-slit-mask

salitMask ---> slitMask
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/instruments/rss/slit-mask/slit-mask-table.component.ts, line 5 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me5AuHb1_cN4sdvawpA:-MeygV9d3hFtmw7OKtGc:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/instruments/rss/slit-mask/slit-mask-table.component.ts#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oops. Sorry, "salit" was a typo.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/instruments/rss/slit-mask/slit-mask-table.component.ts, line 10 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me5AaZo9zX27SqC7mcT:-Meyg_8k0f2ug0Uxdy58:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/instruments/rss/slit-mask/slit-mask-table.component.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do you really need null and undefined? We should discuss this. (Also applies to other components.)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-19 17:42 UTC, hettlage requested changes
> Reviewed 20 of 20 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/48)* status: all files reviewed, 7 unresolved discussions (waiting on @Eb-Zeero)

___
*[frontend/src/app/types.ts, line 197 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me55kCX8bH9oumVSb92:-MezosT72pFFxmwSjZzH:bc8dz2q) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L197)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I migh tbe mixing up names help
</blockquote></details>

I guess we'll discuss this when discussing the types.
___
*[frontend/src/app/types.ts, line 211 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me560M64oVluTZrfeDR:-MezoZab12I99DoUTeQF:b-hll9m5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L211)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

?
</blockquote></details>

runningNumber is essentially an array index. So you need this in the database, but not in the TypeScript type.
___
*[frontend/src/app/types.ts, line 166 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Mezo8dF3s12v3KjGkY7:-Mezo8dF3s12v3KjGkY8:b9nyd4a) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9388a6b6c42e72259c281dab9b223a674812f28e/frontend/src/app/types.ts#L166)):*
> ```XML
>   cameraAngle: number;
> }
> export interface SalitMask {
> ```

Another RSS-only type, I think. And it should be "SlitMask".
___
*[frontend/src/app/proposal/instruments/detector-table/detector-table.component.html, line 14 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-MezpFZ-49tTrlHPk_4a:-MezpFZ-49tTrlHPk_4b:bbl3ycz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2146713a1a16525849d0cfb7cae242d842076465/frontend/src/app/proposal/instruments/detector-table/detector-table.component.html#L14)):*
> ```HTML
>   <div class="row detector-section">
>     <div>{{detector.iterations}}</div>
>     <div>{{detector.readOutSpeed}}</div>
> ```

readOutSpeed ---> readoutSpeed (lowercase 'o')  
___
*[frontend/src/app/proposal/instruments/rss/rss-types.ts, line 6 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-MezpUwTCLrfnZo0hLfK:-MezpUwTCLrfnZo0hLfL:b-b8c2ni) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2146713a1a16525849d0cfb7cae242d842076465/frontend/src/app/proposal/instruments/rss/rss-types.ts#L6)):*
> ```XML
> } from '../../../types';
> 
> export type ReadOutSpeed = 'Slow' | 'None' | 'Fast';
> ```

ReadOutSpeed ---> ReadoutSpeed
___
*[frontend/src/app/proposal/instruments/rss/rss-calibration-table/rss-calibration-table.component.ts, line 10 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me59VAoBviRG4pKpwMM:-Mezq55b7g-18ln7qgzE:bvfpjf0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/instruments/rss/rss-calibration-table/rss-calibration-table.component.ts#L10)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Not sure I believe I will get the list of Configs. consting of Science, Aquisition and calibration.
and only Calibration setup have calibration res they do not.
</blockquote></details>

I think I was wondering why the variable is called calibrations, but the type is called CalibrationSetup.
___
*[frontend/src/app/proposal/instruments/rss/rss-cofiguration-view/rss-configuration-view.component.html, line 12 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-MezqTXd09aSZilgSoHo:-MezqTXd09aSZilgSoHp:b-jrf4v1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2146713a1a16525849d0cfb7cae242d842076465/frontend/src/app/proposal/instruments/rss/rss-cofiguration-view/rss-configuration-view.component.html#L12)):*
> ```HTML
>     <wm-rss-slit-mask [slitMask]="instrumentConfiguration.configuration.slitMask"></wm-rss-slit-mask>
>   </div>
>   <div *ngIf="instrumentConfiguration.configuration.calibrations">
> ```

I think this needs discussion (along with the types).


<!-- Sent from Reviewable.io -->

2021-07-20 09:53 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/48)* status: all files reviewed, 7 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/src/app/types.ts, line 166 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Mezo8dF3s12v3KjGkY7:-Mf2Hyxz-VnZF3Q0L_fO:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9388a6b6c42e72259c281dab9b223a674812f28e/frontend/src/app/types.ts#L166)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Another RSS-only type, I think. And it should be "SlitMask".
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/instruments/detector-table/detector-table.component.html, line 14 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-MezpFZ-49tTrlHPk_4a:-Mf2IosfE3uvvUMm6kw-:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2146713a1a16525849d0cfb7cae242d842076465/frontend/src/app/proposal/instruments/detector-table/detector-table.component.html#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

readOutSpeed ---> readoutSpeed (lowercase 'o')  
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/instruments/rss/rss-types.ts, line 6 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-MezpUwTCLrfnZo0hLfK:-Mf2Iw4FBlk2aINc6F38:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2146713a1a16525849d0cfb7cae242d842076465/frontend/src/app/proposal/instruments/rss/rss-types.ts#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

ReadOutSpeed ---> ReadoutSpeed
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/instruments/rss/rss-calibration-table/rss-calibration-table.component.ts, line 10 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me59VAoBviRG4pKpwMM:-Mf2IxwR-5D-oJ6TlE-G:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/proposal/instruments/rss/rss-calibration-table/rss-calibration-table.component.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think I was wondering why the variable is called calibrations, but the type is called CalibrationSetup.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-22 09:07 UTC, hettlage requested changes
> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/48)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/src/app/proposal/instruments/rss/rss-types.ts, line 52 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-MfCPiGk9SVUsel56gI-:-MfCPiGl1S_YspVlHjZb:b-bcsqwh) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/bd319de35e3601abb739b4fe046ce968d1f7e908/frontend/src/app/proposal/instruments/rss/rss-types.ts#L52)):*
> ```XML
> 
> export interface SlitMask {
>   Type: string;
> ```

Should be "type" (or maybe "maskType", to avoid potential clashes with a type keyword?)
___
*[frontend/src/app/proposal/instruments/rss/rss-calibration-table/rss-calibration-table.component.html, line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-MfCQA703PxLwsNpWuAO:-MfCQA703PxLwsNpWuAP:b-iotrmk) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/bd319de35e3601abb739b4fe046ce968d1f7e908/frontend/src/app/proposal/instruments/rss/rss-calibration-table/rss-calibration-table.component.html#L1)):*
> ```HTML
> <div class="table" *ngIf="calibrationSetup">
> ```

There should be no ngIf -- if this isn't a calibration, you shouldn't render the component at all.


<!-- Sent from Reviewable.io -->

2021-07-22 09:43 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/48)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[frontend/src/app/types.ts, line 197 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-Me55kCX8bH9oumVSb92:-MfC__ZxCC_36a6S1ezf:b2nign6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8eb1449200f057d9105979f564aeab895e829852/frontend/src/app/types.ts#L197)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess we'll discuss this when discussing the types.
</blockquote></details>

yes
___
*[frontend/src/app/proposal/instruments/rss/rss-types.ts, line 52 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-MfCPiGk9SVUsel56gI-:-MfCVroQCwxal-l7lwtH:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/bd319de35e3601abb739b4fe046ce968d1f7e908/frontend/src/app/proposal/instruments/rss/rss-types.ts#L52)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be "type" (or maybe "maskType", to avoid potential clashes with a type keyword?)
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/instruments/rss/rss-calibration-table/rss-calibration-table.component.html, line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-MfCQA703PxLwsNpWuAO:-MfCWE8i0e9a7QLGX86D:bacgraz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/bd319de35e3601abb739b4fe046ce968d1f7e908/frontend/src/app/proposal/instruments/rss/rss-calibration-table/rss-calibration-table.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should be no ngIf -- if this isn't a calibration, you shouldn't render the component at all.
</blockquote></details>

nice catch.
forgot to remove this line
___
*[frontend/src/app/proposal/instruments/rss/rss-cofiguration-view/rss-configuration-view.component.html, line 12 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/48#-MezqTXd09aSZilgSoHo:-MfCWLqcEJyRj3yBF7vi:b-8mc9a9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2146713a1a16525849d0cfb7cae242d842076465/frontend/src/app/proposal/instruments/rss/rss-cofiguration-view/rss-configuration-view.component.html#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think this needs discussion (along with the types).
</blockquote></details>

yes we have to


<!-- Sent from Reviewable.io -->

2021-07-22 10:16 UTC, hettlage reviewed
> Reviewed 9 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/48)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)



<!-- Sent from Reviewable.io -->

2021-07-22 10:18 UTC, merged