Block summary table issues
saltastroops/web-manager-2021 pull request #89
Opened 2021-12-10 12:04 UTC by mofokeng-chaka

2021-12-13 14:39 UTC, hettlage requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.html, line 42 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MqoCh0R88ZTaKv6JGaQ:-MqoCh0R88ZTaKv6JGaR:bs293vs) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/83e00e93d62f6f5f7825ca54b39c222a4ae0c482/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L42)):*
> ```HTML
>         b.status.value === 'Completed' &&
>         b.acceptedObservations === b.requestedObservations
>           ? 'is-green-background'
> ```

I'm not sure about the green background, given that easily might be interpreted as "all good, ready to be observed". The current WM uses a light blue background for completed blocks.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 13 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-Mqo33cN0y2u9DHeOMmv:-Mqo33cN0y2u9DHeOMmw:b-2xx1d8) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/83e00e93d62f6f5f7825ca54b39c222a4ae0c482/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L13)):*
> ```XML
>   @Input() blocks!: BlockSummary[];
>   @Input() proposalCode!: string;
>   filteredBlocks: BlockSummary[] = [];
> ```

I suspect this is too complicated and you don't need any observables.

I'd suggest the following:

* Have boolean variables recording whether completed / unobservable blocks are filtered
* Set the checked status ofd the checkboxes from these variables
* Let click events update these variables and then filter the blocks accordingly
* Store the variable values in local storage (and initialise them from there).

Maybe we can have a quick chat about this?
___
*[src/app/types/common.ts, line 22 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-Mqo8HPVDMv_F9KF5LLl:-Mqo8HPVDMv_F9KF5LLm:b3wp8t9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/83e00e93d62f6f5f7825ca54b39c222a4ae0c482/src/app/types/common.ts#L22)):*
> ```XML
>   name: string;
>   modes: string[];
>   grating: string | null;
> ```

If you can have multiple modes, you could have multiple gratings as well. Also, given that gratings are relevant for some detectors only, having them as a field might be a bit awkward. So the better choice might be to include the grating information in the mode.


<!-- Sent from Reviewable.io -->

2021-12-15 12:45 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: 5 of 11 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.html, line 42 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MqoCh0R88ZTaKv6JGaQ:-Mqss_ji4kLEma6LyK6X:b-pbbn1w) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/83e00e93d62f6f5f7825ca54b39c222a4ae0c482/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L42)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not sure about the green background, given that easily might be interpreted as "all good, ready to be observed". The current WM uses a light blue background for completed blocks.
</blockquote></details>

I agree with you. I have used a light blue colour instead.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 13 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-Mqo33cN0y2u9DHeOMmv:-Mqy5bcz6akDTJ0aA5K1:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/83e00e93d62f6f5f7825ca54b39c222a4ae0c482/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I suspect this is too complicated and you don't need any observables.

I'd suggest the following:

* Have boolean variables recording whether completed / unobservable blocks are filtered
* Set the checked status ofd the checkboxes from these variables
* Let click events update these variables and then filter the blocks accordingly
* Store the variable values in local storage (and initialise them from there).

Maybe we can have a quick chat about this?
</blockquote></details>

Done.
___
*[src/app/types/common.ts, line 22 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-Mqo8HPVDMv_F9KF5LLl:-MqstOx10GUqJ3LL2BG5:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/83e00e93d62f6f5f7825ca54b39c222a4ae0c482/src/app/types/common.ts#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If you can have multiple modes, you could have multiple gratings as well. Also, given that gratings are relevant for some detectors only, having them as a field might be a bit awkward. So the better choice might be to include the grating information in the mode.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-15 14:37 UTC, hettlage requested changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 27 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MqySmWV4UlzJOpIxZLI:-MqySmWW4DRxk-8ggq08:b-w2mjs9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e474cdf7776cd3115a477621157adf5702a11a9e/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L27)):*
> ```XML
>   }
> 
>   ngAfterViewInit() {
> ```

Why don't you do this in ngOnInit?
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 34 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MqyTkRQ0eI78ryLxEyJ:-MqyTkRQ0eI78ryLxEyK:b7d233g) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e474cdf7776cd3115a477621157adf5702a11a9e/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L34)):*
> ```XML
>   }
> 
>   OnChange(event: Event) {
> ```

This might need some discussion. :-)

* Function makes should start with a lower case
* The checked value of the checkboxes should be set with the corresponding variable (such as filteredByCompleted) in the template.
* There should be three functions:
    * An event handler for events from the "filter completed" checkbox.
    * An event handler for events from the "filter unobservable" checkbox.
    * A function for performing the filtering, which is called by the other two functions.
___
*[src/app/types/common.ts, line 22 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-Mqo8HPVDMv_F9KF5LLl:-MqoUt1i5klS0Sl27eO3:b24imj2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/83e00e93d62f6f5f7825ca54b39c222a4ae0c482/src/app/types/common.ts#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If you can have multiple modes, you could have multiple gratings as well. Also, given that gratings are relevant for some detectors only, having them as a field might be a bit awkward. So the better choice might be to include the grating information in the mode.
</blockquote></details>

Alas, it's not that easy: From the backend perspective, there is no easy way of accomplishing this. Also, note that the issue also mentioned slit details.

So the solution might be rather to have a field called something like "additional_details" where all this extra stuff can be "dumped".


<!-- Sent from Reviewable.io -->

2021-12-15 14:37 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 34 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MqyTkRQ0eI78ryLxEyJ:-MqyWeiu2Wvqh4E3tD6Q:b6b7aby) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e474cdf7776cd3115a477621157adf5702a11a9e/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This might need some discussion. :-)

* Function makes should start with a lower case
* The checked value of the checkboxes should be set with the corresponding variable (such as filteredByCompleted) in the template.
* There should be three functions:
    * An event handler for events from the "filter completed" checkbox.
    * An event handler for events from the "filter unobservable" checkbox.
    * A function for performing the filtering, which is called by the other two functions.
</blockquote></details>

Oh, and the functionality should be tested...


<!-- Sent from Reviewable.io -->

2021-12-18 06:33 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: 7 of 12 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 27 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MqySmWV4UlzJOpIxZLI:-Mr83ix98uQb8P71xUR2:b-ddw8qk) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e474cdf7776cd3115a477621157adf5702a11a9e/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why don't you do this in ngOnInit?
</blockquote></details>

At first, it seemed as if the checkboxes values were not being initialized as expected. But it appears not to be the case now. ngOnInit does work as expected.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 34 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MqyTkRQ0eI78ryLxEyJ:-Mr83W4_C2uxztmhvpuz:b-a8tn1p) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e474cdf7776cd3115a477621157adf5702a11a9e/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oh, and the functionality should be tested...
</blockquote></details>

I think I am going to need help with testing.
___
*[src/app/types/common.ts, line 22 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-Mqo8HPVDMv_F9KF5LLl:-Mr83fMh2LnWMDUO_HcC:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/83e00e93d62f6f5f7825ca54b39c222a4ae0c482/src/app/types/common.ts#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Alas, it's not that easy: From the backend perspective, there is no easy way of accomplishing this. Also, note that the issue also mentioned slit details.

So the solution might be rather to have a field called something like "additional_details" where all this extra stuff can be "dumped".

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-19 09:34 UTC, hettlage requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: all files reviewed, 12 unresolved discussions (waiting on @mofokeng-chaka)

___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.html, line 118 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlKqOp9Qo8k-XbWi1n:-MtlKqOp9Qo8k-XbWi1o:b3d1rgw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L118)):*
> ```HTML
>               {{ m }}
>             </div>
>             <div *ngIf="i.gratings && i.filters">
> ```

You only display anythings if there is both a grating and a filter, but I suspect you want to display something if either of them has a truth value?
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 34 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlTdo74VxpmZXS4tvz:-MtlTdo74VxpmZXS4tw-:b-v5l12q) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L34)):*
> ```XML
>     (
>       document.getElementById('filter-unobservable') as HTMLInputElement
>     ).checked = this.filteredByUnobservable;
> ```

You set the checkbox value from local storage -- but you still have to filter accordingly... At the moment you might have, say, the "Hide completed blocks" checkbox checked with the completed blocks being displayed.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 44 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlNv315EdsVTIMeDqi:-MtlNv315EdsVTIMeDqj:bpq6xzh) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L44)):*
> ```XML
>       JSON.stringify(this.filteredByCompleted)
>     );
>     checkbox.checked = this.filteredByCompleted;
> ```

Isn't this method called in response to a checkbox event? So there should be no need for setting the checkbox checked status. Actually, I think the checked status should be dynamically set from the this.filteredByComplete value, ie. in the template you should have something like

```<input ...  [checked]="filteredByCompleted" ...>```
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 48 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlUMAO1CUF8Ph3wvNB:-MtlUMAO1CUF8Ph3wvNC:bexof28) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L48)):*
> ```XML
>   }
> 
>   filterByUnobservable(event: Event) {
> ```

See my comment for the filterByCompleted method.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 59 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlchnA4bmnD83LIw5d:-MtlchnA4bmnD83LIw5e:b-br46h1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L59)):*
> ```XML
>   }
> 
>   applyBlocksFilter() {
> ```

From what I can see you can combine and simplify `applyBlocksFilters` and `filterBlocks`, and simplify:

```
  filterBlocks() {
    let blocks = [...this.blocks]
    if (this.filteredByCompleted) {
      blocks = this.filteredBlocks.filter(
        (block) => block.status.value !== 'Completed'
      );
    }
    if (this.filteredByUnobservable) {
      blocks = this.blocks.filter(
        (block) =>
          block.acceptedObservations === block.requestedObservations ||
          block.remainingNights !== 0
      )
    }
    this.filteredBlocks = blocks;
  }
``` 
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 99 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlUypz4GhzMsxs30ik:-MtlUypz4GhzMsxs30il:b-tvv36l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L99)):*
> ```XML
>   filterBlocks(blocks: BlockSummary[]) {
>     this.filteredBlocks = blocks;
>     this.filteredBlocks$.next(blocks);
> ```

I don't think you need the observable any longer?
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts, line 99 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtldCKUCtMaBiREA11E:-MtldCKUCtMaBiREA11F:bz64uqk) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts#L99)):*
> ```XML
>   });
> 
>   it('should have all checkboxes deselected initially', async () => {
> ```

Unless they are selected in localStorage... ;-) (cf. https://blog.bradleygore.com/2014/09/18/angular-unit-testing-pt-1-local-storage/). But quite frankly, that might be easier to test in an e2e test.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts, line 115 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtleLUYDlDTrweDfmJ_:-MtleLUYDlDTrweDfmJa:bcik4aj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts#L115)):*
> ```XML
>       // wait for async checkboxes' clicks
>       component.applyBlocksFilter(); // filter the list based on the checkboxes' status
>       expect(component.filteredBlocks.length).toEqual(1);
> ```

There is a potential issue. From this test you know that one block has been filtered. But you don't know it has been the correct one..
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts, line 131 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtledJG3u-2IGf-ChSC:-MtledJG3u-2IGf-ChSD:bcik4aj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts#L131)):*
> ```XML
>       // wait for async checkboxes' clicks
>       component.applyBlocksFilter(); // filter the list based on the checkboxes' status
>       expect(component.filteredBlocks.length).toEqual(1);
> ```

There is a potential issue. From this test you know that one block has been filtered. But you don't know it has been the correct one..
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts, line 132 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlepBRE1RWqsqm_OVu:-MtlepBRE1RWqsqm_OVv:b-h8eitr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts#L132)):*
> ```XML
>       component.applyBlocksFilter(); // filter the list based on the checkboxes' status
>       expect(component.filteredBlocks.length).toEqual(1);
>       filterByUnobservable.click();
> ```

What is the use of the lines after the expect() statement?
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts, line 149 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlexS71ZMZRSOqpKr8:-MtlexS71ZMZRSOqpKr9:b-h8eitr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts#L149)):*
> ```XML
>       component.applyBlocksFilter(); // filter the list based on the checkboxes' status
>       expect(component.filteredBlocks.length).toEqual(0);
>       filter [...]

2022-01-22 07:19 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: all files reviewed, 12 unresolved discussions (waiting on @hettlage)

___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.html, line 118 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlKqOp9Qo8k-XbWi1n:-MtqNoOq0nTk_uVBQUPH:b-lwkcpp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L118)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You only display anythings if there is both a grating and a filter, but I suspect you want to display something if either of them has a truth value?
</blockquote></details>

That's correct, I have fixed this now.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 34 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlTdo74VxpmZXS4tvz:-MtqOA9LCA9178lPhujY:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You set the checkbox value from local storage -- but you still have to filter accordingly... At the moment you might have, say, the "Hide completed blocks" checkbox checked with the completed blocks being displayed.
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 44 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlNv315EdsVTIMeDqi:-MtqOlhu3oLN-2FAQllx:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't this method called in response to a checkbox event? So there should be no need for setting the checkbox checked status. Actually, I think the checked status should be dynamically set from the this.filteredByComplete value, ie. in the template you should have something like

```<input ...  [checked]="filteredByCompleted" ...>```
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 48 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlUMAO1CUF8Ph3wvNB:-MtqOp_g7kKAXWnyUYxS:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See my comment for the filterByCompleted method.
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 59 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlchnA4bmnD83LIw5d:-MtqMxyg5NYpCAHNp_X6:b-fi1brp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

From what I can see you can combine and simplify `applyBlocksFilters` and `filterBlocks`, and simplify:

```
  filterBlocks() {
    let blocks = [...this.blocks]
    if (this.filteredByCompleted) {
      blocks = this.filteredBlocks.filter(
        (block) => block.status.value !== 'Completed'
      );
    }
    if (this.filteredByUnobservable) {
      blocks = this.blocks.filter(
        (block) =>
          block.acceptedObservations === block.requestedObservations ||
          block.remainingNights !== 0
      )
    }
    this.filteredBlocks = blocks;
  }
``` 
</blockquote></details>

I agree with you about combining the two functions now that an observable is no longer required. However, I tried using this function and I realized that it was missing some functionality, for instance, when the two checkboxes are checked and then you uncheck either one, the displayed blocks table does not change (doesn't get filtered). So I decided to stick with my function, add some bits of your code to my code.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 99 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlUypz4GhzMsxs30ik:-MtqN0DCD7iHbpLtF3Zv:bwt75nm) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L99)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you need the observable any longer?
</blockquote></details>

That's true, I removed it.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts, line 99 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtldCKUCtMaBiREA11E:-Mu-O6WD2azPp2EHezDH:b8yo5qb) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts#L99)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unless they are selected in localStorage... ;-) (cf. https://blog.bradleygore.com/2014/09/18/angular-unit-testing-pt-1-local-storage/). But quite frankly, that might be easier to test in an e2e test.
</blockquote></details>

I have done these tests in an e2e test instead of here.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts, line 115 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtleLUYDlDTrweDfmJ_:-MtqOwn7BYsH1FvN4RFe:b-otilcs) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts#L115)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is a potential issue. From this test you know that one block has been filtered. But you don't know it has been the correct one..
</blockquote></details>

See comment above.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts, line 131 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtledJG3u-2IGf-ChSC:-Mu-Ov_WBcJPe_vjr4zA:b-otilcs) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts#L131)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is a potential issue. From this test you know that one block has been filtered. But you don't know it has been the correct one..
</blockquote></details>

See comment above.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts, line 132 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlepBRE1RWqsqm_OVu:-Mu-OyBnEuP281P7msu1:baaf6ls) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts#L132)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What is the use of the lines after the expect() statement?
</blockquote></details>

I was using them to return the checkboxes to the state they were before each click in each test case. But they are no longer necessary.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.spec.ts, line 149 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlexS71ZMZRSOqpKr8:-Mu-PZV4CqCs7vrBLMT3:b-apayz0) ([raw file](https://github.com/saltastr [...]

2022-01-25 14:16 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: all files reviewed, 5 unresolved discussions (waiting on @mofokeng-chaka)

___
*[cypress/integration/proposal/block-summaries.spec.ts, line 24 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuG1nqD8gYxBAqfLwiu:-MuG1nqD8gYxBAqfLwiv:b-q3kjvr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b695dc44d7a0d9e20956ae65bc77c01aeeeeb200/cypress/integration/proposal/block-summaries.spec.ts#L24)):*
> ```XML
>   });
> 
>   it('should have checkboxes deselected initially', () => {
> ```

Here is something else to test: When you click the checkboxes and re.load the page, the checkboxes are still checked, and the content is filtered.
___
*[cypress/integration/proposal/block-summaries.spec.ts, line 30 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuG20KVC8JjqhSLJi12:-MuG20KW7z8pBJTnop_t:b-v3bm8p) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b695dc44d7a0d9e20956ae65bc77c01aeeeeb200/cypress/integration/proposal/block-summaries.spec.ts#L30)):*
> ```XML
> 
>   it('should filter completed blocks when filter-completed checkbox is clicked', () => {
>     BlockSummaries.clickFilterCompleted();
> ```

You should check that initially there *are* completed proposals.
___
*[cypress/integration/proposal/block-summaries.spec.ts, line 37 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuG29tCBcRq6GM6BSgo:-MuG29tD-kEtqgF1UFz_:b-ifpcyr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b695dc44d7a0d9e20956ae65bc77c01aeeeeb200/cypress/integration/proposal/block-summaries.spec.ts#L37)):*
> ```XML
> 
>   it('should filter unobservable blocks when filter-unobservable checkbox is clicked', () => {
>     BlockSummaries.clickFilterUnobservable();
> ```

ou should check that initially there *are* unobservable proposals.
___
*[cypress/support/components/block-summaries.ts, line 13 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuG1Zbh-BRI6ufsZc5o:-MuG1Zbh-BRI6ufsZc5p:bf4cas1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b695dc44d7a0d9e20956ae65bc77c01aeeeeb200/cypress/support/components/block-summaries.ts#L13)):*
> ```XML
>   }
> 
>   static filterCompletedNotChecked() {
> ```

You might consider combining the Checked / NotChecked functions into a single function taking a boolean argument.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 59 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlchnA4bmnD83LIw5d:-MuGM57L6IHdazKZDtw_:b-6tgkfj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L59)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I agree with you about combining the two functions now that an observable is no longer required. However, I tried using this function and I realized that it was missing some functionality, for instance, when the two checkboxes are checked and then you uncheck either one, the displayed blocks table does not change (doesn't get filtered). So I decided to stick with my function, add some bits of your code to my code.
</blockquote></details>

I stick to my guns: This can be simplified considerably. There were indeed issues with my suggested code, but here is an updated version (which should work):

```
  filterByCompleted(event: Event) {
    this.filteredByCompleted = (event.target as HTMLInputElement).checked
    localStorage.setItem(
      'filterByCompleted',
      JSON.stringify(this.filteredByCompleted)
    );
    this.filterBlocks();
  }

  filterByUnobservable(event: Event) {
    this.filteredByUnobservable = (event.target as HTMLInputElement).checked;
    localStorage.setItem(
      'filterByUnobservable',
      JSON.stringify(this.filteredByUnobservable)
    );
    this.filterBlocks();
  }

  filterBlocks() {
    let blocks = [...this.blocks]
    if (this.filteredByCompleted) {
      blocks = blocks.filter(
        (block) => block.status.value !== 'Completed'
      );
    }
    if (this.filteredByUnobservable) {
      blocks = blocks.filter(
        (block) =>
          block.acceptedObservations === block.requestedObservations ||
          block.remainingNights !== 0
      )
    }
    this.filteredBlocks = blocks;
  }
```


<!-- Sent from Reviewable.io -->

2022-01-25 19:14 UTC, hettlage requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[cypress/integration/proposal/block-summaries.spec.ts, line 64 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuHcmgT5F2AEo-MyfsI:-MuHcmgT5F2AEo-MyfsJ:b4dhqip) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddad5027e9030bacc022162a66f4032f4397d4a0/cypress/integration/proposal/block-summaries.spec.ts#L64)):*
> ```XML
>     BlockSummaries.filterCompletedChecked(true);
>     BlockSummaries.filterUnobservableChecked(true);
>     BlockSummaries.hasFilteredCompleted();
> ```

I'd suggest to merge hasCompletedBlocks and hasFilteredCompleted into a single function as well (or at least have more consistent names -- hasCompletedBlocks / hasNoCompletedBlocks). Similarly for uncompleted blocks.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 59 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlchnA4bmnD83LIw5d:-MuHdTgy27mKJ3eik3k-:b-yvkqia) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L59)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Now it is working as expected. I am not sure what i was doing wrong previously.
</blockquote></details>

Who says *you* did something wrong? There were bugs in my code, and relying on the value of the checkbox status variables (such as `this.filteredByUnobservable`) rather than the checkbox status itself probably didn't help either...


<!-- Sent from Reviewable.io -->

2022-01-26 06:51 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[cypress/integration/proposal/block-summaries.spec.ts, line 64 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuHcmgT5F2AEo-MyfsI:-MuK7uv-6va_KfulpYbs:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddad5027e9030bacc022162a66f4032f4397d4a0/cypress/integration/proposal/block-summaries.spec.ts#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to merge hasCompletedBlocks and hasFilteredCompleted into a single function as well (or at least have more consistent names -- hasCompletedBlocks / hasNoCompletedBlocks). Similarly for uncompleted blocks.
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 59 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MtlchnA4bmnD83LIw5d:-MuK879HA0zYoc5kIPM5:bn6sleb) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/caaba68e066da2008566d1667b7e9134bddc6458/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Who says *you* did something wrong? There were bugs in my code, and relying on the value of the checkbox status variables (such as `this.filteredByUnobservable`) rather than the checkbox status itself probably didn't help either...
</blockquote></details>

I understand, since you were sticking to your guns I had to give in by suggesting I am the wrong one so that you don't shoot me.


<!-- Sent from Reviewable.io -->

2022-01-26 07:45 UTC, hettlage requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[cypress/support/components/block-summaries.ts, line 33 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuKJQ5l0h4njDVfNbdY:-MuKJQ5m4n6qmAyUVllU:b-x1ifet) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1ab4ce8156c825fb053388c6d54d2dd65bbfba99/cypress/support/components/block-summaries.ts#L33)):*
> ```XML
>       cy.get('.table')
>         .get('.block-row')
>         .should('have.class', 'completed-proposal');
> ```

Sorry, I didn't pick this up beforehand. Using classes for selecting elements is not considered best practice in Cypress; see https://docs.cypress.io/guides/references/best-practices#Selecting-Elements. `data-test` attributes are preferred (I wouldn't use data-cy -- why "tie" the code to Cypress if there is no need? :) )


<!-- Sent from Reviewable.io -->

2022-01-26 08:17 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: 14 of 16 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[cypress/support/components/block-summaries.ts, line 33 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuKJQ5l0h4njDVfNbdY:-MuKSFnx-wUYP7xaHbJv:b-1i8ren) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1ab4ce8156c825fb053388c6d54d2dd65bbfba99/cypress/support/components/block-summaries.ts#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry, I didn't pick this up beforehand. Using classes for selecting elements is not considered best practice in Cypress; see https://docs.cypress.io/guides/references/best-practices#Selecting-Elements. `data-test` attributes are preferred (I wouldn't use data-cy -- why "tie" the code to Cypress if there is no need? :) )
</blockquote></details>

Noted, thanks for pointing this out.


<!-- Sent from Reviewable.io -->

2022-01-26 08:29 UTC, hettlage requested changes
> Reviewed 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[cypress/support/components/block-summaries.ts, line 33 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuKJQ5l0h4njDVfNbdY:-MuKTsI-E1U8NwOgo5Xf:b-134eoc) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1ab4ce8156c825fb053388c6d54d2dd65bbfba99/cypress/support/components/block-summaries.ts#L33)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Noted, thanks for pointing this out.
</blockquote></details>

Thanks -- but you are still replying on classes for identifying elements (namely "completed-proposal" and "is-red-background" [note that these names are somewhat inconsistent...]. But you could use data-test attributes instead of these (and then forget about the block-row part), like:

```
cy.get('[data-test="completed-block"]')
```
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.html, line 55 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuKV0JB6Wpofd6UR4tZ:-MuKV0JB6Wpofd6UR4t_:b-x12zt5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/02454ab84c8cb9ab981efae186372caf594f1002/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L55)):*
> ```HTML
>           : ''
>       "
>       data-test="block-summary"
> ```

See my comment on block-summaries.component.ts/


<!-- Sent from Reviewable.io -->

2022-01-26 08:58 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: 14 of 16 files reviewed, 2 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[cypress/support/components/block-summaries.ts, line 33 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuKJQ5l0h4njDVfNbdY:-MuKadVm2SrLSTFRHHEP:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1ab4ce8156c825fb053388c6d54d2dd65bbfba99/cypress/support/components/block-summaries.ts#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Thanks -- but you are still replying on classes for identifying elements (namely "completed-proposal" and "is-red-background" [note that these names are somewhat inconsistent...]. But you could use data-test attributes instead of these (and then forget about the block-row part), like:

```
cy.get('[data-test="completed-block"]')
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-26 11:55 UTC, hettlage requested changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.html, line 59 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuLDFX98wYp3Uebs5vd:-MuLDFX98wYp3Uebs5ve:b7zonp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a67147073d53342d707778194b288084b6aaa37a/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L59)):*
> ```HTML
>         b.acceptedObservations === b.requestedObservations
>           ? 'completed-block'
>           : b.status.value !== 'Completed' &&
> ```

Isn't `b.status.value !== 'Completed'` always true, given the earlier condition `b.status.value !== 'Completed'`?

Also these nested ternary operators here and above make me wonder whether the code wouldn't be clearer if you move the logic into methods. Something like

```
if (this.isCompleted(block)) {
    return ...
} else if (this.isUnobservable(block)) {
    return ...
}
```

might be more understandable.


<!-- Sent from Reviewable.io -->

2022-01-26 12:58 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.html, line 55 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuKV0JB6Wpofd6UR4tZ:-MuLSls6Bzc6OtqXMCpJ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/02454ab84c8cb9ab981efae186372caf594f1002/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L55)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See my comment on block-summaries.component.ts/
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.html, line 59 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuLDFX98wYp3Uebs5vd:-MuLSlDi7YiBrvtjjCbU:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a67147073d53342d707778194b288084b6aaa37a/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't `b.status.value !== 'Completed'` always true, given the earlier condition `b.status.value !== 'Completed'`?

Also these nested ternary operators here and above make me wonder whether the code wouldn't be clearer if you move the logic into methods. Something like

```
if (this.isCompleted(block)) {
    return ...
} else if (this.isUnobservable(block)) {
    return ...
}
```

might be more understandable.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-26 14:21 UTC, hettlage requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: 14 of 16 files reviewed, 5 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 83 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuLkJC493Swscb8GR6f:-MuLkJC493Swscb8GR6g:bpbchp7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/85e0fec22eed06428c5a0438c05835a636b42bb7/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L83)):*
> ```XML
>   }
>   
>   setElementProperty(block:BlockSummary, property: string) {
> ```

I think this should be split into two methods.

(Also setElementProperty is an unfortunate name, because you aren't setting anything really.)
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 86 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuLkR2A-Cxng3HMYVTD:-MuLkR2A-Cxng3HMYVTE:b-c2k25j) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/85e0fec22eed06428c5a0438c05835a636b42bb7/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L86)):*
> ```XML
>     if (property.toLowerCase() === 'class') {
>       if (this.isCompleted(block)) {
>         return 'completed-proposal';
> ```

Why id this 'completed-proposal'?


<!-- Sent from Reviewable.io -->

2022-01-26 14:21 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: 14 of 16 files reviewed, 5 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 86 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuLkR2A-Cxng3HMYVTD:-MuLknfm0pQY0uboHiBC:b-gr72lw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/85e0fec22eed06428c5a0438c05835a636b42bb7/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L86)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why id this 'completed-proposal'?
</blockquote></details>

Why id > Why is


<!-- Sent from Reviewable.io -->

2022-01-26 16:18 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: 13 of 16 files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 83 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuLkJC493Swscb8GR6f:-MuMALLUCH0tbcHIO9K1:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/85e0fec22eed06428c5a0438c05835a636b42bb7/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L83)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think this should be split into two methods.

(Also setElementProperty is an unfortunate name, because you aren't setting anything really.)
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 86 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuLkR2A-Cxng3HMYVTD:-MuMAPI273BM5if338Pw:bgyshxe) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/85e0fec22eed06428c5a0438c05835a636b42bb7/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L86)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why id > Why is
</blockquote></details>

It should be completed block, i have changed it now


<!-- Sent from Reviewable.io -->

2022-01-27 07:32 UTC, hettlage requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: 13 of 16 files reviewed, 4 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 83 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuLkJC493Swscb8GR6f:-MuPQtvXBfWPYbfv26ws:b-8ts3gu) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/85e0fec22eed06428c5a0438c05835a636b42bb7/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L83)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, but the method isn't *adding* anything either... :-( How about calling it something like `blockClass` or `blockRowClass`? (The same applies to the `addDataTestAttribute` method as well.)

Also, there are linting issues...


<!-- Sent from Reviewable.io -->

2022-01-27 07:57 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: 12 of 16 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 83 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/89#-MuLkJC493Swscb8GR6f:-MuPXWFl2kTFt1HGev9W:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/85e0fec22eed06428c5a0438c05835a636b42bb7/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L83)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry, but the method isn't *adding* anything either... :-( How about calling it something like `blockClass` or `blockRowClass`? (The same applies to the `addDataTestAttribute` method as well.)

Also, there are linting issues...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-27 08:46 UTC, hettlage approved these changes
> Reviewed 1 of 2 files at r11, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/89)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2022-01-27 08:47 UTC, merged