Links to blocks in block summary and block visits table
saltastroops/web-manager-2021 pull request #92
Opened 2022-01-24 19:44 UTC by mofokeng-chaka

2022-01-25 15:14 UTC, hettlage requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/92)* status: all files reviewed, 8 unresolved discussions (waiting on @mofokeng-chaka)

___
*[src/app/proposal/proposal.component.html, line 53 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuGgduMB38TnS03Vtkx:-MuGgduMB38TnS03Vtky:b-a61lol) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f15265207bd7fdd42bee17078d25c776cdbf8cc/src/app/proposal/proposal.component.html#L53)):*
> ```HTML
>       [blocks]="p.blocks"
>       [proposalCode]="p.proposalCode"
>       (selectEmitter)="onClick($event)"
> ```

selectEmitter might be a bit generic, and something like selectBlock might be better.
___
*[src/app/proposal/proposal.component.ts, line 29 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuGi3RyEOBAXbwl9phN:-MuGi3RyEOBAXbwl9phO:b-dwiyrb) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f15265207bd7fdd42bee17078d25c776cdbf8cc/src/app/proposal/proposal.component.ts#L29)):*
> ```XML
> 
>   onClick(block: string) {
>     this.blockName = block;
> ```

The following code should be included here, I think:

```
    const elementList = document.querySelectorAll('.block-content');
    const element = elementList[0] as HTMLElement;
    element.scrollIntoView({ behavior: 'smooth' });
```
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.scss, line 48 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuGn9vd2P_cJjlbGT4S:-MuGn9vd2P_cJjlbGT4T:b-6mn1kl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f15265207bd7fdd42bee17078d25c776cdbf8cc/src/app/proposal/blocks/block-summaries/block-summaries.component.scss#L48)):*
> ```SCSS
> }
> 
> .link {
> ```

I'd suggest that rather than using CSS styles to "turn the button into a link", you actually use a link:

```
<a href="javascript:return false"  (click)=...>
```
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 16 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuGe7sWE2yB8yKIiAzM:-MuGe7sX0wvEUX7SBmLU:b-9v5ufx) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f15265207bd7fdd42bee17078d25c776cdbf8cc/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L16)):*
> ```XML
>   onClick(blockName: string) {
>     this.selectEmitter.emit(blockName);
>     const elementList = document.querySelectorAll('.block-content');
> ```

Couldn't you rather use an id and querySelector?

Also, apart from the first statement this code should rather be included in the proposal component (in the onClick method) -- the block summary view shouldn't have to know about the block content.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 18 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuGeFEb7PusNCylV_IP:-MuGeFEb7PusNCylV_IQ:be4mb84) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f15265207bd7fdd42bee17078d25c776cdbf8cc/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L18)):*
> ```XML
>     const elementList = document.querySelectorAll('.block-content');
>     const element = elementList[0] as HTMLElement;
>     element.scrollIntoView({ behavior: 'smooth' });
> ```

It might be better to scroll so that the navigation elements for blocks are visible as well.
___
*[src/app/proposal/blocks/block-view/block-view.component.ts, line 109 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuGiXw12ne_zJjrYVvL:-MuGiXw12ne_zJjrYVvM:bxrudk0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f15265207bd7fdd42bee17078d25c776cdbf8cc/src/app/proposal/blocks/block-view/block-view.component.ts#L109)):*
> ```XML
> 
>   ngOnChanges(changes: SimpleChanges) {
>     for (const propName in changes) {
> ```

If you change any property other than the block name, you will still execute this code. I think yiu should explicitly limit it to the blockName property.
___
*[src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.scss, line 42 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuGm_AxAzpUT4b3LFoy:-MuGiwrR-ME2vLjxbOOs:b1uq8g7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f15265207bd7fdd42bee17078d25c776cdbf8cc/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.scss#L42)):*
> ```SCSS
> }
> 
> .link {
> ```

I'd suggest that rather than using CSS styles to "turn the button into a link", you actually use a link instead of a button:

```
<a href="javascript:return false"  (click)=...>
```
___
*[src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts, line 48 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuGiOCt4CahC2ZOy5ML:-MuGiOCt4CahC2ZOy5MM:b-9v5ufx) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f15265207bd7fdd42bee17078d25c776cdbf8cc/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L48)):*
> ```XML
>   onClick(blockName: string) {
>     this.selectEmitter.emit(blockName);
>     const elementList = document.querySelectorAll('.block-content');
> ```

Couldn't you rather use an id and querySelector?

Also, apart from the first statement this code should rather be included in the proposal component (in the onClick method) -- the block summary view shouldn't have to know about the block content.


<!-- Sent from Reviewable.io -->

2022-01-28 06:06 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/92)* status: 0 of 15 files reviewed, 8 unresolved discussions (waiting on @hettlage)

___
*[src/app/proposal/proposal.component.html, line 53 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuGgduMB38TnS03Vtkx:-MuPTSSV6inrGMcAPdEC:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f15265207bd7fdd42bee17078d25c776cdbf8cc/src/app/proposal/proposal.component.html#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

selectEmitter might be a bit generic, and something like selectBlock might be better.
</blockquote></details>

Done.
___
*[src/app/proposal/proposal.component.ts, line 29 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuGi3RyEOBAXbwl9phN:-MuPfahu7rOh0LQ2NuZO:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f15265207bd7fdd42bee17078d25c776cdbf8cc/src/app/proposal/proposal.component.ts#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The following code should be included here, I think:

```
    const elementList = document.querySelectorAll('.block-content');
    const element = elementList[0] as HTMLElement;
    element.scrollIntoView({ behavior: 'smooth' });
```
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.scss, line 48 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuGn9vd2P_cJjlbGT4S:-MuPfc_z2aLaiMA6D37g:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f15265207bd7fdd42bee17078d25c776cdbf8cc/src/app/proposal/blocks/block-summaries/block-summaries.component.scss#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest that rather than using CSS styles to "turn the button into a link", you actually use a link:

```
<a href="javascript:return false"  (click)=...>
```
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 16 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuGe7sWE2yB8yKIiAzM:-MuPhf1r4hATl6GlCEex:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f15265207bd7fdd42bee17078d25c776cdbf8cc/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Couldn't you rather use an id and querySelector?

Also, apart from the first statement this code should rather be included in the proposal component (in the onClick method) -- the block summary view shouldn't have to know about the block content.
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 18 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuGeFEb7PusNCylV_IP:-MuPjAl24MJ1ulWAGrmg:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f15265207bd7fdd42bee17078d25c776cdbf8cc/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be better to scroll so that the navigation elements for blocks are visible as well.
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-view/block-view.component.ts, line 109 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuGiXw12ne_zJjrYVvL:-MuPjrZM45zhaQhLxgEG:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f15265207bd7fdd42bee17078d25c776cdbf8cc/src/app/proposal/blocks/block-view/block-view.component.ts#L109)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If you change any property other than the block name, you will still execute this code. I think yiu should explicitly limit it to the blockName property.
</blockquote></details>

Done.
___
*[src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.scss, line 42 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuGm_AxAzpUT4b3LFoy:-MuPju64BB4ECX5klqIE:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f15265207bd7fdd42bee17078d25c776cdbf8cc/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.scss#L42)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest that rather than using CSS styles to "turn the button into a link", you actually use a link instead of a button:

```
<a href="javascript:return false"  (click)=...>
```
</blockquote></details>

Done.
___
*[src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts, line 48 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuGiOCt4CahC2ZOy5ML:-MuPjw-b7Mp_6f-W1NjS:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f15265207bd7fdd42bee17078d25c776cdbf8cc/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Couldn't you rather use an id and querySelector?

Also, apart from the first statement this code should rather be included in the proposal component (in the onClick method) -- the block summary view shouldn't have to know about the block content.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-28 16:46 UTC, hettlage requested changes
> Reviewed 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/92)* status: all files reviewed, 11 unresolved discussions (waiting on @mofokeng-chaka)

___
*[cypress/integration/proposal/block-summaries.spec.ts, line 68 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWYYi_2DNByD95BzWn:-MuWYYia1oqyy_25vOMD:b90grmq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/integration/proposal/block-summaries.spec.ts#L68)):*
> ```XML
>   });
> 
>   it('should scroll when block name link is clicked', () => {
> ```

Shouldn't there be such a test for the table of executed observations as well?
___
*[cypress/integration/proposal/block-summaries.spec.ts, line 73 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWVq5d2K_R8jPBVr29:-MuWVq5d2K_R8jPBVr2A:b-8pb89e) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/integration/proposal/block-summaries.spec.ts#L73)):*
> ```XML
>     BlockSummaries.inViewport(true);
>   });
> });
> ```

It would be good to have a test that the correct block is loaded when you click on a block name link.
___
*[cypress/support/index.ts, line 8 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWYlvy73m9Jk-AU0Lz:-MuWYlvy73m9Jk-AU0M-:b-wnyv98) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/support/index.ts#L8)):*
> ```XML
> });
> 
> Cypress.on('uncaught:exception', (err, runnable) => {
> ```

Can we discuss this?
___
*[cypress/support/utils.ts, line 123 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWLlzo7p7TYuZajtfk:-MuWLlzo7p7TYuZajtfl:b8z26lu) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/support/utils.ts#L123)):*
> ```XML
>       const rect = $el[0].getBoundingClientRect();
> 
>       expect(rect.left).to.be.greaterThan(0);
> ```

If I understand the documentation correctly, `getBoundingClientRect()` returns coordinates relative to the viewport, but you are comparing relative to the document. So I don't think the test is conclusive, and it might be good luck that it passes.
___
*[cypress/support/utils.ts, line 123 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWSrG5CpLADAet3nXo:-MuWSrG5CpLADAet3nXp:b-wktnn6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/support/utils.ts#L123)):*
> ```XML
>       const rect = $el[0].getBoundingClientRect();
> 
>       expect(rect.left).to.be.greaterThan(0);
> ```

If you include an assertion for `rect.left`, you should also test that it isn't to the right of the viewport.
___
*[cypress/support/utils.ts, line 143 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWTeVuDdiZsORPojAv:-MuWTeVuDdiZsORPojAw:bml83wm) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/support/utils.ts#L143)):*
> ```XML
>       const rect = $el[0].getBoundingClientRect();
> 
>       expect(rect.left).to.be.greaterThan(0);
> ```

I'm not convinced the assertion for `rect.left` is necessary.
___
*[cypress/support/utils.ts, line 144 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWSllU-iZlyDNwjjLx:-MuWSllVDasgKgMTK1KT:b8z26lu) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/support/utils.ts#L144)):*
> ```XML
> 
>       expect(rect.left).to.be.greaterThan(0);
>       expect(rect.top).to.be.greaterThan(Math.abs(documentRect.top));
> ```

If I understand the documentation correctly, `getBoundingClientRect()` returns coordinates relative to the viewport, but you are comparing relative to the document. So I don't think the test is conclusive, and it might be good luck that it passes.
___
*[cypress/support/components/block-summaries.ts, line 53 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWTxII7ViTgX3tHVS0:-MuWTxII7ViTgX3tHVS1:bivx90w) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/support/components/block-summaries.ts#L53)):*
> ```XML
>   }
> 
>   static inViewport(visible: boolean) {
> ```

The names `inViewport` / `notInViewport` might to be too generic -- it doesn't tell you *what* is (not) in the viewport (and that it isn't the block summaries...).
___
*[cypress/support/components/block-summaries.ts, line 55 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWY7pQ0uJ83Zl6gb0G:-MuWY7pQ0uJ83Zl6gb0H:bd8c6bg) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/support/components/block-summaries.ts#L55)):*
> ```XML
>   static inViewport(visible: boolean) {
>     if (visible) {
>       isInViewport('#block-selection');
> ```

You are effectively using ids for selecting elements, which isn't best practice; data-test attributes might be better.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.html, line 51 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWV29b7TnedW-Q2RUy:-MuWV29b7TnedW-Q2RUz:bf8p9xs) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L51)):*
> ```HTML
>       <div>
>         <a
>           id="block-link"
> ```

An id must be unique within a document, and this is not the case here if there is more than one block.
___
*[src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html, line 35 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWZRQXB3Nk4YDBNFBS:-MuWZRQXB3Nk4YDBNFBT:b-h6jc4n) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L35)):*
> ```HTML
>       <div>
>         <div>
>           <a class="link" (click)="onClick(e.blockName)">
> ```

I think when I tried this I had to include `href="javascript:return false"` to avoid a page reload.


<!-- Sent from Reviewable.io -->

2022-01-31 13:43 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/92)* status: all files reviewed, 11 unresolved discussions (waiting on @hettlage)

___
*[cypress/integration/proposal/block-summaries.spec.ts, line 68 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWYYi_2DNByD95BzWn:-MuiROGt7VYqmak3FaVk:bxfo4au) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/integration/proposal/block-summaries.spec.ts#L68)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't there be such a test for the table of executed observations as well?
</blockquote></details>

There should be one I was planning to write that test after you have reviewed this code.
___
*[cypress/integration/proposal/block-summaries.spec.ts, line 73 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWVq5d2K_R8jPBVr29:-MukMBjr3OsSnZ8BMrdo:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/integration/proposal/block-summaries.spec.ts#L73)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It would be good to have a test that the correct block is loaded when you click on a block name link.
</blockquote></details>

Done.
___
*[cypress/support/index.ts, line 8 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWYlvy73m9Jk-AU0Lz:-Mujxgf64evI54Crunfk:b-vc14y4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/support/index.ts#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we discuss this?
</blockquote></details>

Done, I have removed this code and modified the link to get rid of the uncaught exception.



_Code snippet:_
```XML
href="javascript:return false" ---> href="javascript:void(0)"
```
___
*[cypress/support/utils.ts, line 123 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWLlzo7p7TYuZajtfk:-MujylHiDIeDUZB5q7JV:b-ehh2fj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/support/utils.ts#L123)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If I understand the documentation correctly, `getBoundingClientRect()` returns coordinates relative to the viewport, but you are comparing relative to the document. So I don't think the test is conclusive, and it might be good luck that it passes.
</blockquote></details>

I see what you mean, I have added changes to work with the viewport's coordinates instead.
___
*[cypress/support/utils.ts, line 123 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWSrG5CpLADAet3nXo:-MukAnrt44uUtEHd9MRU:b-a6o0io) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/support/utils.ts#L123)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If you include an assertion for `rect.left`, you should also test that it isn't to the right of the viewport.
</blockquote></details>

See my comment below.
___
*[cypress/support/utils.ts, line 143 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWTeVuDdiZsORPojAv:-MukCiNU0w_WgLwpRyMC:b-huha2r) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/support/utils.ts#L143)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not convinced the assertion for `rect.left` is necessary.
</blockquote></details>

I agree and this overrides your comment above.
___
*[cypress/support/utils.ts, line 144 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWSllU-iZlyDNwjjLx:-MukDMj815b4bqrHGUQW:beot4qd) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/support/utils.ts#L144)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If I understand the documentation correctly, `getBoundingClientRect()` returns coordinates relative to the viewport, but you are comparing relative to the document. So I don't think the test is conclusive, and it might be good luck that it passes.
</blockquote></details>

See my comment above on this.
___
*[cypress/support/components/block-summaries.ts, line 53 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWTxII7ViTgX3tHVS0:-MukHBYUCWY9bDWfrPDF:bw23rby) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/support/components/block-summaries.ts#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The names `inViewport` / `notInViewport` might to be too generic -- it doesn't tell you *what* is (not) in the viewport (and that it isn't the block summaries...).
</blockquote></details>

I agree i have changed `inViewport` ---> `blockContentLoaded`.
___
*[cypress/support/components/block-summaries.ts, line 55 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWY7pQ0uJ83Zl6gb0G:-MuiWGwA8NNrYVZGCAyg:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/cypress/support/components/block-summaries.ts#L55)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are effectively using ids for selecting elements, which isn't best practice; data-test attributes might be better.
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.html, line 51 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWV29b7TnedW-Q2RUy:-MukDTWS8C56p17v0O2i:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

An id must be unique within a document, and this is not the case here if there is more than one block.
</blockquote></details>

Done.
___
*[src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html, line 35 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWZRQXB3Nk4YDBNFBS:-MuiShG99hCNRgysuecH:bqj1yjx) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think when I tried this I had to include `href="javascript:return false"` to avoid a page reload.
</blockquote></details>

Done. I have added `href="javascript:void(0)"` to avoid getting uncaught exception from cypress.


<!-- Sent from Reviewable.io -->

2022-01-31 15:32 UTC, hettlage requested changes
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/92)* status: all files reviewed, 7 unresolved discussions (waiting on @mofokeng-chaka)

___
*[cypress/integration/proposal/block-summaries.spec.ts, line 68 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MukdN8f4pKu7l_dYx-I:-MukdN8g0q8KESvEpOQ5:bwy9ymx) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1b51341b21fb9d3cea572bd211bebb35c97b93c8/cypress/integration/proposal/block-summaries.spec.ts#L68)):*
> ```XML
>   });
> 
>   it('should scroll when block name link is clicked', () => {
> ```

The test name is a bit misleading; you test more than scrolling.

Also, the test fails for me (although I couldn't figure out why it isn't loading the correct block -- but see the comment on sorting below).
___
*[cypress/support/utils.ts, line 139 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MukX71c6DwgL1JN3izk:-MukX71c6DwgL1JN3izl:b86oh6c) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1b51341b21fb9d3cea572bd211bebb35c97b93c8/cypress/support/utils.ts#L139)):*
> ```XML
>       const rect = $el[0].getBoundingClientRect();
>       
>       expect(rect.top - window.scrollY).to.be.greaterThan(window.visualViewport.pageTop);
> ```

I'm not convinced I'm convinced by the logic. Maybe it is easier to have a quick chat?
___
*[cypress/support/components/block-summaries.ts, line 73 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MukXb5O-l5SgTARqEq6:-MukXb5O-l5SgTARqEq7:b-foc0uv) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1b51341b21fb9d3cea572bd211bebb35c97b93c8/cypress/support/components/block-summaries.ts#L73)):*
> ```XML
>       .then((expected_block_name) => {
>         cy.get(LOADED_BLOCK_CONTENT)
>           .invoke('text')
> ```

Are you sure you need the (second) `invoke('text')`? Juxt using `contains` should work.
___
*[src/app/proposal/blocks/block/block.component.html, line 1 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-Muk__OuBrm90ZljnluW:-Muk__OuBrm90ZljnluX:b-no19wc) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1b51341b21fb9d3cea572bd211bebb35c97b93c8/src/app/proposal/blocks/block/block.component.html#L1)):*
> ```HTML
> <h2 data-test="loaded-block-content" class="title is-2">Block {{ block.name }}</h2>
> ```

That is nit-picking, but you'd expect a name like loaded-block-content on a container rather than a headline...
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 20 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MukhXrZEJy-HAeELoij:-MukhXrZEJy-HAeELoik:b7rivjw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1b51341b21fb9d3cea572bd211bebb35c97b93c8/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L20)):*
> ```XML
>   ngOnInit(): void {
>     this.filteredBlocks = this.blocks.sort(
>       byPropertiesOf<BlockSummary>(['name'])
> ```

This information gets lost the first time you filter, I think.

And it seems this sorting might cause the failing test.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 31 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MukbUAR8ofq_JlbX4pG:-MukbUAR8ofq_JlbX4pH:bc64ecs) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1b51341b21fb9d3cea572bd211bebb35c97b93c8/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L31)):*
> ```XML
>   onClick(blockName: string): void {
>     this.selectBlock.emit(blockName);
>     (document.getElementById('filter-completed') as HTMLInputElement).checked =
> ```

Why are you dealing with filters in this method?
___
*[src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html, line 35 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWZRQXB3Nk4YDBNFBS:-Mukkwf02yuFzHQn5A9X:b2zambe) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L35)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done. I have added `href="javascript:void(0)"` to avoid getting uncaught exception from cypress.
</blockquote></details>

It seems you haven't updated this link here at all? :) 


<!-- Sent from Reviewable.io -->

2022-01-31 17:38 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/92)* status: 6 of 16 files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[cypress/integration/proposal/block-summaries.spec.ts, line 68 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MukdN8f4pKu7l_dYx-I:-MukxoDA9-mDqMZaqL9a:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1b51341b21fb9d3cea572bd211bebb35c97b93c8/cypress/integration/proposal/block-summaries.spec.ts#L68)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The test name is a bit misleading; you test more than scrolling.

Also, the test fails for me (although I couldn't figure out why it isn't loading the correct block -- but see the comment on sorting below).
</blockquote></details>

Done.
___
*[cypress/support/utils.ts, line 139 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MukX71c6DwgL1JN3izk:-MulAKjgBDqufVt5MoIX:b-j9upom) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1b51341b21fb9d3cea572bd211bebb35c97b93c8/cypress/support/utils.ts#L139)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not convinced I'm convinced by the logic. Maybe it is easier to have a quick chat?
</blockquote></details>

It's hard to argue my point here, it's not that straightforward how to check if an element is in the viewport. I have made some changes to this code, and the logic makes sense, but I am happy to discuss this with you tomorrow morning.
___
*[cypress/support/components/block-summaries.ts, line 73 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MukXb5O-l5SgTARqEq6:-MukvCO4C_jyJu10u2GW:b-x9fwn1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1b51341b21fb9d3cea572bd211bebb35c97b93c8/cypress/support/components/block-summaries.ts#L73)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Are you sure you need the (second) `invoke('text')`? Juxt using `contains` should work.
</blockquote></details>

I think it was needed because if I didn't include it `cy.get` yields `<h2.title.is-2>` rather than the text. Anyway, I think because I have moved the `data-test="loaded-block-content"` as suggested by your following comment.
___
*[src/app/proposal/blocks/block/block.component.html, line 1 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-Muk__OuBrm90ZljnluW:-MulAGxD-90K4iryAUQV:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1b51341b21fb9d3cea572bd211bebb35c97b93c8/src/app/proposal/blocks/block/block.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That is nit-picking, but you'd expect a name like loaded-block-content on a container rather than a headline...
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 20 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MukhXrZEJy-HAeELoij:-MukzFIJ0l718uZagwKo:b1rr9kl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1b51341b21fb9d3cea572bd211bebb35c97b93c8/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This information gets lost the first time you filter, I think.

And it seems this sorting might cause the failing test.
</blockquote></details>

I realized that the block summary table is not sorted at first, but when I clicked on the link the block content is loaded and scrolled into view however the table is also modified by being sorted.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 31 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MukbUAR8ofq_JlbX4pG:-Mul00b416_p6gb9Eqwc:bcahwnp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/1b51341b21fb9d3cea572bd211bebb35c97b93c8/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why are you dealing with filters in this method?
</blockquote></details>

I think this code was moved here during the time I was merging the development branch into my branch. And you're right this seems to be the cause of some of the failing tests because I had to sort the table to make the test pass.
___
*[src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html, line 35 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MuWZRQXB3Nk4YDBNFBS:-Mul1SSt10MdIoL3_B8i:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cb78d69ca960b32cedc65bdbf842199949f2ff7/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It seems you haven't updated this link here at all? :) 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-01 09:59 UTC, hettlage requested changes
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/92)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[cypress/support/components/block-summaries.ts, line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-Muoh8H4EOwm_dN6_djn:-Muoh8H4EOwm_dN6_djo:b-4ry2qu) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2fa2c1cde53b1eb8d791a5019e895652e8357c66/cypress/support/components/block-summaries.ts#L10)):*
> ```XML
> const BLOCK_LINK = '[data-test="block-link"]';
> const BLOCK_CONTENT = '[data-test="block-content"]';
> const LOADED_BLOCK_CONTENT = '[data-test="displayed-block-content"]';
> ```

You might consider renaming the constant to DISPLAYED_BLOCK_CONTENT (for consistency).


<!-- Sent from Reviewable.io -->

2022-02-01 13:10 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/92)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[cypress/support/components/block-summaries.ts, line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-Muoh8H4EOwm_dN6_djn:-MupOnUz4dd8nSmXqkgG:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2fa2c1cde53b1eb8d791a5019e895652e8357c66/cypress/support/components/block-summaries.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You might consider renaming the constant to DISPLAYED_BLOCK_CONTENT (for consistency).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-01 13:54 UTC, hettlage requested changes
> Reviewed 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/92)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[cypress/integration/proposal/block-summaries.spec.ts, line 68 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MupYzCA5f_LoY01E_kH:-MupYzCBDzoUhRfp91HJ:b-qsiqet) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2fa2c1cde53b1eb8d791a5019e895652e8357c66/cypress/integration/proposal/block-summaries.spec.ts#L68)):*
> ```XML
>   });
> 
>   it('should have correct block cotent scrolled into viewport when block name link is clicked', () => {
> ```

You should still, test that the correct block is loaded...


<!-- Sent from Reviewable.io -->

2022-02-07 11:04 UTC, hettlage requested changes
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/92)* status: all files reviewed, 7 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[cypress/integration/proposal/block-summaries.spec.ts, line 68 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MutWjgt7WRbJaYpdgHj:-MutWjguDMnpEXOPd9O3:b-h2a46n) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/0a4e59c29f38957f1df8344a51a06db6f7f29902/cypress/integration/proposal/block-summaries.spec.ts#L68)):*
> ```XML
>   });
> 
>   it('should have correct block cotent scrolled into viewport when block name link is clicked', () => {
> ```

As you are not testing scrolling, I'd suggest to update the description:

```
it("should load the correct block content when a block name link is clicked")
```
___
*[cypress/integration/proposal/summary-of-executed-observations.spec.ts, line 4 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MutXSO56xfgf9E5POqL:-MutXSO56xfgf9E5POqM:b-uubfkr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/0a4e59c29f38957f1df8344a51a06db6f7f29902/cypress/integration/proposal/summary-of-executed-observations.spec.ts#L4)):*
> ```XML
> import { SummaryOfExecutedObservations } from '../../support/components/summary-of-executed-observations';
> import {
>   forceAuthenticationError,
> ```

The fact that `ng lint` passes despite all these unused imports indicates there might be an issue with the listing setup., Can you perhaps have a look?
___
*[cypress/integration/proposal/summary-of-executed-observations.spec.ts, line 24 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MutY3iC3-fdlXf6P43V:-MutY3iC3-fdlXf6P43W:b-h2a46n) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/0a4e59c29f38957f1df8344a51a06db6f7f29902/cypress/integration/proposal/summary-of-executed-observations.spec.ts#L24)):*
> ```XML
>   });
> 
>   it('should have correct block cotent scrolled into viewport when block name link is clicked', () => {
> ```

As you are not testing scrolling, I'd suggest to update the description:

```
it("should load the correct block content when a block name link is clicked")
```
___
*[cypress/support/components/block-summaries.ts, line 51 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MutYSWvCETepj1-tE6o:-MutYSWvCETepj1-tE6p:b-tvmxy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/0a4e59c29f38957f1df8344a51a06db6f7f29902/cypress/support/components/block-summaries.ts#L51)):*
> ```XML
>   }
> 
>   static clickBlockNameLink() {
> ```

Minor suggestion: Pass the 4 as an argument in clickBlockNameLink and correctBlockLoaded
___
*[cypress/support/components/summary-of-executed-observations.ts, line 4 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MutYj4bA-3UGa-uBvqd:-MutYj4bA-3UGa-uBvqe:b-6z8zj6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/0a4e59c29f38957f1df8344a51a06db6f7f29902/cypress/support/components/summary-of-executed-observations.ts#L4)):*
> ```XML
> const DISPLAYED_BLOCK_CONTENT = '[data-test="displayed-block-content"]';
> 
> export class SummaryOfExecutedObservations {
> ```

Minor suggestion: Pass the 8 as an argument in clickBlockNameLink and correctBlockLoaded
___
*[src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html, line 34 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MutZ2mJ3fcRijmGVhNM:-MutZ2mJ3fcRijmGVhNN:b-54j95k) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/0a4e59c29f38957f1df8344a51a06db6f7f29902/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L34)):*
> ```HTML
>     <div class="summary-row row">
>       <div>
>         <div data-test="executed-observations-link">
> ```

Nitpicking: The link is not really for exceed observations.


<!-- Sent from Reviewable.io -->

2022-02-09 10:29 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/92)* status: 12 of 22 files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[cypress/integration/proposal/block-summaries.spec.ts, line 68 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MutWjgt7WRbJaYpdgHj:-MvStxsM3RpxGDRJi-_1:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/0a4e59c29f38957f1df8344a51a06db6f7f29902/cypress/integration/proposal/block-summaries.spec.ts#L68)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As you are not testing scrolling, I'd suggest to update the description:

```
it("should load the correct block content when a block name link is clicked")
```
</blockquote></details>

Done.
___
*[cypress/integration/proposal/summary-of-executed-observations.spec.ts, line 4 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MutXSO56xfgf9E5POqL:-MvSxrUU3so4R24qCzjd:bwz1rtb) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/0a4e59c29f38957f1df8344a51a06db6f7f29902/cypress/integration/proposal/summary-of-executed-observations.spec.ts#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The fact that `ng lint` passes despite all these unused imports indicates there might be an issue with the listing setup., Can you perhaps have a look?
</blockquote></details>

I did have a look, you are right `ng lint` isn't set up to disallow unused imports. I have set it up now, what about the order of the imports? is it necessary to disallow some order?

Also, I realized that `ng lint --fix` does not fix all the issues, most have to be fixed manually which is my next task.
___
*[cypress/integration/proposal/summary-of-executed-observations.spec.ts, line 24 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MutY3iC3-fdlXf6P43V:-MvSuDBC6JbZGzrA26kE:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/0a4e59c29f38957f1df8344a51a06db6f7f29902/cypress/integration/proposal/summary-of-executed-observations.spec.ts#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As you are not testing scrolling, I'd suggest to update the description:

```
it("should load the correct block content when a block name link is clicked")
```
</blockquote></details>

Done.
___
*[cypress/support/components/block-summaries.ts, line 51 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MutYSWvCETepj1-tE6o:-MvSw0sL2ahjER20Vrxz:bb6un1j) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/0a4e59c29f38957f1df8344a51a06db6f7f29902/cypress/support/components/block-summaries.ts#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Minor suggestion: Pass the 4 as an argument in clickBlockNameLink and correctBlockLoaded
</blockquote></details>

Done
___
*[src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html, line 34 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MutZ2mJ3fcRijmGVhNM:-MvSy_rBAI00pUJgk3xP:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/0a4e59c29f38957f1df8344a51a06db6f7f29902/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Nitpicking: The link is not really for exceed observations.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-09 10:52 UTC, hettlage requested changes
> Reviewed 10 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/92)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[cypress/integration/proposal/block-summaries.spec.ts, line 68 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/92#-MutWjgt7WRbJaYpdgHj:-MvT5UYf-4cmg89B3fZ8:b-hcnw9x) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/0a4e59c29f38957f1df8344a51a06db6f7f29902/cypress/integration/proposal/block-summaries.spec.ts#L68)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see any change here...


<!-- Sent from Reviewable.io -->

2022-02-09 11:16 UTC, hettlage approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/92)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2022-02-09 11:17 UTC, merged