Table sorting by clicking on the header
saltastroops/web-manager-2021 pull request #93
Opened 2022-02-04 14:08 UTC by mofokeng-chaka

2022-02-07 10:34 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/93)* status: all files reviewed, 15 unresolved discussions (waiting on @mofokeng-chaka)

___
*[.eslintrc.json, line 40 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvII5-g0Z3Db5-7bWuH:-MvII5-g0Z3Db5-7bWuI:b-raoohx) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/.eslintrc.json#L40)):*
> ```jsonc
>             "extendDefaults": true,
>             "types": {
>               "{}": false
> ```

Having read the documentation, I'm not convinced that disabling this is a good idea.
___
*[cypress/integration/proposal/block-summaries.spec.ts, line 75 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIjeyxB4B6Rtpw8M7Z:-MvIjeyxB4B6Rtpw8M7_:b-l7bzir) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/cypress/integration/proposal/block-summaries.spec.ts#L75)):*
> ```XML
>   });
> 
>   it('should have the table sorted by names when block ID column is clicked', () => {
> ```

ID > name
___
*[cypress/support/components/block-summaries.ts, line 7 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIXtin5rkdbYppnQ9G:-MvIXtio1lKFBvsCvf26:b-ihwoze) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/cypress/support/components/block-summaries.ts#L7)):*
> ```XML
> const SORT_BY_ID_COLUMN = '[data-testid=block-summary-id]';
> const SORT_BY_NAME_COLUMN = '[data-testid=block-summary-name]';
> const BLOCK_ID_ROW = '[data-test=block-id]';
> ```

"ROW" might be misleading, isn't this more of a "CELL" or "ELEMENT"?
___
*[cypress/support/components/block-summaries.ts, line 59 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIIgLmAt7QPWRpGOjv:-MvIIgLmAt7QPWRpGOjw:b-4edlh0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/cypress/support/components/block-summaries.ts#L59)):*
> ```XML
>   }
> 
>   static blocksSortedByIdInAscending(ascending: boolean) {
> ```

Can't you combine blocksSortedByIdInAscending and blocksSortedByNameInAscending into a single function (with appropriate arguments)?

Also I'd call the function blocksSortedBy (without the "Ascending"), and (maybe) would consider making ascending a literal accepting the values "ascending" or "descending".
___
*[src/app/utils.ts, line 61 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIZ-ebB4DUfO830GPy:-MvIZ-ebB4DUfO830GPz:b-plj2iz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/utils.ts#L61)):*
> ```XML
>     return function (a: T, b: T) {
>       let result = 0;
>       if (typeof a[key] === 'string' && typeof b[key] === 'string') {
> ```

This if condition raises the question what should happen if only `a` or only `b` is a string? But the point is probably moot, as both `a` and `b` are declared to be of the same type. So maybe just ditch the comparison for `b`?:



_Suggestion:_
```XML
if (typeof b[key] === 'string') {
   ...
```
___
*[src/app/utils.ts, line 63 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIZnOt71kGuhNUh4aF:-MvIZnOt71kGuhNUh4aG:b-t3lfwz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/utils.ts#L63)):*
> ```XML
>       if (typeof a[key] === 'string' && typeof b[key] === 'string') {
>         result =
>           parseToLowerCase(a[key]) < parseToLowerCase(b[key])
> ```

I don't think there is a need for `parseToLowerCase`. If TypeScript isn't clever enough to see that `a[key]` (or `b[key]`) is a string, you should just cast it.
___
*[src/app/utils.ts, line 64 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvI_NhZ3Wo6jDZ0VAbQ:-MvI_NhZ3Wo6jDZ0VAbR:b-yxsevj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/utils.ts#L64)):*
> ```XML
>         result =
>           parseToLowerCase(a[key]) < parseToLowerCase(b[key])
>             ? -1
> ```

I think the code would be easier to read if you replace at least one of the ternary operators with an `if` statement.
___
*[src/app/utils.ts, line 69 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvI_xt430WN8W3tD1Sb:-MvI_xt430WN8W3tD1Sc:b-yxsevj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/utils.ts#L69)):*
> ```XML
>             : 0;
>       } else {
>         result = a[key] < b[key] ? -1 : a[key] > b[key] ? 1 : 0;
> ```

I think the code would be easier to read if you replace at least one of the ternary operators with an `if` statement.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.html, line 30 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIatu3CYLDlV4DmJb8:-MvIatu3CYLDlV4DmJb9:b-3a5kec) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L30)):*
> ```HTML
>   <div class="block-row headers is-info row">
>     <div
>       class="sortable-column"
> ```

I'd suggest to ditch the `class` attribute and include its value in the object returned by the `sortableColumnClass` method.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.html, line 45 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIbxUw0q1nK_E3Ug4D:-MvIbxUw0q1nK_E3Ug4E:bpq1uqp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L45)):*
> ```HTML
>       Block
>     </div>
>     <div>ObsTime</div>
> ```

Why don't you make all columns sortable?
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 18 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIcgfnDexJhuKTxs5I:-MvIcgfnDexJhuKTxs5J:bf0u4ww) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L18)):*
> ```XML
>   filteredByUnobservable!: boolean;
>   filteredBlocks: BlockSummary[] = [];
>   columnsSortDirections: { [blockName: string]: string } = {};
> ```

Shouldn't `blockName` be `columnName`?

Also, there second `string` is a bit broad; it should be `ask` or `desc` or an empty string. (Although `null` or `undefined` might make more sense than an empty string, perhaps?)
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 37 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIdDsE8ph96RMfSuSv:-MvIdDsE8ph96RMfSuSw:bg3iod9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L37)):*
> ```XML
>       document.querySelectorAll('.sortable-column');
>     sortableColumnElements.forEach((columnElement) => {
>       const column = columnElement.getAttribute('data-testid');
> ```

Given that `data-tested` is explicitly referring to a `test`, I wouldn't use it here.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 111 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIe--r4mOqzgwSBe8J:-MvIe--r4mOqzgwSBe8K:bg3iod9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L111)):*
> ```XML
>   onColumnClick(event: Event): void {
>     const element = event.target as HTMLDivElement;
>     const dataTestID = ele [...]

2022-02-09 07:41 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/93)* status: 0 of 7 files reviewed, 15 unresolved discussions (waiting on @hettlage)

___
*[cypress/integration/proposal/block-summaries.spec.ts, line 75 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIjeyxB4B6Rtpw8M7Z:-MvIyVnk9yztCa_4l5Df:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/cypress/integration/proposal/block-summaries.spec.ts#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

ID > name
</blockquote></details>

Done.
___
*[cypress/support/components/block-summaries.ts, line 7 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIXtin5rkdbYppnQ9G:-MvRydXM14UH-Pr2D_JB:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/cypress/support/components/block-summaries.ts#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"ROW" might be misleading, isn't this more of a "CELL" or "ELEMENT"?
</blockquote></details>

Done.
___
*[cypress/support/components/block-summaries.ts, line 59 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIIgLmAt7QPWRpGOjv:-MvSQA0d8SoVIp9VjU2V:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/cypress/support/components/block-summaries.ts#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can't you combine blocksSortedByIdInAscending and blocksSortedByNameInAscending into a single function (with appropriate arguments)?

Also I'd call the function blocksSortedBy (without the "Ascending"), and (maybe) would consider making ascending a literal accepting the values "ascending" or "descending".
</blockquote></details>

Done.
___
*[src/app/utils.ts, line 61 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIZ-ebB4DUfO830GPy:-MvJ-3hR8o-crx2whDc1:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/utils.ts#L61)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This if condition raises the question what should happen if only `a` or only `b` is a string? But the point is probably moot, as both `a` and `b` are declared to be of the same type. So maybe just ditch the comparison for `b`?:
</blockquote></details>

Done.
___
*[src/app/utils.ts, line 63 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIZnOt71kGuhNUh4aF:-MvJ02Hr9kPpfi9mM-SD:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/utils.ts#L63)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think there is a need for `parseToLowerCase`. If TypeScript isn't clever enough to see that `a[key]` (or `b[key]`) is a string, you should just cast it.
</blockquote></details>

Done.
___
*[src/app/utils.ts, line 64 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvI_NhZ3Wo6jDZ0VAbQ:-MvJ1sQd9_X9dIs2eYYK:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/utils.ts#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the code would be easier to read if you replace at least one of the ternary operators with an `if` statement.
</blockquote></details>

Done.
___
*[src/app/utils.ts, line 69 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvI_xt430WN8W3tD1Sb:-MvJ2NP767_7ev7nIMKV:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/utils.ts#L69)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the code would be easier to read if you replace at least one of the ternary operators with an `if` statement.
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.html, line 30 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIatu3CYLDlV4DmJb8:-MvJ5ulq5U0sKQ_sUAev:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to ditch the `class` attribute and include its value in the object returned by the `sortableColumnClass` method.
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.html, line 45 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIbxUw0q1nK_E3Ug4D:-MvRuLZ7E3E1cVxWqJVm:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L45)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why don't you make all columns sortable?
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 18 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIcgfnDexJhuKTxs5I:-MvRuvi34qfHN_GlU9uw:b9ajofw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't `blockName` be `columnName`?

Also, there second `string` is a bit broad; it should be `ask` or `desc` or an empty string. (Although `null` or `undefined` might make more sense than an empty string, perhaps?)
</blockquote></details>

`null` and `undefined` gives me an error: Type 'desc' | 'asc' is not assignable to type 'null'. So I have settled to an empty string.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 37 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIdDsE8ph96RMfSuSv:-MvRvKxm-1jhXl_ZjScE:b-ujsq5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given that `data-tested` is explicitly referring to a `test`, I wouldn't use it here.
</blockquote></details>

Maybe data-column-id?
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 111 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIe--r4mOqzgwSBe8J:-MvRvSXEClYQ66z4AJTf:b-iobuo6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L111)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given that `data-tested` is explicitly referring to a `test`, I wouldn't use it here.
</blockquote></details>

See my comment above
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 118 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIgA_C4D2TZl-SRPqS:-MvRvWsG5waqD9jW_SCC:b-uumjxe) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L118)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This lime looks odd... :-)

I'd recommend that you make sure that `this.columnsSortDirections` has the new value before doing anything else in this nmeth
</blockquote></details>

I have verified that `this.columns [...]

2022-02-09 10:05 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/93)* status: all files reviewed, 13 unresolved discussions (waiting on @mofokeng-chaka)

___
*[cypress/integration/proposal/block-summaries.spec.ts, line 75 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSoGt_8INNU1t2nlww:-MvSoGt_8INNU1t2nlwx:bokkjqq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/cypress/integration/proposal/block-summaries.spec.ts#L75)):*
> ```XML
>   });
> 
>   it('should have the table sorted by names when block name column is clicked', () => {
> ```

You should also test the following:

Click column A [sorted in ascending order by A]
Click column A [sorted in descending order by A]
Click column B [sorted in ascending order by B]
Click column A [sorted in ...]

And that is where it gets interesting: Should the results be sorted in ascending or descending order now?
___
*[cypress/integration/proposal/block-summaries.spec.ts, line 82 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSRq-5DSk3dlkZhZ4L:-MvSRq-5DSk3dlkZhZ4M:b-r3wjww) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/cypress/integration/proposal/block-summaries.spec.ts#L82)):*
> ```XML
>   });
> 
>   it('should have the table sorted by observation time when observation time column is clicked', () => {
> ```

Nit-picking: when > when the

Applies to the other test cases as well, of course. :-)
___
*[cypress/support/components/block-summaries.ts, line 96 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSSNb02A0YuzYsf6SJ:-MvSSNb02A0YuzYsf6SK:bf8stnm) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/cypress/support/components/block-summaries.ts#L96)):*
> ```XML
>   static blocksSortedBy(column: string, order: 'ascending' | 'descending') {
>     let columnElement = '';
>     switch (column) {
> ```

There is nothing inherently wrong with this... but rather than having this big switch statement, couldn't you just create the column elements dynamically from the `column` parameter?
___
*[cypress/support/components/block-summaries.ts, line 120 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSYr8D1yehOK-hm6eJ:-MvSYr8EE-zewjbC5dCl:b5r3qfw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/cypress/support/components/block-summaries.ts#L120)):*
> ```XML
> 
>     let sortedBlockIds = [];
>     if (order==='ascending') {
> ```

You should also test that the arrow symbol is shown (i.e. that the relevant class is present.
___
*[src/app/utils.ts, line 64 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSlffb1P0CulMZ2GYw:-MvSlffb1P0CulMZ2GYx:b-1gk864) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/src/app/utils.ts#L64)):*
> ```XML
>         if (String(a[key]) < String(b[key])) {
>           result = -1;
>         } else if (String(a[key]) > String(b[key])) {
> ```

Why do you need the `String` constructor, given that `a[key]` and `b[key]` are a string already? 
___
*[src/app/utils.ts, line 70 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSmEzc4mrYmWG8pfv0:-MvSmEzc4mrYmWG8pfv1:b-5vxm9g) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/src/app/utils.ts#L70)):*
> ```XML
>         }
>       } else {
>         const key_split = key.toString().split('.');
> ```

I wonder whether this doesn't make the utility function overly complicated... At least you should comment what yiu are doing here. :-)
___
*[src/app/utils.ts, line 217 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSs4hHCKqrq7Af9j1A:-MvSs4hHCKqrq7Af9j1B:bjg82yu) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/src/app/utils.ts#L217)):*
> ```XML
>   : '';
> 
> export type Leaves<T, D extends number = 10> = [D] extends [never]
> ```

I think this is becoming a bit complicated... Can we have a chat about this?
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.html, line 49 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSteDu5SMGNP71IDSF:-MvSteDu5SMGNP71IDSG:b-1147y9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L49)):*
> ```HTML
>       (click)="onColumnClick($event)"
>       data-sort-id="block-summary-observationTime"
>       data-testid="block-summary-observation-time"
> ```

You don't need a data-sort-id attribute; you could instead pass the required value as a second argument to the `onColumnClick` method.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 18 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIcgfnDexJhuKTxs5I:-MvSv16K8ZIBeqRdMbV4:b-agkxqq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L18)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

`null` and `undefined` gives me an error: Type 'desc' | 'asc' is not assignable to type 'null'. So I have settled to an empty string.
</blockquote></details>

Wouldn't `"asc" | "desc" | null` work?
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 37 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIdDsE8ph96RMfSuSv:-MvSvVhg2uXqfltwIaB-:b-vwkcq1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L37)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Maybe data-column-id?
</blockquote></details>

Or nothing at all. Can we chat about this?
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 111 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIe--r4mOqzgwSBe8J:-MvSvaoq6Bw6g0CAl1Fv:bxawmwz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L111)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

See my comment above
</blockquote></details>

See mine as well. :-)
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 118 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIgA_C4D2TZl-SRPqS:-MvSw2oSBl3OoMlYnDkL:bajc32v) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L118)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I have verified that `this.columnsSortDirections` has the new by printing it in the console. The line `this.isDec = direction === 'asc'` is used to make sure that the icon on the clicked column shows the opposite direction than the sort direction (i.e. if the table is sorted in ascending by block id column, then the icon on this column will show descending direction.
</blockquote></details>

Can we talk about this?
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 146 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSnbWFEoBPbCAoobRv:-MvSnbWFEoBPbCAoobRw:bu69fqg) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffd [...]

2022-02-10 14:42 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/93)* status: 2 of 7 files reviewed, 12 unresolved discussions (waiting on @hettlage)

___
*[cypress/integration/proposal/block-summaries.spec.ts, line 75 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSoGt_8INNU1t2nlww:-MvZ48gbD3-8J-OgEQyv:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/cypress/integration/proposal/block-summaries.spec.ts#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should also test the following:

Click column A [sorted in ascending order by A]
Click column A [sorted in descending order by A]
Click column B [sorted in ascending order by B]
Click column A [sorted in ...]

And that is where it gets interesting: Should the results be sorted in ascending or descending order now?
</blockquote></details>

Done.
___
*[cypress/integration/proposal/block-summaries.spec.ts, line 82 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSRq-5DSk3dlkZhZ4L:-MvT_c8L8hEMd7LTR2D2:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/cypress/integration/proposal/block-summaries.spec.ts#L82)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Nit-picking: when > when the

Applies to the other test cases as well, of course. :-)
</blockquote></details>

Done.
___
*[cypress/support/components/block-summaries.ts, line 96 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSSNb02A0YuzYsf6SJ:-MvZ46Kb2VMjdsVp6_bn:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/cypress/support/components/block-summaries.ts#L96)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is nothing inherently wrong with this... but rather than having this big switch statement, couldn't you just create the column elements dynamically from the `column` parameter?
</blockquote></details>

Done.
___
*[cypress/support/components/block-summaries.ts, line 120 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSYr8D1yehOK-hm6eJ:-MvZ45aPBCBZTeP_NpeV:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/cypress/support/components/block-summaries.ts#L120)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should also test that the arrow symbol is shown (i.e. that the relevant class is present.
</blockquote></details>

Done.
___
*[src/app/utils.ts, line 64 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSlffb1P0CulMZ2GYw:-MvT1BjC-udXd42rmUNw:b3f2u1g) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/src/app/utils.ts#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you need the `String` constructor, given that `a[key]` and `b[key]` are a string already? 
</blockquote></details>

Aaah, I remember why I needed this, it is because some block names have capital first letters while others don't. So when comparing the two without taking them to lowercase you get wrong results. So I meant to convert them to lowercase before comparing them which is what I have done now.

Also because this function uses a generic type if I don't use the `String` constructor I am not able to convert them to lowercase by the `toLocaleLowerCase` method because `a[key]` and `b[key]` are of type `T[keyof T]` string.
___
*[src/app/utils.ts, line 70 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSmEzc4mrYmWG8pfv0:-MvY1ITsB9scjXDnDEgs:b-m4d21p) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/src/app/utils.ts#L70)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I wonder whether this doesn't make the utility function overly complicated... At least you should comment what yiu are doing here. :-)
</blockquote></details>

I tried doing something less complicated but I end up having trouble with typescript complaining about my type not being type-safe.
I have settled on using this function because it is already type-safe and works fine for our use case.
___
*[src/app/utils.ts, line 217 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSs4hHCKqrq7Af9j1A:-MvY1CIaC1W-DkoVn4t_:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/src/app/utils.ts#L217)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think this is becoming a bit complicated... Can we have a chat about this?
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.html, line 49 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSteDu5SMGNP71IDSF:-MvY1Abo5aEjlAFGVj28:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You don't need a data-sort-id attribute; you could instead pass the required value as a second argument to the `onColumnClick` method.
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 18 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIcgfnDexJhuKTxs5I:-MvY0xNg7AlOZDsM8wYK:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't `"asc" | "desc" | null` work?
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 37 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIdDsE8ph96RMfSuSv:-MvY0tHx8mJO4st6rH2o:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Or nothing at all. Can we chat about this?
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 111 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIe--r4mOqzgwSBe8J:-MvZ4BYw4AGV_0XrUGxe:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L111)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See mine as well. :-)
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 118 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIgA_C4D2TZl-SRPqS:-MvY0YbU8ENyrqVHhVMW:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L118)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we talk about this?
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 146 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSnbWFEoBPbCAoobRv:-MvY0QE-7o75WgUtvEbn:btc4ywj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/src/app/proposal/block [...]

2022-02-11 08:13 UTC, hettlage requested changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/93)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 118 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIgA_C4D2TZl-SRPqS:-MvbmgJACy0l80g8YTPA:b6bf17d) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L118)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still have an uneasy feeling about this. Let's chat briefly.


<!-- Sent from Reviewable.io -->

2022-02-14 12:01 UTC, hettlage requested changes
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/93)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[cypress/support/components/block-summaries.ts, line 120 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSYr8D1yehOK-hm6eJ:-Mvs4Ekr-PNCmXn5bBi8:bdme5vl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/cypress/support/components/block-summaries.ts#L120)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh. Did I miss that? Sorry!

Anyway, the test shows a problem., I think: When the table is sorted in ascending order, your class name is `desc`. So I'd suggest to change the CSS so that you can use `ask` instead of `desc` in this case.


<!-- Sent from Reviewable.io -->

2022-02-14 12:35 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/93)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[cypress/support/components/block-summaries.ts, line 120 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvSYr8D1yehOK-hm6eJ:-MvsCFu7-bKH7QyIgzBw:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9ffda07a6856e33caed496b0302637afaf0fc930/cypress/support/components/block-summaries.ts#L120)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oh. Did I miss that? Sorry!

Anyway, the test shows a problem., I think: When the table is sorted in ascending order, your class name is `desc`. So I'd suggest to change the CSS so that you can use `ask` instead of `desc` in this case.
</blockquote></details>

Done.
___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 118 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIgA_C4D2TZl-SRPqS:-MvsCHXV0nDX8M9zc6Ve:bv70nfu) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L118)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I still have an uneasy feeling about this. Let's chat briefly.
</blockquote></details>

I didn't see this comment. I am happy to chat about it if you still want to?


<!-- Sent from Reviewable.io -->

2022-02-14 13:44 UTC, hettlage approved these changes
Some of your Cypress tests seem to be failing.

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-:-MvsTNQb-lUsmPQXEFFz:b1uczhn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

___
*[src/app/proposal/blocks/block-summaries/block-summaries.component.ts, line 118 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-MvIgA_C4D2TZl-SRPqS:-MvsQIDuEzX_18k-zxI-:b-3nu48d) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f59f224120f98aff7d1f68e87f8b14719d151231/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L118)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I didn't see this comment. I am happy to chat about it if you still want to?
</blockquote></details>

But we chatted about it, and you addressed the issue, didn't you? :-D


<!-- Sent from Reviewable.io -->

2022-02-15 08:21 UTC, mofokeng-chaka reviewed
That's true and all the tests that were failing in my case are from `cypress/integration/forgot-password.spec.ts`. I fixed two of them and there's still one that fails, can you please verify if it does fail on your side? If it does fail please help figure out why it is failing.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-:-MvwS5FNCp5BbItSny9Z:bk313je)* status: 7 of 10 files reviewed, all discussions resolved (waiting on @hettlage)



<!-- Sent from Reviewable.io -->

2022-02-15 20:01 UTC, hettlage approved these changes
All the tests are passing for me.

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-:-MvyyE4_2uVgIlFh9-oT:bfvf176)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2022-02-16 06:09 UTC, mofokeng-chaka reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/93#-:-Mw08Xa2-xfYxiYx3k3n:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2022-02-16 06:24 UTC, merged