Mos page
saltastroops/web-manager-2021 pull request #99
Opened 2022-02-28 07:25 UTC by saltastroops

2022-02-28 14:32 UTC, hettlage requested changes
> Reviewed 66 of 66 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: all files reviewed, 24 unresolved discussions (waiting on @saltastroops)

___
*[src/styles.scss, line 162 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-7AI6AAeRuAUZ_J5V:-Mx-7AI6AAeRuAUZ_J5W:b88nbic) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/styles.scss#L162)):*
> ```SCSS
> }
> 
> .is-orange-background {
> ```

Your class names include colours, but the actual value is derived from variables with aname that has semantic meaning, which might be unfortunate.
___
*[src/styles.scss, line 170 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-7SZb8Gzr-HtXEnfr:-Mx-7SZb8Gzr-HtXEnfs:bjvd3h) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/styles.scss#L170)):*
> ```SCSS
> }
> 
> .is-clear-background {
> ```

I would expect a transparent rather than white background for "clear".
___
*[src/app/app.module.ts, line 145 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-7l4q3yjBtPG48Kx9:-Mx-7l4q3yjBtPG48KxA:bvbx750) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/app.module.ts#L145)):*
> ```XML
>     ChangePasswordComponent,
>     MosComponent,
>     LegendComponent,
> ```

"LegendComponent" and "FiltersComponent" are very generic names, which might not be ideal for components that are specifically concerned with MOS.
___
*[src/app/mos/mos.component.html, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-9TKdEXYosVuMwx7J:-Mx-9TKdEXYosVuMwx7K:byr07ne) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/mos/mos.component.html#L1)):*
> ```HTML
> <div>
> ```

(I know the following comments cover more than this file, but I hope that's okay.)

When you hover over a table row, its background turns white. While highlighting the row is a good idea, this may give the false impression that there is "no need for any action right now" for that row. Maybe instead you could give the whole table a white background and then change the opacity when hovering over a row? Or use a different colour?

All the mask comments are missing.

The number of rows for 2021-2-SCI-023 differs between the old and new WM. Probably true for at least one other proposal code as well.

RA should be displayed as HH:MM:SS rather than degrees.

Changing the semester or clicking on the checkboxes seems to have no effect.

The RA filters state the values are in hours, but the filtering is done in degrees.

Filtering doesn't work properly: If I filter by Barcode and then in addition by RA, the number of displayed rows _increases_.

I guess this is beyond the PR, but the Edit buttons do nothing.

I guess this is beyond the PR, but there are no links in the table.

This point will probably become moot if you move from grids to tables, but the filter labels and fields are not aligned properly.

You might consider adding default values for cutting power, RA and Dec (as in the current WM).

The thick line underneath the eating "MOS" is almost invisible due to its colour.
___
*[src/app/mos/mos.component.ts, line 55 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-JY473CPDF4vWs1do:-Mx-JY473CPDF4vWs1dp:bs7k7i0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/mos/mos.component.ts#L55)):*
> ```XML
>       semesters.push(nextSemesterOf(this.selectedSemester));
>     } else {
>         semesters = semesters.filter((s) => s !== nextSemesterOf(this.selectedSemester))
> ```

But wouldn't that include _every_ semester other than the next one?
___
*[src/app/mos/mos.component.ts, line 60 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-Jg3P7_DPhZsis-Mw:-Mx-Jg3P7_DPhZsis-Mx:b-hau0lo) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/mos/mos.component.ts#L60)):*
> ```XML
>       semesters.push(previousSemesterOf(this.selectedSemester));
>     } else {
>       semesters = semesters.filter((s) => s !== previousSemesterOf(this.selectedSemester))
> ```

But wouldn't that include _every_ semester other than the previous one?
___
*[src/app/mos/mos.component.ts, line 103 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-K9O4EK8pHyNC7KLI:-Mx-K9O4EK8pHyNC7KLJ:b-lukiqw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/mos/mos.component.ts#L103)):*
> ```XML
>   rowColor(block: MosBlock): string {
>     if (!!block.cutDate && block.status === "Active"){
>       return "is-orange-background"
> ```

Semantic class names might be nicer.
___
*[src/app/mos/mos.component.ts, line 123 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-K5w04MoVYGe73xSV:-Mx-K5w04MoVYGe73xSW:b-fsvz5v) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/mos/mos.component.ts#L123)):*
> ```XML
>       return "is-red-background"
>     }
>     // if (false) {
> ```

Can this code be deleted?
___
*[src/app/mos/legend/legend.component.html, line 4 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-KVw4D4-VOnr-NrvE:-Mx-KVw4D4-VOnr-NrvF:b-lukiqw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/mos/legend/legend.component.html#L4)):*
> ```HTML
>   <h2 class="title is-5">Colour coding:</h2>
>   <div class="has-two-columns padded">
>     <div class="square is-orange-background"></div>
> ```

Semantic class names might be nicer.
___
*[src/app/mos/mask-to-remove/mask-to-remove.component.html, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-Ke_15LeANgKnOR0W:-Mx-Ke_15LeANgKnOR0X:bbz21bc) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/mos/mask-to-remove/mask-to-remove.component.html#L1)):*
> ```HTML
> <div>
> ```

Why do you have a separate component for this?
___
*[src/app/mos/mask-to-remove/mask-to-remove.component.ts, line 9 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-L0iN5yaEkd4uqDf9:-Mx-L0iN5yaEkd4uqDfA:bhxkz8l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/mos/mask-to-remove/mask-to-remove.component.ts#L9)):*
> ```XML
>   styleUrls: ['./mask-to-remove.component.scss']
> })
> export class MaskToRemoveComponent implements OnInit {
> ```

"Mask" should be "Masks". The sane is true for the selector etc.
___
*[src/app/mos/mask-to-remove/mask-to-remove.component.ts, line 12 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-T4Ih27AKu0Y8lOih:-Mx-T4Ih27AKu0Y8lOii:b-lym7m4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/mos/mask-to-remove/mask-to-remove.component.ts#L12)):*
> ```XML
>   @Input() mosData!: MosBlock[]
>   @Input() currentMasks!: string[]
>   maskToRemove: string[] = []
> ```

maskToRemove > masksToRemove
___
*[src/app/mos/mask-to-remove/mask-to-remove.component.ts, line 13 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-SowZ5b58Xqq97vm6:-Mx-SowZ5b58Xqq97vm7:bo1ibiu) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/mos/mask-to-remove/mask-to-remove.component.ts#L13)):*
> ```XML
>   @Input() currentMasks!: string[]
>   maskToRemove: string[] = []
>   neededMask: string[] = []
> ```

neededMask > neededMasks
___
*[src/app/mos/mask-to-remove/mask-to-remove.compo [...]

2022-03-02 14:46 UTC, hettlage requested changes
> Reviewed 24 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: all files reviewed, 24 unresolved discussions (waiting on @saltastroops)

___
*[src/styles.scss, line 162 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-7AI6AAeRuAUZ_J5V:-Mx9fqPq5V-8cpEXJoaF:b4cfbun) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/styles.scss#L162)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Your class names include colours, but the actual value is derived from variables with aname that has semantic meaning, which might be unfortunate.
</blockquote></details>

Are the colour values used elsewhere? If so, CSS variables n=might be better, as you had before. (I wasn't commenting on the use of CSS variables, but rather on their names.
___
*[src/test.ts, line 25 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx9qaCS14Wrm5YogcWd:-Mx9qaCS14Wrm5YogcWe:bndcuqw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/test.ts#L25)):*
> ```XML
>   BrowserDynamicTestingModule,
>   platformBrowserDynamicTesting(), {
>     teardown: { destroyAfterEach: false }
> ```

Is that new from Angular 13? If so, is this the default in Angular 13 -- if not it might be worth removing it.
___
*[src/app/mos/mos.component.html, line 7 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx9r2SW-iFgxkmhOsJ8:-Mx9r2SW-iFgxkmhOsJ9:bqvvqqu) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/mos/mos.component.html#L7)):*
> ```HTML
>   <h2 class="title is-2">MOS</h2>
>   <hr class="heading-line mos-header" />
>   <p>The following masks are currently in the slit mask magazine, but aren't needed any longer.</p>
> ```

What if there are no such masks?
___
*[src/app/mos/mos.component.html, line 21 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx9rEeZ3vXbHU6_3O75:-Mx9rEeZ3vXbHU6_3O76:b-ixh01f) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/mos/mos.component.html#L21)):*
> ```HTML
>           <div class="select">
>             <select
>               [disabled]="loading"
> ```

I'm not convinced that is the best solution. Users should still be able to change the semester; you just should make sure the correct content is shown afterwards. (This applies to the other input components as well.)

And we should chat about the indication of loading, please.
___
*[src/app/mos/mos.component.html, line 129 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx9wmHg4t3CCpiIXk49:-Mx9wmHg4t3CCpiIXk4A:bdmendc) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/mos/mos.component.html#L129)):*
> ```HTML
>   <wm-mos-legend></wm-mos-legend>
> 
>   <div class="modal" [ngClass]="isModalActive ? 'is-active' : ''">
> ```

It might be good if pressing the Esc key closed the modal as well.
___
*[src/app/mos/mos.component.scss, line 61 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx9xkvz3s08kdhDesLC:-Mx9xkw-6TpBWIsBnLLR:bajc32v) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/mos/mos.component.scss#L61)):*
> ```SCSS
> }
> 
> .has-short-spaces {
> ```

Can we talk about this?
___
*[src/app/mos/mos.component.ts, line 35 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx9yF7K9miVKFHWqohA:-Mx9yF7K9miVKFHWqohB:b-jwxopb) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/mos/mos.component.ts#L35)):*
> ```XML
>       this.mosService.getCurrentMosMasks()
>     ]).subscribe(
>       (results: any) => {
> ```

This should at least be `any[]`, if it cannot be specified are precisely.
___
*[src/app/mos/mos.component.ts, line 36 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx9zCum9MBSgHw8tN0e:-Mx9zCum9MBSgHw8tN0f:b-d122b3) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/mos/mos.component.ts#L36)):*
> ```XML
>     ]).subscribe(
>       (results: any) => {
>         this.mosBlocks = results[0]
> ```

mosBlocks and displayMosBlocks should not point to the same array.
___
*[src/app/mos/mos.component.ts, line 49 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxA-GoE6gkvHCWaFQlO:-MxA-GoE6gkvHCWaFQlP:b-4wq4k2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/mos/mos.component.ts#L49)):*
> ```XML
>       () => {
>         this.loading = false
>         throw new Error("Failed to query MOS page data.")
> ```

Shouldn't you handle the error here?
___
*[src/app/mos/mos.component.ts, line 73 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxA-XBb51hVgMVgeElg:-MxA-XBb51hVgMVgeElh:b-j342b7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/mos/mos.component.ts#L73)):*
> ```XML
>     this.mosService.getMosBlock(semesters).subscribe(
>       (data) => {
>         this.displayedMosBlocks = data
> ```

But shouldn't that be `this.mosBlocks` really?
___
*[src/app/mos/mos.component.ts, line 156 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxA0OYV7gnf7f7Uzv3b:-MxA0OYV7gnf7f7Uzv3c:b-n3ejta) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/mos/mos.component.ts#L156)):*
> ```XML
>       !this.selectedCutMask!.maskComment
>     ) {
>       throw Error ("Need to fill out the form.")
> ```

Shouldn't the error be handled here?
___
*[src/app/mos/mos.component.ts, line 169 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxA1lhqBNWxXGOmGqBE:-MxA1lhqBNWxXGOmGqBF:by09zzr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/mos/mos.component.ts#L169)):*
> ```XML
>         (data: any) => {
>           this.mosBlocks = data;
>           this.displayedMosBlocks = data
> ```

mosBlocks and displayMosBlocks should not point to the same array.

And what about already existing filter conditions?
___
*[src/app/mos/mos.component.ts, line 171 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxA1tw00_-mznawB5fC:-MxA1tw00_-mznawB5fD:b-dnyx8r) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/mos/mos.component.ts#L171)):*
> ```XML
>           this.displayedMosBlocks = data
>           this.loading = false;
>           this.error = undefined;
> ```

Shouldn't the error be removed at the beginning of the loading?
___
*[src/app/service/mos.service.ts, line 42 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxA2mQX2XDvCRz1C9Tn:-MxA2mQX2XDvCRz1C9To:b-re2i5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/service/mos.service.ts#L42)):*
> ```XML
>   }
> 
>   updateMosMask(mask: MosMask, semesters: string[]) {
> ```

I don't think the service should query the MOS masks. (Nor should there be a need, given that only one mask is affected.)


<!-- Sent from Reviewable.io -->

2022-03-09 10:12 UTC, saltastroops reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: all files reviewed, 24 unresolved discussions (waiting on @hettlage)

___
*[src/styles.scss, line 162 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-7AI6AAeRuAUZ_J5V:-Mx3Nu6iAusmTxbBkK0p:bb6un1j) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/styles.scss#L162)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Are the colour values used elsewhere? If so, CSS variables n=might be better, as you had before. (I wasn't commenting on the use of CSS variables, but rather on their names.
</blockquote></details>

Done
___
*[src/styles.scss, line 170 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-7SZb8Gzr-HtXEnfr:-Mx3NuPf9UY5tyLqyfie:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/styles.scss#L170)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would expect a transparent rather than white background for "clear".
</blockquote></details>

Done.
___
*[src/test.ts, line 25 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx9qaCS14Wrm5YogcWd:-MxECXpm8JmjhjKo27qm:bz86aek) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/test.ts#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is that new from Angular 13? If so, is this the default in Angular 13 -- if not it might be worth removing it.
</blockquote></details>


it is the default
___
*[src/app/app.module.ts, line 145 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-7l4q3yjBtPG48Kx9:-Mx3S8uv4FJCLe4ebbC9:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/app.module.ts#L145)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"LegendComponent" and "FiltersComponent" are very generic names, which might not be ideal for components that are specifically concerned with MOS.
</blockquote></details>

Done.
___
*[src/app/mos/mos.component.html, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-9TKdEXYosVuMwx7J:-Mx4Xalt1irFIpeViNpc:b-cjcnfq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/mos/mos.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

(I know the following comments cover more than this file, but I hope that's okay.)

When you hover over a table row, its background turns white. While highlighting the row is a good idea, this may give the false impression that there is "no need for any action right now" for that row. Maybe instead you could give the whole table a white background and then change the opacity when hovering over a row? Or use a different colour?

All the mask comments are missing.

The number of rows for 2021-2-SCI-023 differs between the old and new WM. Probably true for at least one other proposal code as well.

RA should be displayed as HH:MM:SS rather than degrees.

Changing the semester or clicking on the checkboxes seems to have no effect.

The RA filters state the values are in hours, but the filtering is done in degrees.

Filtering doesn't work properly: If I filter by Barcode and then in addition by RA, the number of displayed rows _increases_.

I guess this is beyond the PR, but the Edit buttons do nothing.

I guess this is beyond the PR, but there are no links in the table.

This point will probably become moot if you move from grids to tables, but the filter labels and fields are not aligned properly.

You might consider adding default values for cutting power, RA and Dec (as in the current WM).

The thick line underneath the eating "MOS" is almost invisible due to its colour.
</blockquote></details>

Hover part is more work than gain.
mask comment now visible
there is that encoded content issue it will address thie number of blocks
DD:MM:SS done
Changing the semester or clicking on the checkboxes now have effect
Edit button working
Only proposal code is linked it has it's own page
default value for cutting power set but I am not using it anywhere (To discuss) 
Ahhh :-) you noticed that  
___
*[src/app/mos/mos.component.html, line 7 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx9r2SW-iFgxkmhOsJ8:-MxJIrANAp49X5f4-c57:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/mos/mos.component.html#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What if there are no such masks?
</blockquote></details>

Done.
___
*[src/app/mos/mos.component.html, line 21 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx9rEeZ3vXbHU6_3O75:-Mxi9RH-3tyQqxBbojR0:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/mos/mos.component.html#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not convinced that is the best solution. Users should still be able to change the semester; you just should make sure the correct content is shown afterwards. (This applies to the other input components as well.)

And we should chat about the indication of loading, please.
</blockquote></details>

Done.
___
*[src/app/mos/mos.component.html, line 129 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx9wmHg4t3CCpiIXk49:-Mxi9SJn5LKW-EQeEyMx:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/mos/mos.component.html#L129)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be good if pressing the Esc key closed the modal as well.
</blockquote></details>

Done.
___
*[src/app/mos/mos.component.scss, line 61 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx9xkvz3s08kdhDesLC:-MxETAVx1qEIgSQU-HWJ:b-juksbo) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/mos/mos.component.scss#L61)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we talk about this?
</blockquote></details>

yes we can
___
*[src/app/mos/mos.component.ts, line 55 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-JY473CPDF4vWs1do:-Mx3Sosm2kM1S7YzUTiQ:b-2lb5r9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/mos/mos.component.ts#L55)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But wouldn't that include _every_ semester other than the next one?
</blockquote></details>

this is what I need to do remove next semester if it is in the list
___
*[src/app/mos/mos.component.ts, line 60 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-Jg3P7_DPhZsis-Mw:-Mx3SzCu2d_nxS7YebAg:b-d5m51x) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/mos/mos.component.ts#L60)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But wouldn't that include _every_ semester other than the previous one?
</blockquote></details>

This is what I need to do remove previous semester if it is in the list
___
*[src/app/mos/mos.component.ts, line 103 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-K9O4EK8pHyNC7KLI:-Mx3TNLP-2Gf0I7kR4cW:bb18k1c) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/mos/mos.component.ts#L103)):*
<details><summary><i>Previously, hettlage wrote…< [...]

2022-03-09 19:36 UTC, hettlage requested changes
> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: all files reviewed, 25 unresolved discussions (waiting on @saltastroops)

___
*[src/styles.scss, line 162 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxiGYGa77s28k14npvf:-MxiGYGa77s28k14npvg:b-gwkthj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/styles.scss#L162)):*
> ```SCSS
> }
> 
> .is-ready-mask-background {
> ```

Just wondering... Shouldn't these CSS rules rather be in the styles.css for the component?
___
*[src/test.ts, line 25 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx9qaCS14Wrm5YogcWd:-MxiHMoT53jPTfXXsCwC:be0f05k) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/test.ts#L25)):*
It might not... Here is what I found (https://dev.to/this-is-angular/improving-angular-tests-by-enabling-angular-testing-module-teardown-38kh):

> In Angular versions 12.1 and 12.2, ModuleTeardownOptions#destroyAfterEach has a default value of false. In Angular version 13.0 and later, its default value is true.
___
*[src/app/mos/mos.component.html, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-9TKdEXYosVuMwx7J:-MxiN8Q71YVwZxuVQm97:bm95c02) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/mos/mos.component.html#L1)):*
<details><summary><i>Previously, saltastroops wrote…</i></summary><blockquote>

Hover part is more work than gain.
mask comment now visible
there is that encoded content issue it will address thie number of blocks
DD:MM:SS done
Changing the semester or clicking on the checkboxes now have effect
Edit button working
Only proposal code is linked it has it's own page
default value for cutting power set but I am not using it anywhere (To discuss) 
Ahhh :-) you noticed that  
</blockquote></details>

I'm not entirely convinced it is an encoded content issue?

Trying to upload mask details gives a 404 error, and the popup window stays open. However, the changes is shown in the table, which is a bit misleading. Also, invalid dates are accepted.

And new ones:

The background colour of block SMC_3 is incorrect.

The choice for the semester(s) should be remembered across page reloads (i.e. stored in localStorage).

The block should still be linked, though. Not necessarily in this PR, but then there should be an issue for it.
___
*[src/app/mos/mos.component.html, line 128 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxiMX0U-O5cjJjjcNYt:-MxiMX0U-O5cjJjjcNYu:bpic5vd) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/mos.component.html#L128)):*
> ```HTML
>   ></wm-displayed-mos-block-table>
> 
>   <div *ngIf="error">
> ```

The handling of failing mos block queries could be improved:

* The error message should be above the table
* The currently displayed proposals should be removed.
___
*[src/app/mos/mos.component.ts, line 32 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxjDjtE1Jn3rL4puMen:-MxjDjtE1Jn3rL4puMeo:b-u28waj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/mos/mos.component.ts#L32)):*
> ```XML
>   ngOnInit(): void {
>     forkJoin([
>       this.mosService.getMosBlock([currentSemester()]),
> ```

The semester(s) should be remembered across page reloads.

Because of debouncing and cancelling of previous requests, you probably have to use _one_ stream for querying MOS blocks in this class. This would imply not using forkJoin. And this in turn raises the question whether maybe you could not have the required masks content in its own component.
___
*[src/app/mos/mos.component.ts, line 57 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxjAc2z0-nYxZ4qJ9Il:-MxjAc2z0-nYxZ4qJ9Im:b-y7j0cn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/mos.component.ts#L57)):*
> ```XML
> 
>   filterBlocksForDisplay(): void {
>     const raMinimumEl = <HTMLInputElement>document.getElementById('raMinimum')
> ```

I'd argue that GUI concerns are leaking into this file here... Can we chat about this?
___
*[src/app/mos/mos.component.ts, line 63 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mxj7QBH-uDqTAr31IxU:-Mxj7QBJ4c8_mBw4XOtf:b-vtxv4d) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/mos.component.ts#L63)):*
> ```XML
>     const piSurnameEl = <HTMLInputElement>document.getElementById('piSurname')
> 
>     const minRa = Number(raMinimumEl.value) || 0;
> ```

There is a problem: RAs are output as h:mm:ss, but you expect degrees for the filter value.
___
*[src/app/mos/mos.component.ts, line 84 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxjBWGM78EqUGrSrjth:-MxjBWGM78EqUGrSrjti:b-7o8p8u) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/mos.component.ts#L84)):*
> ```XML
>   }
> 
>   queryMosBlock(): void {
> ```

queryMosBlock > queryMosBlocks
___
*[src/app/mos/mos.component.ts, line 88 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxjBGoK9_c1GQ8PcZwQ:-MxjBGoK9_c1GQ8PcZwR:b-y7j0cn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/mos.component.ts#L88)):*
> ```XML
>     this.loading = true;
>     let semesters = [this.selectedSemester]
>     const includeNextSemesterEl = <HTMLInputElement>document.getElementById('includeNextSemester')
> ```

I'd argue that GUI concerns are leaking into this file here... Can we chat about this?
___
*[src/app/mos/mos.component.ts, line 98 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxjBd8i3178GKusHWWG:-MxjBd8i3178GKusHWWH:bz0mpli) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/mos.component.ts#L98)):*
> ```XML
>     }
> 
>     this.mosService.getMosBlock(semesters).subscribe(
> ```

getMosBlock > getMosBlocks
___
*[src/app/mos/mos.component.ts, line 98 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxjCbCS2n8a5FQFEOQU:-MxjCbCS2n8a5FQFEOQV:b42a9w5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/mos.component.ts#L98)):*
> ```XML
>     }
> 
>     this.mosService.getMosBlock(semesters).subscribe(
> ```

You should include debouncing and cancelling (read: switchMap).
___
*[src/app/mos/displayed-mos-block-table/displayed-mos-block-table.component.html, line 1 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxjGQMX6nQqyscdrjD-:-MxjGQMX6nQqyscdrjD0:b-fp76xe) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/displayed-mos-block-table/displayed-mos-block-table.component.html#L1)):*
> ```HTML
> <div style="position: relative">
> ```

Why do you call this displayed-mos-block-table rather than just mos-blocs-table (and maybe it should be "blocks" rather than "block"?).
___
*[src/app/mos/displayed-mos-block-table/displayed-mos-block-table.component.html, line 5 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mxk5vXsEkUOAS15YVpB:-Mxk5vXsEkUOAS15YVpC:b-20zid) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/displayed-mos-block-table/displayed-mos-block-table.component.html#L5)):*
> ```HTML
>       <wm-loading-spinner></wm-loading-spinner>
>     </div>
>   <div class="modal" [ngClass]="isModalActive ? 'is-active' : ''"  [...]

2022-03-15 12:44 UTC, saltastroops reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: all files reviewed, 25 unresolved discussions (waiting on @hettlage)

___
*[src/styles.scss, line 162 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxiGYGa77s28k14npvf:-MxmrW6n8T5AVyLiRAUj:b122vyd) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/styles.scss#L162)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Just wondering... Shouldn't these CSS rules rather be in the styles.css for the component?
</blockquote></details>

This stlyes only appy to this component
___
*[src/test.ts, line 25 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx9qaCS14Wrm5YogcWd:-MyCasxK8SDM4twVw_CV:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/test.ts#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might not... Here is what I found (https://dev.to/this-is-angular/improving-angular-tests-by-enabling-angular-testing-module-teardown-38kh):

> In Angular versions 12.1 and 12.2, ModuleTeardownOptions#destroyAfterEach has a default value of false. In Angular version 13.0 and later, its default value is true.
</blockquote></details>

Done.
___
*[src/app/mos/mos.component.html, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-9TKdEXYosVuMwx7J:-My6syPO-Zw3xi1i54hf:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/mos/mos.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not entirely convinced it is an encoded content issue?

Trying to upload mask details gives a 404 error, and the popup window stays open. However, the changes is shown in the table, which is a bit misleading. Also, invalid dates are accepted.

And new ones:

The background colour of block SMC_3 is incorrect.

The choice for the semester(s) should be remembered across page reloads (i.e. stored in localStorage).

The block should still be linked, though. Not necessarily in this PR, but then there should be an issue for it.
</blockquote></details>

Done.
___
*[src/app/mos/mos.component.html, line 128 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxiMX0U-O5cjJjjcNYt:-Mxmskxl0w-THG-epkMf:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/mos.component.html#L128)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The handling of failing mos block queries could be improved:

* The error message should be above the table
* The currently displayed proposals should be removed.
</blockquote></details>

Done.
___
*[src/app/mos/mos.component.ts, line 32 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxjDjtE1Jn3rL4puMen:-Mxt05S98ZYWEz1fz9LB:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b2e60f966e61bf73035837f55775a940ccdbbf1d/src/app/mos/mos.component.ts#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The semester(s) should be remembered across page reloads.

Because of debouncing and cancelling of previous requests, you probably have to use _one_ stream for querying MOS blocks in this class. This would imply not using forkJoin. And this in turn raises the question whether maybe you could not have the required masks content in its own component.
</blockquote></details>

Done.
___
*[src/app/mos/mos.component.ts, line 57 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxjAc2z0-nYxZ4qJ9Il:-My7Gxr11KkgQp07wI5W:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/mos.component.ts#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd argue that GUI concerns are leaking into this file here... Can we chat about this?
</blockquote></details>

Done.
___
*[src/app/mos/mos.component.ts, line 63 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mxj7QBH-uDqTAr31IxU:-MyCDeA1EBlAoOOlqCUh:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/mos.component.ts#L63)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is a problem: RAs are output as h:mm:ss, but you expect degrees for the filter value.
</blockquote></details>

Done.
___
*[src/app/mos/mos.component.ts, line 84 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxjBWGM78EqUGrSrjth:-Mxmt0iM4OrumHJghzgx:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/mos.component.ts#L84)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

queryMosBlock > queryMosBlocks
</blockquote></details>

Done.
___
*[src/app/mos/mos.component.ts, line 88 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxjBGoK9_c1GQ8PcZwQ:-MyCDlQDD4ODsh4PaCXZ:b-kk3ut2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/mos.component.ts#L88)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd argue that GUI concerns are leaking into this file here... Can we chat about this?
</blockquote></details>

solved
___
*[src/app/mos/mos.component.ts, line 98 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxjBd8i3178GKusHWWG:-Mxmt2904HOiUpeIx8_0:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/mos.component.ts#L98)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

getMosBlock > getMosBlocks
</blockquote></details>

Done.
___
*[src/app/mos/mos.component.ts, line 98 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxjCbCS2n8a5FQFEOQU:-MyCGvvJ8J8iSijg8RGn:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/mos.component.ts#L98)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should include debouncing and cancelling (read: switchMap).
</blockquote></details>

Done.
___
*[src/app/mos/displayed-mos-block-table/displayed-mos-block-table.component.html, line 1 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxjGQMX6nQqyscdrjD-:-Mxmtg3n9LTk4HsAMa-b:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/displayed-mos-block-table/displayed-mos-block-table.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you call this displayed-mos-block-table rather than just mos-blocs-table (and maybe it should be "blocks" rather than "block"?).
</blockquote></details>

Done.
___
*[src/app/mos/displayed-mos-block-table/displayed-mos-block-table.component.html, line 5 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mxk5vXsEkUOAS15YVpB:-Mxnil4J2GAkOYVVQdcb:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/displayed-mos-block-table/displayed-mos-block-table.component.html#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`(keyup.escape)="onEscKeyPress()"` should be unnecessary.
</blockquote></details>

Done.
___
*[src/app/mos/displayed-mos-block-table/displayed-mos-block-table.component.html, line 9 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxjGkIyEYeqQTCRjCDm:-MyCGyTACtPeTEJGANah:b-89 [...]

2022-03-16 14:24 UTC, hettlage requested changes
> Reviewed 22 of 22 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: all files reviewed, 40 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[src/styles.scss, line 162 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxiGYGa77s28k14npvf:-MyH5MMeE-GadOI406Rv:b-h5fyck) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/styles.scss#L162)):*
<details><summary><i>Previously, saltastroops wrote…</i></summary><blockquote>

This stlyes only appy to this component
</blockquote></details>

But then why are they included in the global styles.css file?
___
*[src/app/app.component.ts, line 30 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyH5wBr1Yakya1jwxig:-MyH5wBr1Yakya1jwxih:bftmz87) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/app.component.ts#L30)):*
> ```XML
> 
>   @HostListener('window:beforeunload', ['$event'])
>   beforeunloadHandler(): void {
> ```

I think at the previous/next semester option don't have to be removed.

And rather than removing an option here, you might consider using session storage.
___
*[src/app/utils.ts, line 217 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyH6Zo2CV-8jXhabxTW:-MyH6Zo2CV-8jXhabxTX:bp2arlq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.ts#L217)):*
> ```XML
> 
> export function convertHMSToDegrees(input: string) {
>   var parts = input.split(":");
> ```

This could be more user friendly: you could split by anything other than a digit or dot or sign.
___
*[src/app/utils.ts, line 218 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyH9yrL4YmMhFN9p3iF:-MyH9yrL4YmMhFN9p3iG:b834zur) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.ts#L218)):*
> ```XML
> export function convertHMSToDegrees(input: string) {
>   var parts = input.split(":");
>   const hours = Number(parts[0]) || 0;
> ```

I don't think that Number(s) is false if s is undefined.

Also, shouldn't you rather raise an error if the string is empty?
___
*[src/app/utils.ts, line 225 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHAiiM5nybHTJWyZwr:-MyHAiiM5nybHTJWyZws:b-wyuwdy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.ts#L225)):*
> ```XML
>     throw new Error("Hours can not be less than 0");
>   }
> ```

Everywhere here:

can not > cannot

greater than > greater than or qual to
___
*[src/app/utils.spec.ts, line 64 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyEHJdk0dFGScz9P7hW:-MyEHJdk0dFGScz9P7hX:bkild6k) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.spec.ts#L64)):*
> ```XML
>   });
> 
>   it("should raise an error for a negative degrees value", () => {
> ```

Incorrect description
___
*[src/app/utils.spec.ts, line 85 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyEHXAc1aRLwmzoaQVw:-MyEHXAc1aRLwmzoaQVx:b-8j9vrw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.spec.ts#L85)):*
> ```XML
> 
>   it("should raise an error for minutes greater or equal to 60", () => {
>     expect(() => convertHMSToDegrees("12:60:30")).toThrowError(/not be greater than 60/);
> ```

Shouldn't that be /not greater than or equal to 60/?
___
*[src/app/utils.spec.ts, line 89 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyEHmaFEN07-PvzDQQY:-MyEHmaFEN07-PvzDQQZ:b-8j9vrw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.spec.ts#L89)):*
> ```XML
> 
>   it("should raise an error for seconds greater or equal to 60", () => {
>     expect(() => convertHMSToDegrees("12:30:60")).toThrowError(/not be greater than 60/);
> ```

Shouldn't that be /not greater than or equal to 60/?
___
*[src/app/mos/mos.component.html, line 54 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHCywwAGot1jy_fNiT:-MyHCywx8hgiMxFTvM8B:b-idp3cz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos.component.html#L54)):*
> ```HTML
>         </label>
>       </div>
>       <table class="table tabler">
> ```

(What does tabler mean?)
___
*[src/app/mos/mos.component.html, line 112 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHIZHmBa5jKkMycXra:-MyHIZHmBa5jKkMycXrb:b-940ehg) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos.component.html#L112)):*
> ```HTML
>             </p>
>           </td>
>           <td>h:m:s</td>
> ```

Maybe better hh:mm:ss?
___
*[src/app/mos/mos.component.ts, line 56 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHWmak2yyD8VoY-7_I:-MyHWmak2yyD8VoY-7_J:bttqzrt) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos.component.ts#L56)):*
> ```XML
>       selectedSemesters.push(previousSemesterOf(this.selectedSemester));
>     }
>       this.mosService.getMosBlock(selectedSemesters).subscribe(
> ```

Isn't that duplicating code from queryMosBlocks?

Also, you might have issues with debouncing etc. if you have to distinct streams.

And from what I remember you might have to unsubscribe the the component is destroyed?
___
*[src/app/mos/mos.component.ts, line 138 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHYGha94CwGwT8FMs9:-MyHYGha94CwGwT8FMsA:btov90h) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos.component.ts#L138)):*
> ```XML
>   includeSemester(name: string, checked: boolean): void {
>     localStorage.setItem(name, checked.toString());
>     this.displayedMosBlocks = [];
> ```

There is a bit of inconsistency: In some cases you remove the existing blocks before making the MOS query, in others you don't.
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.ts, line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHfi_LDLJZiyvVxPPm:-MyHfi_MBrLKphrCbChi:bbsmqtl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos-blocks-table/mos-blocks-table.component.ts#L1)):*
> ```XML
> import {Component, Input, OnInit} from '@angular/core';
> ```

It seems the number of rows for 2021-2-SCI-023 still differs in the old and new WM? And for semester 2021-1 there re differences in row numbers and backgrounds.
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.ts, line 15 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHbIJ4ACpyLYA0VQYd:-MyHbIJ4ACpyLYA0VQYe:btucvo4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos-blocks-table/mos-blocks-table.component.ts#L15)):*
> ```XML
>   @Input() loading!: boolean;
>   @Input() mosBlocks: MosBlock[] = [];
>   @Input() requiredMosMasks!: string[];
> ```

I think the way required MOS masks are handled needs discussion.
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.ts, line 32 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHb_hl3h8MCx1yx5Mg:-MyHb_hl3h8MCx1yx5Mh:bv9ra8t) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos-blocks-table/mos-blocks-table.component.ts#L32)):*
> ```XML
>       },
>       () => {
>         this.mosBlockE [...]

2022-03-22 14:48 UTC, saltastroops reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: 69 of 86 files reviewed, 40 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[src/styles.scss, line 162 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxiGYGa77s28k14npvf:-MyLptYc-6kgK_I1xGr2:buk52ce) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/styles.scss#L162)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But then why are they included in the global styles.css file?
</blockquote></details>

ahh sorry it is used by two componets the legend and the table
___
*[src/app/app.component.ts, line 30 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyH5wBr1Yakya1jwxig:-MyLqT_Z-bO0LCTz62XK:b-9czaiv) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/app.component.ts#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think at the previous/next semester option don't have to be removed.

And rather than removing an option here, you might consider using session storage.
</blockquote></details>

removed 
rememberd about session storage after submission.
but hey it didn't slept though
___
*[src/app/utils.ts, line 217 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyH6Zo2CV-8jXhabxTW:-MyS9F-J0ce57UUoI0K7:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.ts#L217)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This could be more user friendly: you could split by anything other than a digit or dot or sign.
</blockquote></details>

Done.
___
*[src/app/utils.ts, line 218 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyH9yrL4YmMhFN9p3iF:-MyS9jzL9N8Cwib7W50g:bd8d18h) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.ts#L218)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think that Number(s) is false if s is undefined.

Also, shouldn't you rather raise an error if the string is empty?
</blockquote></details>

the method is called on key up  Error is raised
but I do not understand the first part
___
*[src/app/utils.ts, line 225 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHAiiM5nybHTJWyZwr:-MySBBka4aK7KBiQXztC:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.ts#L225)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Everywhere here:

can not > cannot

greater than > greater than or qual to
</blockquote></details>

Done.
___
*[src/app/utils.spec.ts, line 64 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyEHJdk0dFGScz9P7hW:-MySBQYkErQiK-16GrCJ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.spec.ts#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Incorrect description
</blockquote></details>

Done.
___
*[src/app/utils.spec.ts, line 85 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyEHXAc1aRLwmzoaQVw:-MySBdSj7KNIQ8NgItWG:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.spec.ts#L85)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't that be /not greater than or equal to 60/?
</blockquote></details>

Done.
___
*[src/app/utils.spec.ts, line 89 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyEHmaFEN07-PvzDQQY:-MySBdrM5_Q790nyx6Q9:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.spec.ts#L89)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't that be /not greater than or equal to 60/?
</blockquote></details>

Done.
___
*[src/app/mos/mos.component.html, line 54 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHCywwAGot1jy_fNiT:-MySBjk_62KXRghgTZLz:b8k1ccy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos.component.html#L54)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

(What does tabler mean?)
</blockquote></details>

forgot to remove was trying something else
___
*[src/app/mos/mos.component.html, line 112 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHIZHmBa5jKkMycXra:-MySBwEqCDKx6_2F1GTk:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos.component.html#L112)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better hh:mm:ss?
</blockquote></details>

Done.
___
*[src/app/mos/mos.component.ts, line 56 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHWmak2yyD8VoY-7_I:-MylKFqN3a38FY55BDTX:bnae7g8) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos.component.ts#L56)):*
> Isn't that duplicating code from queryMosBlocks?
=> Fixed.

> Also, you might have issues with debouncing etc. if you have to distinct streams.
=> can you please explin what the issue can be currently

> And from what I remember you might have to unsubscribe the the component is destroyed?
=>  Done
___
*[src/app/mos/mos.component.ts, line 138 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHYGha94CwGwT8FMs9:-MySR5boEl59q-Ku2e6S:bjzimeg) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos.component.ts#L138)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is a bit of inconsistency: In some cases you remove the existing blocks before making the MOS query, in others you don't.
</blockquote></details>

I only found one case done
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.ts, line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHfi_LDLJZiyvVxPPm:-MylKdJwBbTT_xS80mDi:b-bggr25) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos-blocks-table/mos-blocks-table.component.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It seems the number of rows for 2021-2-SCI-023 still differs in the old and new WM? And for semester 2021-1 there re differences in row numbers and backgrounds.
</blockquote></details>

This issue needs to be fixed from the backend the API returns wrong number of blocks
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.ts, line 15 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHbIJ4ACpyLYA0VQYd:-MySC80S5PuAL_r8KzK8:b5yuyjx) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos-blocks-table/mos-blocks-table.component.ts#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the way required MOS masks are handled needs discussion.
</blockquote></details>

Yes we need to discuss this
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.ts, line 32 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHb_hl3h8MCx1yx5Mg:-MySCGwa31_DdZmc5KVw:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos-blocks-table/mos-blocks-table.component.ts#L32)):*
<detail [...]

2022-04-04 11:45 UTC, saltastroops reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: all files reviewed, 25 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[src/app/utils.ts, line 218 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyH9yrL4YmMhFN9p3iF:-MzEh_8Q-AARj7thMNOH:b62noji) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.ts#L218)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The question is what, say, `Number('abc')` is. It is NaN, and this is not a false value. So you can end up with, say, `hours` being 
</blockquote></details>

Did some thing have a look
___
*[src/app/utils.ts, line 217 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MypeoKz1FGRZqRYoJ33:-Mz0_XXO9mJGmgIrZj8r:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/utils.ts#L217)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should also check for other errors. For example, "::", "5:" or ":5" should be invalid.
</blockquote></details>

Done.
___
*[src/app/utils.ts, line 220 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MypeU7QB3Silh07G42F:-Mz04W3i0ME5D_6PfgGb:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/utils.ts#L220)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you include the pipe symbol in this list?
</blockquote></details>

removed
___
*[src/app/utils.ts, line 260 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MypgwR62Aaav3wrIS8v:-Mz06aDG4QbC4L64Rx8r:bln3wa7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/utils.ts#L260)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Did you copy this from somewhere? If so, you should include a link to the source.

I have my doubts the code is working, though. The `unsubscribe` method is called on a `Subscription`, but a `Subscription` does not seem to have a `subscribe` method.

Also, if the component contains an `ngOnDestroy` method, its functionality would get lost.
</blockquote></details>

please have a look at https://blog.bitsrc.io/6-ways-to-unsubscribe-from-observables-in-angular-ab912819a78f
5. Use Decorator to automate Unsubscription
___
*[src/app/utils.spec.ts, line 64 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyEHJdk0dFGScz9P7hW:-Mz0eLS6CFR72Tut2gcG:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.spec.ts#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: "should give the correct result"?

(And you might include an example with non-zero minutes and seconds and well.)
</blockquote></details>

Done.
___
*[src/app/utils.spec.ts, line 81 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mypiw0Y4vFMbG0atl1N:-Mz06xg61PwC1vuG7DTS:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.spec.ts#L81)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

A test case to consider would be 24:00:00.
</blockquote></details>

Done.
___
*[src/app/utils.spec.ts, line 85 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyEHXAc1aRLwmzoaQVw:-Mz076uS58mfXZ-ddW08:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.spec.ts#L85)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ah sorry, that was referring solely to the error message. The description should rather one something like "should raise an error for minutes greater than or equal to 60".
</blockquote></details>

Done.
___
*[src/app/mos/mos.component.ts, line 98 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MxjCbCS2n8a5FQFEOQU:-Mz07I8a-8KsL6WSCEg7:ba0vplo) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8de24185c2916883fe6f81dbda87c6224624475d/src/app/mos/mos.component.ts#L98)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not so sure about the "done". Maybe a quick chat would help?
</blockquote></details>

yes we can chat
___
*[src/app/mos/mos.component.ts, line 138 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHYGha94CwGwT8FMs9:-Mz07wqY4TC0IHKW01Kl:b-886gsx) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos.component.ts#L138)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Actually... shouldn't the queryMosBlocks method take care of removing the displayed blocks?
</blockquote></details>

Fixed
___
*[src/app/mos/mos.component.ts, line 96 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MypnOoW4shLpw5WCj-Y:-MzoDixq0APeANu3SiH2:b-at22t1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/mos/mos.component.ts#L96)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Have you checked this in the old WM? What about blocks which are on hold?
</blockquote></details>

fixed from api now
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 67 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyrAuMMDCcwMwzOn-or:-Mz0Dxpf01cygcDIlGAj:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L67)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wrong alt text
</blockquote></details>

Done.
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 74 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyrAyjsB0RaDHJPktOt:-Mz0DyEnEpo2utjjaVEd:b-7ql1td) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L74)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wrong alt text
</blockquote></details>

fixed
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 90 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyrB1le1II2iJsURJDF:-Mz0DzUjDr24euFvS7mo:b-7ql1td) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L90)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wrong alt text
</blockquote></details>

fixed
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 98 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyrB5sT5y4sZBlV1WyO:-Mz0E-uxDCUzTr1vJXzV:b-7ql1td) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L98)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wrong alt text
</blockquote></details>

fixed
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.ts, line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHfi_LDLJZiyvVxPPm:-Mz0EJyq5ZZeicAsjAPG:br3odal) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos-blocks-table/mos-blocks-table.component.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i> [...]

2022-04-05 09:24 UTC, hettlage requested changes
> Reviewed 16 of 16 files at r6, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: all files reviewed, 20 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[src/app/utils.ts, line 260 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MypgwR62Aaav3wrIS8v:-MzobX6GEOVC4E1twbzJ:bovqw14) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/utils.ts#L260)):*
<details><summary><i>Previously, saltastroops wrote…</i></summary><blockquote>

please have a look at https://blog.bitsrc.io/6-ways-to-unsubscribe-from-observables-in-angular-ab912819a78f
5. Use Decorator to automate Unsubscription
</blockquote></details>

Okay, I missed the part about calling the original destructor.

But I still believe that the code doesn't work, and I strongly suspect that `property.subscribe` really is supposed to be `property.unsubscribe`.
___
*[src/app/utils.ts, line 224 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzoZDF5AZnJGXe0MP62:-MzoZDF5AZnJGXe0MP63:bbqj2og) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ac1df33c319b47faf1a45e45334e0ce07aabd862/src/app/utils.ts#L224)):*
> ```XML
>     throw Error("Right ascension should not be an empty string.")
>   }
>   if(/[:,.; "']/.test(input[0]) || /[:,.; "']/.test(input.slice(-1))){
> ```

This still leaves loopholes, though (such as 5::9 or 12.5.0.9). The better bet might be to use a regular expression, something like:

/^[+-]\d{1,2}(([:,.; "']\d{2})?[:,.; "']\d{2}(\.\d*)?)?/
___
*[src/app/utils.ts, line 236 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mzoa-s9CPM6Qv26m9W0:-Mzoa-s9CPM6Qv26m9W1:beiuyr0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ac1df33c319b47faf1a45e45334e0ce07aabd862/src/app/utils.ts#L236)):*
> ```XML
>   }
> 
>   if (isNaN(hours) || isNaN(minutes) || isNaN(seconds)){
> ```

This should be unnecessary if you catch such issues with a regex above already.
___
*[src/app/utils.spec.ts, line 64 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyEHJdk0dFGScz9P7hW:-MzofVDq3gq5JcY9dkNQ:b-sbz8ny) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.spec.ts#L64)):*
<details><summary><i>Previously, saltastroops wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see any change?
___
*[src/app/utils.spec.ts, line 53 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzofH1V4I7Kqva4tCS3:-MzofH1V4I7Kqva4tCS4:b8cghlm) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ac1df33c319b47faf1a45e45334e0ce07aabd862/src/app/utils.spec.ts#L53)):*
> ```XML
> describe("Unit test for hours:minutes:seconds to angle (degrees) conversion functions ", () => {
>   it("It should work", () => {
>     expect(convertHMSToDegrees("0:10:10")).toEqual(2.5416666666666665);
> ```

Comparing floats with `toEqual` is not ideal. See

https://jestjs.io/docs/expect#expectclosetonumber-numdigits

for a better option.
___
*[src/app/utils.spec.ts, line 85 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mzof_ysAu5PIboK6xTY:-Mzof_ysAu5PIboK6xTZ:b-2voqbe) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ac1df33c319b47faf1a45e45334e0ce07aabd862/src/app/utils.spec.ts#L85)):*
> ```XML
>     expect(() => convertHMSToDegrees("-04:00:00.00")).toThrowError(/less than 0/);
>   });
>   it("should raise for an invalid format", () => {
> ```

raise > raise an error

Also https://dev.to/tinesoft/be-smart-write-parameterized-tests-with-jest-3eab might be of interest.
___
*[src/app/home/home-user/home-user.component.html, line 95 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzsgqX_7jfDlr9B1dnT:-MzsgqX_7jfDlr9B1dnU:bef3jp9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f95717185629b64ee35d05719217248e5148e6e7/src/app/home/home-user/home-user.component.html#L95)):*
> ```HTML
>       data-test="single-semester"
>     />
>     Show proposals for the selected Semester
> ```

Semester > semester
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 90 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyrB1le1II2iJsURJDF:-MzoklDsAiVFlHr0iahs:b-sbz8ny) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L90)):*
<details><summary><i>Previously, saltastroops wrote…</i></summary><blockquote>

fixed
</blockquote></details>

I don't see any change?
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 98 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyrB5sT5y4sZBlV1WyO:-Mzokobz7OuR9fADfuCI:b-sbz8ny) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L98)):*
<details><summary><i>Previously, saltastroops wrote…</i></summary><blockquote>

fixed
</blockquote></details>

I don't see any change?
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 50 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzoiLu62EVRILNpyQDg:-MzoiLu62EVRILNpyQDh:b-rmeqcz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ac1df33c319b47faf1a45e45334e0ce07aabd862/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L50)):*
> ```HTML
>               class="icon is-small"
>               src="/assets/icons/noun_tick_2836262-green.svg"
>               alt="The mask in the magazine"
> ```

mask > mask is
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 57 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzoiOq65QKC22yJf6-9:-MzoiOq65QKC22yJf6-A:b-rmeqcz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ac1df33c319b47faf1a45e45334e0ce07aabd862/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L57)):*
> ```HTML
>               class="icon is-small"
>               src="/assets/icons/noun_Cross_2120375.svg"
>               alt="The mask not in the magazine"
> ```

mask > mask is
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 78 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mzok_4ZEGvbwvNX2Lwu:-Mzok_4_2h79e2nh1l0e:b-ijtfn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ac1df33c319b47faf1a45e45334e0ce07aabd862/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L78)):*
> ```HTML
>           </ng-template>
>         </td>
>         <td><button [disabled]="loading" class="button" (click)="selectMosBlock(mb); mosModal.openModal(mb); ">Edit</button></td>
> ```

I'm puzzled by the selectedBlock in the modal... Can we chat about this?
___
*[src/app/mos/mos-blocks-table/mos-mask-modal-update/mos-mask-modal-update.component.html, line 18 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzolDgBDUayyP-IXIOV:-MzolDgC4Rj1xlYzKLfN:b66ssry) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ac1df33c319b47faf1a45e45334e0ce07aabd862/src/app/mos/mos-blocks-table/mos-mask-modal-update/mos-mask-modal-update.component.html#L18)):*
> ```HTML
>               #cutBy
>               [value]="mosBlock?.cutBy"
>               (keyup)="updateMosBlock('cutBy', cutBy.value)"
> ```

Maybe (for consistency with the backend) `updateMosMaskMetadata`?
___
*[src/app/mos/mos-blocks-table/mos-mask-modal-update/mos-mask-modal-update.component.ts, line 45 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyI0QxV25nrishZChDW:-MzolfyH1bCpTuxGSY5V:b-1h7ydx) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos-blocks-table/m [...]

2022-04-05 11:49 UTC, saltastroops reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: all files reviewed, 20 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[src/app/utils.ts, line 260 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MypgwR62Aaav3wrIS8v:-MztMU7GAdeQVPMiZKKl:bm7f7ol) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/utils.ts#L260)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Okay, I missed the part about calling the original destructor.

But I still believe that the code doesn't work, and I strongly suspect that `property.subscribe` really is supposed to be `property.unsubscribe`.
</blockquote></details>

you need to explain this to me please
___
*[src/app/utils.spec.ts, line 64 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyEHJdk0dFGScz9P7hW:-MztEaBD0-LskDo_Kgtr:b-q2cv14) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/utils.spec.ts#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see any change?
</blockquote></details>

it is coverd on the test case above it should work I need to use a value which more staight and easy to calculate and we know it by heart.
___
*[src/app/utils.spec.ts, line 53 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzofH1V4I7Kqva4tCS3:-MztQbSR6OTa2--B_nBP:bjqmh1f) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ac1df33c319b47faf1a45e45334e0ce07aabd862/src/app/utils.spec.ts#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Comparing floats with `toEqual` is not ideal. See

https://jestjs.io/docs/expect#expectclosetonumber-numdigits

for a better option.
</blockquote></details>

migth be much faster to expain this.
___
*[src/app/utils.spec.ts, line 85 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mzof_ysAu5PIboK6xTY:-MztUGuIBDRMghO2nlXJ:bmqnwlo) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ac1df33c319b47faf1a45e45334e0ce07aabd862/src/app/utils.spec.ts#L85)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

raise > raise an error

Also https://dev.to/tinesoft/be-smart-write-parameterized-tests-with-jest-3eab might be of interest.
</blockquote></details>

this is jest and I believe we are using jasmine
___
*[src/app/home/home-user/home-user.component.html, line 95 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzsgqX_7jfDlr9B1dnT:-MztF6XkAy-gf6boPRVR:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f95717185629b64ee35d05719217248e5148e6e7/src/app/home/home-user/home-user.component.html#L95)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Semester > semester
</blockquote></details>

Done.
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 90 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyrB1le1II2iJsURJDF:-MztFql-76wkw_zIy2yn:b-a2jkrg) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L90)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see any change?
</blockquote></details>

missed this one
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 98 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyrB5sT5y4sZBlV1WyO:-MztFs_7D809npSBaZSb:bkd7awl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L98)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see any change?
</blockquote></details>

also missed this one
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 50 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzoiLu62EVRILNpyQDg:-MztFHXC-K59LaYcoX3n:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ac1df33c319b47faf1a45e45334e0ce07aabd862/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L50)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

mask > mask is
</blockquote></details>

Done.
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 57 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzoiOq65QKC22yJf6-9:-MztFKD_3WjlNc6UbHS-:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ac1df33c319b47faf1a45e45334e0ce07aabd862/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

mask > mask is
</blockquote></details>

Done.
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.ts, line 37 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyHvt6p3joXmwSZ6Hu7:-MztVlO71UA7aAV0SmZg:bjr9vsr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos-blocks-table/mos-blocks-table.component.ts#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I cannot confirm that. `*ngIf="!mosBlocks?.length" seems to work fine for me.
</blockquote></details>

yes you are correct it is working
___
*[src/app/mos/mos-blocks-table/mos-mask-modal-update/mos-mask-modal-update.component.html, line 18 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzolDgBDUayyP-IXIOV:-MztGHlSA6m-lZgVjrVY:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ac1df33c319b47faf1a45e45334e0ce07aabd862/src/app/mos/mos-blocks-table/mos-mask-modal-update/mos-mask-modal-update.component.html#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe (for consistency with the backend) `updateMosMaskMetadata`?
</blockquote></details>

Done.
___
*[src/app/mos/mos-blocks-table/mos-mask-modal-update/mos-mask-modal-update.component.ts, line 45 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MyI0QxV25nrishZChDW:-MztHqUO--GokNM3q9t0:b7l5ek9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/018940f352cfbed3f8cab809f311b9c60137bf5e/src/app/mos/mos-blocks-table/mos-mask-modal-update/mos-mask-modal-update.component.ts#L45)):*
> updateMosBlock
it is fine
___
*[src/app/mos/mos-blocks-table/mos-mask-modal-update/mos-mask-modal-update.component.ts, line 10 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzolRSYCe2aAW-97GfS:-MztHaJl95VkDyrbOJMs:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/mos/mos-blocks-table/mos-mask-modal-update/mos-mask-modal-update.component.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry, I noticed this only now... Shouldn't this be "mos-mask-update-modal"? And similarly for the class name?
</blockquote></details>

Done.
___
*[src/app/mos/mos-blocks-table/mos-mask-modal-update/mos-mask-modal-update.component.ts, line 87 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzsiR4T2hFoLX0OxIRj:-MztHvzJ5cvnr58-q_sE:bipa4ug) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f95717185629b64ee35d05719217248e5148e6e7/src/app/mos/mos-blocks-table/mos-mask-modal-update/mos-mask-modal-update.component.ts#L87)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What i the difference between `this.mosBlock` and `this.selectedMosBlock`?

Also, it might be safer not to rely on the updated MOS block (still) being selected.
</blockquote></details>

selectedMosblock update the or [...]

2022-04-06 12:14 UTC, saltastroops reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: 77 of 94 files reviewed, 20 unresolved discussions (waiting on @hettlage)

___
*[src/app/utils.ts, line 224 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzoZDF5AZnJGXe0MP62:-Mztc0A50c-N0NfETRYZ:bc6tzpk) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ac1df33c319b47faf1a45e45334e0ce07aabd862/src/app/utils.ts#L224)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This still leaves loopholes, though (such as 5::9 or 12.5.0.9). The better bet might be to use a regular expression, something like:

/^[+-]\d{1,2}(([:,.; "']\d{2})?[:,.; "']\d{2}(\.\d*)?)?/
</blockquote></details>

12:00:32.1
___
*[src/app/utils.ts, line 236 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mzoa-s9CPM6Qv26m9W0:-Mzy8fLf0bmSSNyLCdny:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ac1df33c319b47faf1a45e45334e0ce07aabd862/src/app/utils.ts#L236)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should be unnecessary if you catch such issues with a regex above already.
</blockquote></details>

Done.
___
*[src/app/mos/mos.component.html, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-9TKdEXYosVuMwx7J:-Mzy8hOR3P_SZvuJ1GAW:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/app/mos/mos.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The message about masks not needed any longer should be shown only if there are such masks.

It should also be highlighted (as it is in the old WM).

No masks not needed any longer are shown in the new WM, but there are some in the old WM. I suspect they are from previous semesters. This points to an issue: You cannot reliably get these masks from the results returned by the queryMosBlocks method.

The number of mask blocks is still different in the old and new WM.

If the backend server is down, a Sentry error is triggered.

The choice of semesters is not remembered across page reloads.
</blockquote></details>

Done.
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 78 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mzok_4ZEGvbwvNX2Lwu:-MzxqMauDMstUOWNCiTu:b-7ql1td) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ac1df33c319b47faf1a45e45334e0ce07aabd862/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L78)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm puzzled by the selectedBlock in the modal... Can we chat about this?
</blockquote></details>

fixed


<!-- Sent from Reviewable.io -->

2022-04-06 14:28 UTC, hettlage requested changes
> Reviewed 7 of 11 files at r8, 10 of 10 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: all files reviewed, 9 unresolved discussions (waiting on @saltastroops)

___
*[src/app/utils.ts, line 260 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MypgwR62Aaav3wrIS8v:-MzyyavK4F1d0lhvRhNA:bhp45fv) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/utils.ts#L260)):*
<details><summary><i>Previously, saltastroops wrote…</i></summary><blockquote>

you need to explain this to me please
</blockquote></details>

I know I'm stubborn, but I'm still sure that it must be `unsubscribe` rather than `subscribe` -- and this time I tested it...
___
*[src/app/login/forgot-password/forgot-password.component.ts, line 77 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzyzCC7AkbDfKJ3dGhW:-MzyzCC83HQEDaPnf5oY:b-ur6msk) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/login/forgot-password/forgot-password.component.ts#L77)):*
> ```XML
>     this.showSuccessMessage = false;
>   }
>   ngOnDestroy() {
> ```

Why are you not using the decorator? :-)
___
*[src/app/mos/mos.component.ts, line 144 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzyzMQv9iwS4JEqDB6n:-MzyzMQv9iwS4JEqDB6o:b-ofqw4a) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos.component.ts#L144)):*
> ```XML
>     return whichRa ===  "min" ? 0 : 360
>   }
>   ngOnDestroy() {
> ```

Why are you not using the decorator?
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 89 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzyzbdQ8YlMmm1POPo0:-MzyzbdQ8YlMmm1POPo1:b-u87iwt) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L89)):*
> ```HTML
>       class="icon is-large"
>       src="/assets/icons/noun-zero-document-723179.svg"
>       alt="MOS blocks not found"
> ```

Maybe better: No MOS blocks found
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 97 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzzD7WS72LAVU2e5Qsf:-MzzD7WS72LAVU2e5Qsg:b-y6r9io) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L97)):*
> ```HTML
>       class="icon is-small"
>       src="/assets/icons/noun-zero-document-723179.svg"
>       alt="Fetching MOS blocks raise error"
> ```

May be better: Error

Actually, the alt text suggests using another icon, such as https://thenounproject.com/icon/error-1645402/.
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.ts, line 66 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzzDmE49mnaWQsu-w_B:-MzzDmE49mnaWQsu-w_C:botreey) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos-blocks-table/mos-blocks-table.component.ts#L66)):*
> ```XML
>   }
> 
>   ngOnDestroy() {
> ```

Why don't you use the decorator?
___
*[src/app/navigation-bar/navigation-bar.component.ts, line 29 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzzF8jLARhDLI_cBwOd:-MzzF8jLARhDLI_cBwOe:bvpx6oq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/navigation-bar/navigation-bar.component.ts#L29)):*
> ```XML
>   logout(): void {
>     this.authService.logout();
>     this.router.navigate(["/login"])
> ```

Maybe redirect to the home page instead?
___
*[src/app/service/mos.service.ts, line 41 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzsqKTH9jQw3_NFdOdQ:-MzzFux5Abjtwf7ZfZem:b-h7l61y) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f95717185629b64ee35d05719217248e5148e6e7/src/app/service/mos.service.ts#L41)):*
<details><summary><i>Previously, saltastroops wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Notre that from all I know you can just pass the query parameters as an object (rather having to create an HttpParams object.
___
*[src/app/mos/mos-blocks-table/mos-mask-update-modal/mos-mask-update-modal.component.ts, line 118 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzzEsDSEko3S5fukSUv:-MzzEsDSEko3S5fukSUw:botreey) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos-blocks-table/mos-mask-update-modal/mos-mask-update-modal.component.ts#L118)):*
> ```XML
>   }
> 
>   ngOnDestroy() {
> ```

Why don't you use the decorator?


<!-- Sent from Reviewable.io -->

2022-04-06 17:52 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: all files reviewed, 9 unresolved discussions (waiting on @saltastroops)

___
*[src/app/utils.ts, line 260 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MypgwR62Aaav3wrIS8v:-N---1eY5MJT0j8ICFBO:b-rq73hq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/utils.ts#L260)):*
<details><summary><i>Previously, saltastroops wrote…</i></summary><blockquote>

this is not called for me that is why I removed the Decorator
</blockquote></details>

It actually *is* called. :-)
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 89 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzyzbdQ8YlMmm1POPo0:-N---FlS54UmbeqUd2uU:b-m7e5nr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L89)):*
<details><summary><i>Previously, saltastroops wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I see no change?
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 97 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzzD7WS72LAVU2e5Qsf:-N---M3gBpFIiJW5fT7y:b-m7e5nr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L97)):*
<details><summary><i>Previously, saltastroops wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I see no change?
___
*[src/app/navigation-bar/navigation-bar.component.ts, line 29 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzzF8jLARhDLI_cBwOd:-N---OhzAsVLK047tQ9Y:b-m7e5nr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/navigation-bar/navigation-bar.component.ts#L29)):*
<details><summary><i>Previously, saltastroops wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I see no change?
___
*[src/app/service/mos.service.ts, line 41 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzsqKTH9jQw3_NFdOdQ:-N---Q_B7XKEws8p-Au0:b-m7e5nr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f95717185629b64ee35d05719217248e5148e6e7/src/app/service/mos.service.ts#L41)):*
<details><summary><i>Previously, saltastroops wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I see no change?


<!-- Sent from Reviewable.io -->

2022-04-06 19:22 UTC, saltastroops reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: 85 of 95 files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[src/app/utils.ts, line 260 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MypgwR62Aaav3wrIS8v:-N--J1RjDRCquHgcuCU8:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/357753d082c2ab9b8bd70c639f980f530f2b97ba/src/app/utils.ts#L260)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It actually *is* called. :-)
</blockquote></details>

Done.
___
*[src/app/login/forgot-password/forgot-password.component.ts, line 77 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzyzCC7AkbDfKJ3dGhW:-N--J2fW4NRkSd1FD37Z:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/login/forgot-password/forgot-password.component.ts#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why are you not using the decorator? :-)
</blockquote></details>

removed
___
*[src/app/mos/mos.component.ts, line 144 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzyzMQv9iwS4JEqDB6n:-N--J5Fo1N11eHxPOgYg:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos.component.ts#L144)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why are you not using the decorator?
</blockquote></details>

removed
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 89 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzyzbdQ8YlMmm1POPo0:-N--EyDLCGrq2cEQZxrz:b936x7e) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L89)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I see no change?
</blockquote></details>

forgot to push all changies
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.html, line 97 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzzD7WS72LAVU2e5Qsf:-N--EwXTA_ZKl-Op2IzP:b936x7e) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos-blocks-table/mos-blocks-table.component.html#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I see no change?
</blockquote></details>

forgot to push all changies
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.ts, line 66 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzzDmE49mnaWQsu-w_B:-N--JAz-902g1heRfdEI:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos-blocks-table/mos-blocks-table.component.ts#L66)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why don't you use the decorator?
</blockquote></details>

removed
___
*[src/app/navigation-bar/navigation-bar.component.ts, line 29 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzzF8jLARhDLI_cBwOd:-N--EovmBqa80yafzRKH:b-2dhmj4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/navigation-bar/navigation-bar.component.ts#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I see no change?
</blockquote></details>

forgot to push all changies
___
*[src/app/service/mos.service.ts, line 41 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzsqKTH9jQw3_NFdOdQ:-N--EhR62-cfq-bEou7H:b936x7e) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f95717185629b64ee35d05719217248e5148e6e7/src/app/service/mos.service.ts#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I see no change?
</blockquote></details>

forgot to push all changies
___
*[src/app/mos/mos-blocks-table/mos-mask-update-modal/mos-mask-update-modal.component.ts, line 118 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzzEsDSEko3S5fukSUv:-N--JIIL6v6rK3VifYLv:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos-blocks-table/mos-mask-update-modal/mos-mask-update-modal.component.ts#L118)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why don't you use the decorator?
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2022-04-06 21:37 UTC, hettlage requested changes
> Reviewed 10 of 10 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: all files reviewed, 5 unresolved discussions (waiting on @saltastroops)

___
*[src/app/login/forgot-password/forgot-password.component.ts, line 77 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzyzCC7AkbDfKJ3dGhW:-N--mjaFB-0C_eda5wLS:bnlh5h3) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/login/forgot-password/forgot-password.component.ts#L77)):*
<details><summary><i>Previously, saltastroops wrote…</i></summary><blockquote>

removed
</blockquote></details>

Ahhhh... But I don't think the decorator works if you don't have a property for the subscription.
___
*[src/app/mos/mos.component.ts, line 93 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-N--n0Ta7f0efT4PQpql:-N--n0Ta7f0efT4PQpqm:b852573) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos.component.ts#L93)):*
> ```XML
>     }
> 
>     this.mosBlocksSubscription = this.mosService.getMosBlocks(fromSemester, toSemester).subscribe(
> ```

I don't think the decorator works if you don't have a property for the subscription.
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.ts, line 26 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-N--n9cnBWeMGzoTvct4:-N--n9cnBWeMGzoTvct5:b852573) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos-blocks-table/mos-blocks-table.component.ts#L26)):*
> ```XML
> 
>   ngOnInit(): void {
>     this.mosMasksInMagazineSubscription = this.mosService.getMosMasksInMagazine().subscribe(
> ```

I don't think the decorator works if you don't have a property for the subscription.
___
*[src/app/service/mos.service.ts, line 40 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-N--nWDe6I1H18n2hGiB:-N--nWDe6I1H18n2hGiC:bwefthb) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b12aed03fe2ef4d194522fca4cdccb1ed6f8ef2e/src/app/service/mos.service.ts#L40)):*
> ```XML
>       .get<string[]>(uri );
>   }
>   getObsoleteMosMasks(from_semester: string, to_semester: string): Observable<string[]> {
> ```

In line with another discussion still to have, this might have to be renamed.
___
*[src/app/mos/mos-blocks-table/mos-mask-update-modal/mos-mask-update-modal.component.ts, line 86 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-N--nDRn5cupR_4iSU-V:-N--nDRn5cupR_4iSU-W:b852573) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos-blocks-table/mos-mask-update-modal/mos-mask-update-modal.component.ts#L86)):*
> ```XML
>     }
> 
>     this.updateMosMaskSubscription = this.mosService
> ```

I don't think the decorator works if you don't have a property for the subscription.


<!-- Sent from Reviewable.io -->

2022-04-07 07:45 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: all files reviewed, 5 unresolved discussions (waiting on @saltastroops)

___
*[src/styles.scss, line 162 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-Mx-7AI6AAeRuAUZ_J5V:-Mx3NnR708zDe1OCwCnV:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/973c46982a924c03316daaabfc6f330ad5fb55b5/src/styles.scss#L162)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Your class names include colours, but the actual value is derived from variables with aname that has semantic meaning, which might be unfortunate.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-04-07 07:56 UTC, saltastroops reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: all files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[src/app/login/forgot-password/forgot-password.component.ts, line 77 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-MzyzCC7AkbDfKJ3dGhW:-N-20HIvALiSmKwhGf7Z:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/login/forgot-password/forgot-password.component.ts#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ahhhh... But I don't think the decorator works if you don't have a property for the subscription.
</blockquote></details>

Done.
___
*[src/app/mos/mos.component.ts, line 93 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-N--n0Ta7f0efT4PQpql:-N-20Kk5-aRuDqQWYZ7t:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos.component.ts#L93)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the decorator works if you don't have a property for the subscription.
</blockquote></details>

Done.
___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.ts, line 26 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-N--n9cnBWeMGzoTvct4:-N-201o53Ah2iRDBEANO:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos-blocks-table/mos-blocks-table.component.ts#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the decorator works if you don't have a property for the subscription.
</blockquote></details>

Done.
___
*[src/app/service/mos.service.ts, line 40 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-N--nWDe6I1H18n2hGiB:-N-20TOE61yEhtoCIx9C:b1krd2f) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/b12aed03fe2ef4d194522fca4cdccb1ed6f8ef2e/src/app/service/mos.service.ts#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

In line with another discussion still to have, this might have to be renamed.
</blockquote></details>

we can discuss
___
*[src/app/mos/mos-blocks-table/mos-mask-update-modal/mos-mask-update-modal.component.ts, line 86 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/99#-N--nDRn5cupR_4iSU-V:-N-206Zp2A6AbJ1uvI9B:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/fc13a051c38db41b89320ed66f72ab5c51209890/src/app/mos/mos-blocks-table/mos-mask-update-modal/mos-mask-update-modal.component.ts#L86)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the decorator works if you don't have a property for the subscription.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-07 10:26 UTC, hettlage approved these changes
> Reviewed 8 of 8 files at r11, 34 of 34 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/99)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @saltastroops)



<!-- Sent from Reviewable.io -->

2022-04-07 10:27 UTC, merged